// Class: ReadBDT-0.3_fold10
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.3_fold10
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/00       [401408]
Creator        : htan
Date           : Fri Aug 16 14:19:43 2024
Host           : Linux 6772f6b99311 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May 9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gluster/home/htan/ZTTBDT
Training events: 105014
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
m_pT_asymm                    m_pT_asymm                    m_pT_asymm                    m_pT_asymm                                                      'F'    [1.16390037874e-05,0.946852445602]
m_sigmaCosDelPhi              m_sigmaCosDelPhi              m_sigmaCosDelPhi              m_sigmaCosDelPhi                                                'F'    [-0.049986757338,1.9745773077]
m_ratioMetTauPT               m_ratioMetTauPT               m_ratioMetTauPT               m_ratioMetTauPT                                                 'F'    [0.00113642180804,11.9963302612]
m_ratioMuonTauPT              m_ratioMuonTauPT              m_ratioMuonTauPT              m_ratioMuonTauPT                                                'F'    [0.0272991936654,0.999976694584]
m_ratioMetMuonPT              m_ratioMetMuonPT              m_ratioMetMuonPT              m_ratioMetMuonPT                                                'F'    [0.00152266630903,24.9829425812]
m_ratioMuonTauM3              m_ratioMuonTauM3              m_ratioMuonTauM3              m_ratioMuonTauM3                                                'F'    [0.00183517555706,0.996654033661]
m_ratioMuonMetM3              m_ratioMuonMetM3              m_ratioMuonMetM3              m_ratioMuonMetM3                                                'F'    [1.27644239001e-06,0.249402225018]
m_ratioMetTauM3               m_ratioMetTauM3               m_ratioMetTauM3               m_ratioMetTauM3                                                 'F'    [5.56223167223e-05,0.977119266987]
NSpec 1
m_event_number                m_event_number                m_event_number                I                                                               'F'    [113,1214786176]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.3_fold10Node

#ifndef BDT-0.3_fold10Node__def
#define BDT-0.3_fold10Node__def

class BDT-0.3_fold10Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.3_fold10Node ( BDT-0.3_fold10Node* left,BDT-0.3_fold10Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.3_fold10Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold10Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold10Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.3_fold10Node*   fLeft;     // pointer to the left daughter node
   BDT-0.3_fold10Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.3_fold10Node::~BDT-0.3_fold10Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.3_fold10Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.3_fold10Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.3_fold10 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.3_fold10( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.3_fold10" ),
        fNvars( 8 )
   {
      // the training input variables
      const char* inputVars[] = { "m_pT_asymm", "m_sigmaCosDelPhi", "m_ratioMetTauPT", "m_ratioMuonTauPT", "m_ratioMetMuonPT", "m_ratioMuonTauM3", "m_ratioMuonMetM3", "m_ratioMetTauM3" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.3_fold10() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.3_fold10Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.3_fold10::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.3_fold10Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.3_fold10Node*)current->GetRight();
         else current=(BDT-0.3_fold10Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.3_fold10::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465457,-0.00690869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789401,0.0578803) , 
7, 0.567253, 1, 0, 0.667465,0.167465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340117,-0.0319765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496898,-0.000620374) , 
0, 0.27322, 1, 0, 0.412309,-0.087691) , 
6, 0.0429545, 1, 0, 0.529706,0.0297055)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419667,-0.0142977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.668275,0.0315212) , 
1, -0.0143394, 1, 0, 0.593321,0.0883564) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217656,-0.0548949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442948,-0.0131336) , 
7, 0.551778, 1, 0, 0.333644,-0.166863) , 
1, 0.0240551, 1, 0, 0.494296,-0.00896902)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375593,-0.0219683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.639185,0.0242571) , 
1, -0.0163303, 1, 0, 0.574429,0.064191) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245566,-0.0493411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410985,-0.0128444) , 
6, 0.0520926, 1, 0, 0.331059,-0.15193) , 
1, 0.0739321, 1, 0, 0.513133,0.00975747)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442369,-0.0112507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646055,0.0242117) , 
7, 0.53302, 1, 0, 0.573631,0.0575523) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181176,-0.0556088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39582,-0.0162698) , 
0, 0.27994, 1, 0, 0.284841,-0.181721) , 
1, 0.0986257, 1, 0, 0.504597,0.000355446)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402787,-0.0195452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655054,0.0237982) , 
7, 0.498098, 1, 0, 0.580012,0.0537311) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279897,-0.0400039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422377,-0.00773248) , 
5, 0.697525, 1, 0, 0.3189,-0.154659) , 
1, 0.0249971, 1, 0, 0.483252,-0.0234916)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417554,-0.0132704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228924,-0.0506143) , 
3, 0.819719, 1, 0, 0.348323,-0.133599) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79583,0.0502498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458689,-0.00807097) , 
6, 0.0397653, 1, 0, 0.618435,0.0957392) , 
0, 0.254306, 1, 0, 0.483348,-0.0189557)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247716,-0.0438265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446203,-0.00215458) , 
5, 0.692344, 1, 0, 0.334963,-0.125833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662971,0.023972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412799,-0.0133565) , 
6, 0.0615316, 1, 0, 0.574131,0.0522468) , 
7, 0.470597, 1, 0, 0.509377,0.00403184)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344692,-0.0242818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69164,0.028679) , 
7, 0.518837, 1, 0, 0.639408,0.100595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299932,-0.0322004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517629,0.00796892) , 
5, 0.704038, 1, 0, 0.396572,-0.0700405) , 
3, 0.56824, 1, 0, 0.514093,0.012539)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147028,-0.0677691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445781,-0.0142218) , 
2, 0.602938, 1, 0, 0.322807,-0.17615) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667362,0.0226606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424089,-0.0102468) , 
3, 0.559681, 1, 0, 0.526142,0.0167918) , 
5, 0.501014, 1, 0, 0.493049,-0.0146096)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.252985,-0.0354129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620017,0.0169264) , 
7, 0.336077, 1, 0, 0.582141,0.0559194) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.250191,-0.0400628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491905,0.00787791) , 
5, 0.702681, 1, 0, 0.325358,-0.122074) , 
6, 0.0951123, 1, 0, 0.523322,0.0151479)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745581,0.0343713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359083,-0.0273277) , 
1, 0.0244707, 1, 0, 0.634428,0.0781009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279891,-0.0392136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461441,-0.00282984) , 
5, 0.582139, 1, 0, 0.392462,-0.0811081) , 
6, 0.0400296, 1, 0, 0.495552,-0.0132765)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729686,0.0286577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374569,-0.0216758) , 
1, 0.025549, 1, 0, 0.63437,0.0700736) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277955,-0.0370561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437543,-0.0080336) , 
5, 0.556254, 1, 0, 0.390285,-0.0803898) , 
6, 0.030682, 1, 0, 0.470153,-0.0311561)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83136,0.0477087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490452,0.00408561) , 
1, 0.0242309, 1, 0, 0.705475,0.147521) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5319,0.000497231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30966,-0.0218343) , 
1, 0.0247429, 1, 0, 0.455262,-0.0343654) , 
3, 0.415517, 1, 0, 0.505054,0.00182982)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289916,-0.0285255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253992,-0.0575635) , 
5, 0.445483, 1, 0, 0.280562,-0.171294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577032,0.0132286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212502,-0.0508698) , 
3, 0.927926, 1, 0, 0.551065,0.041147) , 
5, 0.46854, 1, 0, 0.514969,0.012799)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47112,-0.00437452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764459,0.0334665) , 
7, 0.674895, 1, 0, 0.538977,0.0196136) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430004,-0.0182896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195089,-0.0495019) , 
3, 0.613198, 1, 0, 0.346866,-0.140935) , 
2, 0.743646, 1, 0, 0.497731,-0.0148563)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.214183,-0.0387597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585691,0.0114577) , 
7, 0.284937, 1, 0, 0.537738,0.0238098) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514131,-0.00665517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234554,-0.039731) , 
6, 0.0398966, 1, 0, 0.326991,-0.13728) , 
2, 0.74158, 1, 0, 0.497231,-0.00715266)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3303,-0.0338897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663645,0.0201232) , 
5, 0.468405, 1, 0, 0.637199,0.0743331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275388,-0.0358565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385223,-0.00197636) , 
6, 0.0461488, 1, 0, 0.338282,-0.0788545) , 
1, 0.0243839, 1, 0, 0.526846,0.0177801)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337855,-0.0289004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594085,0.00499207) , 
5, 0.503498, 1, 0, 0.530592,-0.0162075) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209823,-0.0681344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352575,-0.0160293) , 
3, 0.722468, 1, 0, 0.325734,-0.122679) , 
3, 0.687759, 1, 0, 0.465355,-0.0501133)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627897,0.0246011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593874,-0.00290416) , 
4, 0.832164, 1, 0, 0.607832,0.0411917) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32907,-0.0164622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524412,0.0221099) , 
7, 0.782745, 1, 0, 0.347129,-0.0603805) , 
1, 0.0249971, 1, 0, 0.515703,0.0052974)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499128,-0.00411687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598251,0.0205484) , 
5, 0.714873, 1, 0, 0.525942,0.0128977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155842,-0.0565666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213852,-0.036799) , 
6, 0.161597, 1, 0, 0.194099,-0.205742) , 
6, 0.147794, 1, 0, 0.493271,-0.0086285)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479279,-0.00770243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606685,0.0234919) , 
5, 0.762159, 1, 0, 0.496807,-0.0152796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14981,-0.0531266) , 
3, 0.916173, 1, 0, 0.469866,-0.0331314)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189359,-0.0407316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357059,-0.0188384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583777,0.0106051) , 
5, 0.507735, 1, 0, 0.538886,0.0226953) , 
0, 0.0468242, 1, 0, 0.511592,0.00637627)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3224,-0.0217699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549818,0.00986762) , 
5, 0.720133, 1, 0, 0.412927,-0.0413916) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215002,-0.0328334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662149,0.0170308) , 
7, 0.419845, 1, 0, 0.628131,0.0608137) , 
0, 0.290308, 1, 0, 0.512931,0.00610268)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9002,0.0585464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356268,-0.0211859) , 
1, 0.030094, 1, 0, 0.728078,0.145779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213391,-0.0384147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500304,-0.00248803) , 
0, 0.0466671, 1, 0, 0.48121,-0.0224616) , 
6, 0.0092055, 1, 0, 0.507576,-0.00449344)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470416,-0.00796731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597683,0.0110491) , 
5, 0.607137, 1, 0, 0.53458,0.00772441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307737,-0.0121116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.169684,-0.0460463) , 
4, 0.835606, 1, 0, 0.235305,-0.137021) , 
6, 0.13482, 1, 0, 0.503019,-0.00754023)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.182553,-0.0406068) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384181,-0.0228791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572875,0.0104992) , 
1, -0.0250841, 1, 0, 0.551632,0.0302087) , 
7, 0.27795, 1, 0, 0.520412,0.0124159)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748976,0.0317643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.88256,0.0563062) , 
6, 0.0047855, 1, 0, 0.813224,0.187338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503349,0.00701724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468858,-0.0115522) , 
2, 0.447026, 1, 0, 0.482509,-0.0190552) , 
6, 0.00923078, 1, 0, 0.514415,0.000856927)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582694,0.00576609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.75844,0.036652) , 
4, 1.50403, 1, 0, 0.621308,0.0574142) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420036,-0.0138538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570933,0.0130003) , 
5, 0.704055, 1, 0, 0.466046,-0.0245872) , 
1, 2.47884e-06, 1, 0, 0.52909,0.00870979)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544533,-0.0120074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.875654,0.054331) , 
6, 0.00334779, 1, 0, 0.744538,0.117004) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335336,-0.0186601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521679,0.00031221) , 
7, 0.505745, 1, 0, 0.457583,-0.0285308) , 
6, 0.012319, 1, 0, 0.495312,-0.00939573)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490671,-0.000509232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285637,-0.0366882) , 
2, 0.571331, 1, 0, 0.434971,-0.0473497) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713004,0.0273037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295587,-0.0252783) , 
4, 3.17166, 1, 0, 0.66038,0.0902538) , 
7, 0.686348, 1, 0, 0.498303,-0.00868817)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320864,-0.0302423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325554,-0.00963313) , 
6, 0.0459328, 1, 0, 0.32332,-0.0899503) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.254989,-0.0406362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594379,0.00682879) , 
0, 0.0934117, 1, 0, 0.574696,0.018186) , 
7, 0.517878, 1, 0, 0.489166,-0.0186072)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666196,0.0165529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260435,-0.0237631) , 
1, 0.174265, 1, 0, 0.621757,0.0545621) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282562,-0.0232224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493985,0.0101261) , 
5, 0.712765, 1, 0, 0.342042,-0.0612321) , 
6, 0.0646608, 1, 0, 0.518683,0.0118925)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656247,-0.000706132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.731459,0.0340463) , 
6, 0.0121821, 1, 0, 0.71348,0.116177) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470984,-0.0288518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445847,0.00185145) , 
6, 0.033843, 1, 0, 0.456499,-0.049067) , 
3, 0.412336, 1, 0, 0.50208,-0.0197571)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480278,-0.00693704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340778,-0.0413056) , 
5, 0.674991, 1, 0, 0.469307,-0.042926) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711336,0.0311214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397485,-0.00332693) , 
1, 0.0235004, 1, 0, 0.598396,0.0872973) , 
5, 0.691863, 1, 0, 0.510516,-0.00135521)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.158156,-0.0417831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429846,-0.0145831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602013,0.0104939) , 
5, 0.616779, 1, 0, 0.509011,-0.013281) , 
0, 0.0467692, 1, 0, 0.47905,-0.0270014)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264036,-0.0252795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560362,0.000700103) , 
0, 0.257202, 1, 0, 0.461129,-0.0350023) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442339,-0.00516247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.767265,0.0353708) , 
7, 0.508624, 1, 0, 0.585619,0.056494) , 
5, 0.689611, 1, 0, 0.497997,-0.00790519)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69048,0.0233672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251068,-0.0387966) , 
2, 1.02346, 1, 0, 0.632522,0.0651406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398883,-0.00830962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325924,-0.0513687) , 
0, 0.264003, 1, 0, 0.390883,-0.058491) , 
3, 0.556248, 1, 0, 0.500026,-0.00264932)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496139,-0.0114823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.769197,0.0308915) , 
5, 0.592643, 1, 0, 0.596754,0.0165676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408689,-0.005849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269804,-0.0365088) , 
7, 0.608035, 1, 0, 0.370596,-0.0642428) , 
3, 0.555667, 1, 0, 0.477538,-0.0260307)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469058,-0.00591289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565958,0.0195162) , 
5, 0.803838, 1, 0, 0.481103,-0.0115805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608914,0.00378333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.876195,0.0564774) , 
3, 0.274765, 1, 0, 0.756304,0.140534) , 
0, 0.513047, 1, 0, 0.500529,-0.000843246)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562475,0.0164758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500741,-0.0120819) , 
4, 0.929438, 1, 0, 0.528993,0.00581183) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.101148,-0.0672425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241444,-0.0257217) , 
6, 0.144352, 1, 0, 0.200658,-0.165588) , 
6, 0.13143, 1, 0, 0.492967,-0.0129949)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554386,0.00924979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170742,-0.0384185) , 
3, 0.419326, 1, 0, 0.316736,-0.0826657) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660999,0.0145223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354629,-0.0114582) , 
1, 0.0237616, 1, 0, 0.559624,0.0259951) , 
5, 0.495545, 1, 0, 0.515135,0.00609189)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327347,-0.018794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69477,0.0193186) , 
7, 0.543101, 1, 0, 0.641341,0.0589445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347855,-0.0341732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408808,-0.00351055) , 
6, 0.0123176, 1, 0, 0.398729,-0.0381573) , 
3, 0.557164, 1, 0, 0.51373,0.0078703)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574831,-0.00212867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406647,-0.0269995) , 
6, 0.0301063, 1, 0, 0.506952,-0.054942) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699948,0.0484033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379962,-0.00468895) , 
6, 0.0650055, 1, 0, 0.425344,0.0132537) , 
6, 0.0554239, 1, 0, 0.47552,-0.0286754)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519235,-0.00116977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692786,0.0301345) , 
5, 0.809808, 1, 0, 0.531085,0.00491435) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190532,-0.0394921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350691,0.00210085) , 
7, 0.388868, 1, 0, 0.251916,-0.101069) , 
3, 0.856035, 1, 0, 0.496744,-0.00812269)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457868,0.00643126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163401,-0.0427164) , 
6, 0.0395905, 1, 0, 0.305002,-0.0796117) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639948,0.0132897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380588,-0.00889305) , 
3, 0.699768, 1, 0, 0.551677,0.0250668) , 
5, 0.497447, 1, 0, 0.507456,0.00630151)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509055,0.00416323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471891,-0.0220192) , 
7, 0.756175, 1, 0, 0.503718,0.0024074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673706,0.0234235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.85536,0.0482185) , 
3, 0.285628, 1, 0, 0.765302,0.150571) , 
0, 0.513046, 1, 0, 0.519799,0.0115158)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198097,-0.0273421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525078,0.000887965) , 
5, 0.466409, 1, 0, 0.487496,-0.00872262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752209,0.0351832) , 
0, 0.542277, 1, 0, 0.49856,-0.00207636)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381367,-0.0157806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604987,0.00341499) , 
7, 0.699787, 1, 0, 0.463607,-0.037993) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441988,-0.00706708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.825675,0.0465776) , 
4, 0.452507, 1, 0, 0.606562,0.0676072) , 
5, 0.701893, 1, 0, 0.499369,-0.0115756)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448904,0.0632598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44484,-0.0107944) , 
7, 0.350107, 1, 0, 0.445106,-0.028774) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331978,-0.0168091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67747,0.0243875) , 
7, 0.403176, 1, 0, 0.580343,0.0559388) , 
5, 0.628203, 1, 0, 0.512104,0.0131939)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462395,0.0040332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21549,-0.0472437) , 
6, 0.0764124, 1, 0, 0.31962,-0.115892) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55992,-0.000743803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462137,0.0203499) , 
6, 0.0612421, 1, 0, 0.531861,0.0226055) , 
1, -0.0251998, 1, 0, 0.50552,0.00541663)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933955,0.0575548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555996,0.0127052) , 
1, 0.0131933, 1, 0, 0.828542,0.174851) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481159,-0.00414674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60034,0.0252056) , 
5, 0.801588, 1, 0, 0.494868,-0.00249044) , 
6, 0.0123073, 1, 0, 0.536264,0.0195108)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488975,0.00370981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483975,-0.0148873) , 
5, 0.630718, 1, 0, 0.486649,-0.0221896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654716,0.0360487) , 
5, 0.847508, 1, 0, 0.495891,-0.011775)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391693,-0.00210193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254511,-0.0320197) , 
0, 0.150015, 1, 0, 0.314615,-0.0831563) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442701,-0.0185711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666045,0.0141774) , 
5, 0.59218, 1, 0, 0.55993,-0.00689247) , 
7, 0.494717, 1, 0, 0.47547,-0.0331495)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472684,-0.0670779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571107,-0.0039278) , 
6, 0.00913691, 1, 0, 0.55085,-0.0633693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400481,-0.0132807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54525,0.0119945) , 
2, 0.297314, 1, 0, 0.506919,0.0211329) , 
3, 0.427445, 1, 0, 0.519132,-0.00235995)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248441,-0.0326582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497018,-0.00294079) , 
4, 0.309935, 1, 0, 0.479812,-0.0215658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634683,0.0304974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652487,0.00239831) , 
7, 0.457304, 1, 0, 0.641825,0.0903164) , 
5, 0.801588, 1, 0, 0.496767,-0.00985685)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498731,-0.00350769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719805,0.0276994) , 
5, 0.773145, 1, 0, 0.523514,0.000713299) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382325,-0.00246743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.128585,-0.0496826) , 
6, 0.0796672, 1, 0, 0.246456,-0.114683) , 
3, 0.879858, 1, 0, 0.491059,-0.0128044)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510351,-0.0200666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482302,0.00328712) , 
3, 0.466331, 1, 0, 0.491501,-0.0186106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.811129,0.056625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416768,0.0279087) , 
3, 0.389548, 1, 0, 0.630573,0.185425) , 
4, 2.37765, 1, 0, 0.500811,-0.00495177)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323592,-0.0386652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350387,-0.00703223) , 
6, 0.0336737, 1, 0, 0.341382,-0.0792664) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6701,0.024142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521423,-0.00702538) , 
2, 0.480772, 1, 0, 0.565131,0.00797612) , 
0, 0.233206, 1, 0, 0.461904,-0.0322732)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29935,-0.0781213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.784459,0.0308988) , 
2, 0.583481, 1, 0, 0.496234,-0.152816) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564953,0.00776294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335582,-0.0145866) , 
3, 0.751423, 1, 0, 0.503701,0.00804552) , 
3, 0.305854, 1, 0, 0.503145,-0.00392814)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443441,-0.0177171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455139,0.00613262) , 
1, -0.000416792, 1, 0, 0.449904,-0.020798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3878,-0.0118131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714496,0.0258899) , 
2, 0.216423, 1, 0, 0.582825,0.0452153) , 
5, 0.692259, 1, 0, 0.492724,0.000467929)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617115,0.0118434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314984,-0.008606) , 
1, 0.0249971, 1, 0, 0.502923,0.0183465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727071,0.0125291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337913,-0.0456301) , 
6, 0.0366791, 1, 0, 0.514357,-0.0929204) , 
0, 0.455908, 1, 0, 0.50503,-0.0021596)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528928,-0.00130042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.729883,0.0351873) , 
7, 0.804614, 1, 0, 0.543163,0.00537027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326516,0.00445513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235458,-0.0382706) , 
7, 0.488599, 1, 0, 0.266512,-0.104243) , 
6, 0.0949245, 1, 0, 0.483534,-0.0182556)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410059,-0.000933098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250891,-0.0553881) , 
7, 0.620015, 1, 0, 0.337341,-0.12457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.818144,0.042878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492951,-0.00358819) , 
3, 0.303492, 1, 0, 0.507336,-0.00680203) , 
1, -0.0249921, 1, 0, 0.488661,-0.0197392)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591165,0.00566151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374169,-0.0114827) , 
3, 0.688104, 1, 0, 0.525715,0.00165363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.201801,-0.0386074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25492,-0.0169386) , 
6, 0.167094, 1, 0, 0.231253,-0.115251) , 
6, 0.150141, 1, 0, 0.500905,-0.00819601)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614668,0.0417268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27142,-0.00583678) , 
1, 0.024434, 1, 0, 0.45821,0.0930855) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385797,-0.0337592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564,0.00411006) , 
4, 0.449273, 1, 0, 0.548554,0.00220143) , 
7, 0.44589, 1, 0, 0.528784,0.0220895)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105797,-0.0559776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500609,-0.00357918) , 
7, 0.264211, 1, 0, 0.484377,-0.0235898) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715824,0.0301908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386992,-0.00231324) , 
1, 0.0234765, 1, 0, 0.583885,0.0774639) , 
5, 0.801841, 1, 0, 0.495988,-0.0117985)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384954,-0.039963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517029,0.00687174) , 
3, 0.35507, 1, 0, 0.507043,0.0133643) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66569,0.0210335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.868445,0.0500844) , 
4, 2.16787, 1, 0, 0.768267,0.143073) , 
0, 0.513395, 1, 0, 0.523952,0.0217606)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530244,-0.00459148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481466,-0.0397226) , 
5, 0.585209, 1, 0, 0.510791,-0.0761961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600104,0.0152302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414186,-0.00606419) , 
1, 2.44058e-05, 1, 0, 0.490955,0.0126297) , 
3, 0.437496, 1, 0, 0.496786,-0.0134841)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498419,-0.00520587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.74636,0.0298988) , 
7, 0.699738, 1, 0, 0.651361,0.0690979) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432843,-0.0231738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389544,-0.00484232) , 
6, 0.0492658, 1, 0, 0.41421,-0.0653605) , 
3, 0.447592, 1, 0, 0.473139,-0.0319496)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376211,-0.0296462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412016,0.00390788) , 
6, 0.0461876, 1, 0, 0.393898,-0.0580308) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724754,0.0234225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291619,-0.0167425) , 
3, 0.568097, 1, 0, 0.621372,0.0567892) , 
7, 0.626147, 1, 0, 0.484931,-0.0120812)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391107,-0.0454553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555309,0.00257708) , 
6, 0.00351702, 1, 0, 0.542708,-0.00409663) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224673,-0.0423344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320735,0.00216585) , 
1, 0.0489226, 1, 0, 0.268703,-0.100071) , 
6, 0.0949245, 1, 0, 0.481665,-0.0254777)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.15241,-0.0108435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.141426,-0.0502246) , 
5, 0.743589, 1, 0, 0.145409,-0.149527) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534813,0.00664219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484983,-0.0247694) , 
0, 0.475245, 1, 0, 0.526211,0.00504131) , 
0, 0.0584586, 1, 0, 0.483394,-0.0123383)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470471,0.01791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457291,-0.0160796) , 
5, 0.73194, 1, 0, 0.465068,0.0134519) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731611,0.0100766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356254,-0.0301667) , 
6, 0.0397653, 1, 0, 0.516773,-0.0628846) , 
0, 0.362383, 1, 0, 0.483732,-0.0141023)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476636,0.00792433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546071,-0.00897398) , 
7, 0.590026, 1, 0, 0.518461,-0.00900641) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21569,-0.0154061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197238,-0.0418421) , 
0, 0.0498473, 1, 0, 0.208012,-0.107248) , 
3, 0.855846, 1, 0, 0.47152,-0.0238611)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491737,0.00780486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502894,-0.00731729) , 
5, 0.675146, 1, 0, 0.496576,0.00439578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764308,0.0294552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203732,-0.0511919) , 
6, 0.0397806, 1, 0, 0.404198,-0.109285) , 
7, 0.792594, 1, 0, 0.486507,-0.00799512)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232564,-0.053597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461954,0.000380826) , 
3, 0.351109, 1, 0, 0.446942,-0.0147976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864489,0.0438162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529504,0.0100637) , 
6, 0.0368373, 1, 0, 0.681186,0.0968858) , 
7, 0.684222, 1, 0, 0.510505,0.0155085)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542832,0.0101164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479367,-0.0300753) , 
7, 0.788466, 1, 0, 0.539097,0.0326565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.740895,0.0450562) , 
7, 0.81879, 1, 0, 0.548081,0.0390037)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534758,-0.0181827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.726817,0.0369527) , 
4, 2.18392, 1, 0, 0.574208,-0.030298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504394,0.00900589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864226,0.063971) , 
0, 0.341319, 1, 0, 0.523232,0.0499346) , 
3, 0.471609, 1, 0, 0.542385,0.0197887)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444425,-0.0153237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497576,0.0187503) , 
3, 0.655926, 1, 0, 0.48334,0.0408075) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488291,0.00584327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498672,-0.0219372) , 
5, 0.573587, 1, 0, 0.494338,-0.0429662) , 
4, 0.618348, 1, 0, 0.491092,-0.0182361)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506146,-0.00396957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414408,0.0292535) , 
1, 0.346559, 1, 0, 0.499852,-0.00789902) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402975,0.0101523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299739,-0.0439552) , 
2, 0.139159, 1, 0, 0.33696,-0.115403) , 
5, 0.825971, 1, 0, 0.481188,-0.0202167)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436,-0.00204655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277074,-0.0460635) , 
0, 0.507674, 1, 0, 0.429299,-0.017599) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761512,0.0289944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247838,-0.0198643) , 
2, 1.25186, 1, 0, 0.688025,0.0874034) , 
7, 0.684459, 1, 0, 0.496511,0.00967855)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421251,-0.0158391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422909,0.01163) , 
6, 0.046034, 1, 0, 0.422136,-0.00672361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615817,0.0378865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68498,0.0121157) , 
7, 0.624424, 1, 0, 0.666031,0.0789514) , 
0, 0.29033, 1, 0, 0.53051,0.0313459)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462236,-0.0082764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0429061,-0.0608585) , 
6, 0.174537, 1, 0, 0.441486,-0.0447171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70034,0.0275802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529942,-0.000399008) , 
5, 0.749804, 1, 0, 0.590153,0.039673) , 
5, 0.693686, 1, 0, 0.483468,-0.0208859)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326347,-0.0504889) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499067,0.0101487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519556,-0.0060729) , 
5, 0.583398, 1, 0, 0.512961,-0.00420503) , 
3, 0.267458, 1, 0, 0.506822,-0.0115546)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809669,0.0343057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237027,-0.0347267) , 
1, 0.2463, 1, 0, 0.690981,0.0749249) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450397,-0.00221356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437022,-0.0225905) , 
7, 0.667334, 1, 0, 0.446383,-0.0344116) , 
3, 0.388435, 1, 0, 0.485211,-0.0170552)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622034,0.0112683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492238,-0.0202215) , 
6, 0.0196911, 1, 0, 0.548375,-0.028894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644515,0.0309062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395247,0.00383128) , 
6, 0.0660304, 1, 0, 0.472465,0.054035) , 
6, 0.0431076, 1, 0, 0.51348,0.0092274)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561574,-0.00129992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.848555,0.0880309) , 
3, 0.655059, 1, 0, 0.575408,0.0135641) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390069,0.00152512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303721,-0.0378321) , 
7, 0.508973, 1, 0, 0.35603,-0.060822) , 
3, 0.687735, 1, 0, 0.500431,-0.0118589)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580094,0.0237729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498932,-0.00315566) , 
1, -0.0253719, 1, 0, 0.505808,-0.00269441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376388,-0.0441536) , 
0, 0.584505, 1, 0, 0.501594,-0.00875984)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360218,-0.00219398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293695,-0.0530064) , 
5, 0.491124, 1, 0, 0.343688,-0.0645517) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572477,0.0104199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492148,-0.00828951) , 
5, 0.66596, 1, 0, 0.532202,0.00330771) , 
5, 0.509622, 1, 0, 0.491418,-0.0113734)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485406,-0.0128027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390423,0.0175288) , 
6, 0.101609, 1, 0, 0.471625,-0.0362078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729957,0.042318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371731,-0.00919989) , 
5, 0.883651, 1, 0, 0.589279,0.101254) , 
5, 0.801841, 1, 0, 0.483349,-0.0225096)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574735,-0.00246651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526246,0.0108472) , 
3, 0.471566, 1, 0, 0.544856,0.0251355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.151012,-0.0474678) , 
2, 1.3357, 1, 0, 0.521905,0.01194)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697842,0.0172128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456191,-0.00796065) , 
6, 0.0538157, 1, 0, 0.606579,0.0298263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207003,-0.0308032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29034,-0.00337536) , 
6, 0.0429543, 1, 0, 0.261167,-0.0510545) , 
1, 0.0735402, 1, 0, 0.51231,0.00775243)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622238,0.0452713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220939,0.0012801) , 
1, 0.0988599, 1, 0, 0.435264,0.107146) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500871,-0.00550256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261247,-0.053834) , 
4, 2.77929, 1, 0, 0.492346,-0.0310878) , 
5, 0.456259, 1, 0, 0.487653,-0.0197225)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500864,0.0272005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46694,-0.0115106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417338,0.0295425) , 
1, 0.349937, 1, 0, 0.463968,-0.0388981) , 
2, 0.15089, 1, 0, 0.465979,-0.030428)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543987,-0.0304005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.65531,0.0156598) , 
6, 0.00364737, 1, 0, 0.64167,0.0403815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387242,-0.0145465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504182,0.0232775) , 
4, 2.16281, 1, 0, 0.396958,-0.0505836) , 
6, 0.0369195, 1, 0, 0.493317,-0.0147648)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274911,-0.0244292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270038,0.00890473) , 
1, 0.149347, 1, 0, 0.273749,-0.0702392) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542472,-0.000103753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546508,0.0274625) , 
2, 0.708186, 1, 0, 0.543064,0.0159601) , 
5, 0.472051, 1, 0, 0.504478,0.00361013)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593955,0.0345833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587402,0.00667234) , 
0, 0.206133, 1, 0, 0.588427,0.0468343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351694,0.00731032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313231,-0.0178818) , 
7, 0.393243, 1, 0, 0.330526,-0.0285431) , 
3, 0.760123, 1, 0, 0.529199,0.0295236)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277614,-0.0308561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337375,-0.00638394) , 
6, 0.0277127, 1, 0, 0.315844,-0.0670912) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659899,0.0327247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555699,-0.00705849) , 
7, 0.623319, 1, 0, 0.585363,0.0187622) , 
7, 0.516334, 1, 0, 0.48334,-0.0137364)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397278,-0.00973233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59578,0.0113025) , 
5, 0.521176, 1, 0, 0.541792,0.0239303) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400016,-0.0334057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572565,0.0156674) , 
6, 0.0486112, 1, 0, 0.475096,-0.0509863) , 
5, 0.777205, 1, 0, 0.530619,0.0113799)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618124,0.0149062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242164,-0.0190993) , 
6, 0.132291, 1, 0, 0.570444,0.0446369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395911,-0.0112309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194992,-0.0607953) , 
7, 0.86346, 1, 0, 0.371095,-0.0738452) , 
2, 0.708044, 1, 0, 0.517023,0.0128862)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418435,-0.0246261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682499,0.00664494) , 
0, 0.41292, 1, 0, 0.471212,-0.0822013) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196279,-0.0275997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553122,0.0141668) , 
7, 0.277636, 1, 0, 0.520014,0.0422604) , 
1, -0.000576744, 1, 0, 0.498421,-0.0128092)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373102,-0.0203917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370191,0.0182999) , 
6, 0.0703543, 1, 0, 0.372531,-0.053909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67339,0.0136208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386835,-0.00755825) , 
3, 0.687681, 1, 0, 0.562028,0.021024) , 
5, 0.554512, 1, 0, 0.500336,-0.00337097)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405827,-0.00680751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237341,-0.04748) , 
1, -0.0352896, 1, 0, 0.301856,-0.147933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412954,0.0153199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546652,-0.00121398) , 
7, 0.434417, 1, 0, 0.521678,0.0075044) , 
1, -0.0251914, 1, 0, 0.494667,-0.0115957)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356811,-0.00797099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583849,0.0200462) , 
0, 0.174682, 1, 0, 0.467831,0.0246561) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623579,2.55542e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24564,-0.044725) , 
3, 0.555667, 1, 0, 0.534274,-0.0445528) , 
7, 0.638187, 1, 0, 0.497466,-0.00621321)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608877,0.00555481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364066,-0.0192422) , 
1, 0.00567142, 1, 0, 0.501656,-0.0213747) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.312956,-0.00146603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449652,0.0427755) , 
2, 0.595378, 1, 0, 0.373889,0.068193) , 
1, 0.272017, 1, 0, 0.491454,-0.0142228)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503304,0.00216752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394647,-0.0358176) , 
0, 0.463152, 1, 0, 0.491133,-0.00885262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585742,0.00964349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.876037,0.0573368) , 
5, 0.556399, 1, 0, 0.69416,0.107998) , 
7, 0.772057, 1, 0, 0.515865,0.00538152)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292357,-0.0354986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339184,0.0120754) , 
6, 0.0521875, 1, 0, 0.30512,-0.0955057) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573118,0.000869366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506997,0.0281971) , 
1, 0.0974711, 1, 0, 0.563707,0.0203984) , 
5, 0.505385, 1, 0, 0.506616,-0.00519083)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168649,-0.0329712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536606,0.0276533) , 
5, 0.397436, 1, 0, 0.4553,0.0579134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578613,-0.0202665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508216,0.00269458) , 
6, 0.0275596, 1, 0, 0.531821,-0.0183969) , 
5, 0.533372, 1, 0, 0.514582,-0.00120598)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401011,0.00426879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493116,-0.0152344) , 
7, 0.493704, 1, 0, 0.464198,-0.0371165) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481795,-0.0117977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.784802,0.0372) , 
5, 0.504771, 1, 0, 0.654546,0.060559) , 
0, 0.467587, 1, 0, 0.488424,-0.0246851)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333932,-0.0238936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.768127,0.0221887) , 
7, 0.511679, 1, 0, 0.610167,0.0121801) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399874,0.0228715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410046,-0.0157097) , 
7, 0.372275, 1, 0, 0.408933,-0.0517785) , 
6, 0.0307917, 1, 0, 0.480851,-0.0289206)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599198,0.019716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213026,-0.0412955) , 
3, 0.533643, 1, 0, 0.310792,-0.111952) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658001,0.0137821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455034,-0.00335378) , 
1, -0.000299776, 1, 0, 0.522905,0.010188) , 
1, -0.0249881, 1, 0, 0.495064,-0.00584359)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394195,0.00744051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492571,-0.0113667) , 
0, 0.154403, 1, 0, 0.466948,-0.0276581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712394,0.0114514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559829,0.0352864) , 
2, 0.894072, 1, 0, 0.63144,0.0949414) , 
4, 2.13173, 1, 0, 0.481779,-0.0166044)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315414,-0.0170481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234667,-0.0516418) , 
7, 0.607698, 1, 0, 0.277785,-0.151846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610398,0.00743184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352378,-0.00793639) , 
3, 0.70016, 1, 0, 0.525797,0.00936067) , 
1, -0.0251914, 1, 0, 0.493273,-0.0117801)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347703,-0.020744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555915,0.002375) , 
4, 1.17022, 1, 0, 0.460963,-0.034369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.746259,0.0506568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540711,0.00327233) , 
5, 0.718109, 1, 0, 0.572775,0.0434411) , 
5, 0.687859, 1, 0, 0.495144,-0.0105825)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520529,0.00480904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199718,-0.0256183) , 
6, 0.138444, 1, 0, 0.480592,0.00527189) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318707,-0.0615077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580985,-0.0027841) , 
7, 0.739504, 1, 0, 0.513767,-0.0758979) , 
7, 0.723858, 1, 0, 0.488334,-0.0136707)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826738,0.0482572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634352,0.0125224) , 
7, 0.735809, 1, 0, 0.768939,0.136451) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495644,-0.0197532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460724,0.00260405) , 
6, 0.0298499, 1, 0, 0.470747,-0.0146016) , 
6, 0.0091937, 1, 0, 0.50276,0.00161511)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390169,0.0260035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538157,-0.00070933) , 
0, 0.168427, 1, 0, 0.512709,0.0144674) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500804,0.0055407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.854815,0.0498548) , 
4, 0.452938, 1, 0, 0.616127,0.0825728) , 
5, 0.726456, 1, 0, 0.537472,0.0307754)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387931,-0.00743171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405978,-0.0354131) , 
7, 0.594101, 1, 0, 0.391545,-0.0554256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79016,0.0270394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452956,-0.0101472) , 
2, 0.646342, 1, 0, 0.58842,0.016529) , 
7, 0.650294, 1, 0, 0.464709,-0.0286853)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.241031,-0.0473745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595867,0.00456743) , 
0, 0.179688, 1, 0, 0.570658,0.00346069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540162,0.0301629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235775,-0.0167164) , 
3, 0.942015, 1, 0, 0.478171,0.09102) , 
3, 0.723784, 1, 0, 0.549651,0.0233482)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599288,0.00674137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285436,-0.0143001) , 
1, 0.149206, 1, 0, 0.544717,0.0128912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167093,-0.034284) , 
3, 0.917248, 1, 0, 0.515119,0.00110942)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167707,-0.0293959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504698,-0.00420929) , 
7, 0.422856, 1, 0, 0.441424,-0.0345778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62564,0.016402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251449,-0.0225724) , 
6, 0.135367, 1, 0, 0.553482,0.03676) , 
5, 0.641469, 1, 0, 0.488742,-0.00445472)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697966,-0.0012638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377902,-0.0298878) , 
6, 0.0305661, 1, 0, 0.492239,-0.087984) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490196,0.0024322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605772,0.0368492) , 
5, 0.859324, 1, 0, 0.499057,0.0217531) , 
3, 0.447563, 1, 0, 0.496772,-0.0150277)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.82036,0.0345408) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483629,-0.00574882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304075,-0.0409575) , 
7, 0.804312, 1, 0, 0.472755,-0.0332574) , 
3, 0.315463, 1, 0, 0.492507,-0.0244088)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425741,0.00714947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358896,-0.0284277) , 
7, 0.477065, 1, 0, 0.385472,-0.0599127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60499,0.0203194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592166,-0.00979559) , 
7, 0.674369, 1, 0, 0.59758,0.0125841) , 
0, 0.285224, 1, 0, 0.489301,-0.0244249)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380072,0.00780736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14953,-0.0550823) , 
3, 0.77853, 1, 0, 0.209802,-0.158367) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45702,-0.00693879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613705,0.00900374) , 
7, 0.673864, 1, 0, 0.515579,-0.00514897) , 
7, 0.349222, 1, 0, 0.475985,-0.0249884)    );
   return;
};

// Clean up
inline void ReadBDT-0.3_fold10::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.3_fold10::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
