// Class: ReadBDT-0.3_fold10
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.3_fold10
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/00       [401408]
Creator        : htan
Date           : Thu Aug 15 09:50:19 2024
Host           : Linux 6772f6b99311 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May 9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gluster/home/htan/ZTTBDT
Training events: 105014
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
m_d_zeta                      m_d_zeta                      m_d_zeta                      m_d_zeta                                                        'F'    [-1859.73010254,1223.64221191]
m_pT_asymm                    m_pT_asymm                    m_pT_asymm                    m_pT_asymm                                                      'F'    [1.16390037874e-05,0.946852445602]
m_sigmaCosDelPhi              m_sigmaCosDelPhi              m_sigmaCosDelPhi              m_sigmaCosDelPhi                                                'F'    [-0.049986757338,1.9745773077]
m_ratioMetTauPT               m_ratioMetTauPT               m_ratioMetTauPT               m_ratioMetTauPT                                                 'F'    [0.00113642180804,11.9963302612]
m_ratioMuonTauPT              m_ratioMuonTauPT              m_ratioMuonTauPT              m_ratioMuonTauPT                                                'F'    [0.0272991936654,0.999976694584]
m_ratioMetMuonPT              m_ratioMetMuonPT              m_ratioMetMuonPT              m_ratioMetMuonPT                                                'F'    [0.00152266630903,24.9829425812]
m_ratioMuonTauM3              m_ratioMuonTauM3              m_ratioMuonTauM3              m_ratioMuonTauM3                                                'F'    [0.00183517555706,0.996654033661]
m_ratioMuonMetM3              m_ratioMuonMetM3              m_ratioMuonMetM3              m_ratioMuonMetM3                                                'F'    [1.27644239001e-06,0.249402225018]
m_ratioMetTauM3               m_ratioMetTauM3               m_ratioMetTauM3               m_ratioMetTauM3                                                 'F'    [5.56223167223e-05,0.977119266987]
NSpec 1
m_event_number                m_event_number                m_event_number                I                                                               'F'    [113,1214786176]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.3_fold10Node

#ifndef BDT-0.3_fold10Node__def
#define BDT-0.3_fold10Node__def

class BDT-0.3_fold10Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.3_fold10Node ( BDT-0.3_fold10Node* left,BDT-0.3_fold10Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.3_fold10Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold10Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold10Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.3_fold10Node*   fLeft;     // pointer to the left daughter node
   BDT-0.3_fold10Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.3_fold10Node::~BDT-0.3_fold10Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.3_fold10Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.3_fold10Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.3_fold10 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.3_fold10( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.3_fold10" ),
        fNvars( 9 )
   {
      // the training input variables
      const char* inputVars[] = { "m_d_zeta", "m_pT_asymm", "m_sigmaCosDelPhi", "m_ratioMetTauPT", "m_ratioMuonTauPT", "m_ratioMetMuonPT", "m_ratioMuonTauM3", "m_ratioMuonMetM3", "m_ratioMetTauM3" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.3_fold10() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.3_fold10Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.3_fold10::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.3_fold10Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.3_fold10Node*)current->GetRight();
         else current=(BDT-0.3_fold10Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.3_fold10::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465457,-0.00690869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789401,0.0578803) , 
8, 0.567253, 1, 0, 0.667465,0.167465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340117,-0.0319765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496898,-0.000620374) , 
1, 0.27322, 1, 0, 0.412309,-0.087691) , 
7, 0.0429545, 1, 0, 0.529706,0.0297055)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419667,-0.0142977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.668275,0.0315212) , 
2, -0.0143394, 1, 0, 0.593321,0.0883564) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217656,-0.0548949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442948,-0.0131336) , 
8, 0.551778, 1, 0, 0.333644,-0.166863) , 
2, 0.0240551, 1, 0, 0.494296,-0.00896902)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375593,-0.0219683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.639185,0.0242571) , 
2, -0.0163303, 1, 0, 0.574429,0.064191) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245566,-0.0493411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410985,-0.0128444) , 
7, 0.0520926, 1, 0, 0.331059,-0.15193) , 
2, 0.0739321, 1, 0, 0.513133,0.00975747)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442369,-0.0112507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646055,0.0242117) , 
8, 0.53302, 1, 0, 0.573631,0.0575523) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181176,-0.0556088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39582,-0.0162698) , 
1, 0.27994, 1, 0, 0.284841,-0.181721) , 
2, 0.0986257, 1, 0, 0.504597,0.000355446)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402787,-0.0195452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655054,0.0237982) , 
8, 0.498098, 1, 0, 0.580012,0.0537311) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279897,-0.0400039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422377,-0.00773248) , 
6, 0.697525, 1, 0, 0.3189,-0.154659) , 
2, 0.0249971, 1, 0, 0.483252,-0.0234916)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417554,-0.0132704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228924,-0.0506143) , 
4, 0.819719, 1, 0, 0.348323,-0.133599) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79583,0.0502498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458689,-0.00807097) , 
7, 0.0397653, 1, 0, 0.618435,0.0957392) , 
1, 0.254306, 1, 0, 0.483348,-0.0189557)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247716,-0.0438265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446203,-0.00215458) , 
6, 0.692344, 1, 0, 0.334963,-0.125833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662971,0.023972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412799,-0.0133565) , 
7, 0.0615316, 1, 0, 0.574131,0.0522468) , 
8, 0.470597, 1, 0, 0.509377,0.00403184)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344692,-0.0242818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69164,0.028679) , 
8, 0.518837, 1, 0, 0.639408,0.100595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299932,-0.0322004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517629,0.00796892) , 
6, 0.704038, 1, 0, 0.396572,-0.0700405) , 
4, 0.56824, 1, 0, 0.514093,0.012539)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147028,-0.0677691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445781,-0.0142218) , 
3, 0.602938, 1, 0, 0.322807,-0.17615) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667362,0.0226606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424089,-0.0102468) , 
4, 0.559681, 1, 0, 0.526142,0.0167918) , 
6, 0.501014, 1, 0, 0.493049,-0.0146096)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.252985,-0.0354129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620017,0.0169264) , 
8, 0.336077, 1, 0, 0.582141,0.0559194) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.250191,-0.0400628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491905,0.00787791) , 
6, 0.702681, 1, 0, 0.325358,-0.122074) , 
7, 0.0951123, 1, 0, 0.523322,0.0151479)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745581,0.0343713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359083,-0.0273277) , 
2, 0.0244707, 1, 0, 0.634428,0.0781009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279891,-0.0392136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461441,-0.00282984) , 
6, 0.582139, 1, 0, 0.392462,-0.0811081) , 
7, 0.0400296, 1, 0, 0.495552,-0.0132765)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729686,0.0286577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374569,-0.0216758) , 
2, 0.025549, 1, 0, 0.63437,0.0700736) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277955,-0.0370561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437543,-0.0080336) , 
6, 0.556254, 1, 0, 0.390285,-0.0803898) , 
7, 0.030682, 1, 0, 0.470153,-0.0311561)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83136,0.0477087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490452,0.00408561) , 
2, 0.0242309, 1, 0, 0.705475,0.147521) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303597,-0.0273058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50247,-0.000944634) , 
0, -9.78018, 1, 0, 0.455262,-0.0343654) , 
4, 0.415517, 1, 0, 0.505054,0.00182982)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289916,-0.0286359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253992,-0.0576293) , 
6, 0.445483, 1, 0, 0.280562,-0.171989) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577032,0.0131983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212502,-0.0507496) , 
4, 0.927926, 1, 0, 0.551065,0.0411078) , 
6, 0.46854, 1, 0, 0.514969,0.0126723)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47112,-0.00424656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764459,0.0335725) , 
8, 0.674895, 1, 0, 0.538977,0.0202096) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430004,-0.0184474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195089,-0.049918) , 
4, 0.613198, 1, 0, 0.346866,-0.14236) , 
3, 0.743646, 1, 0, 0.497731,-0.0146944)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.214183,-0.0389679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585691,0.0115212) , 
8, 0.284937, 1, 0, 0.537738,0.0239514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514131,-0.00664063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234554,-0.0399777) , 
7, 0.0398966, 1, 0, 0.326991,-0.13827) , 
3, 0.74158, 1, 0, 0.497231,-0.00722841)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3303,-0.0337576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663645,0.0204447) , 
6, 0.468405, 1, 0, 0.637199,0.0758008) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275388,-0.036086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385223,-0.00283497) , 
7, 0.0461488, 1, 0, 0.338282,-0.0816873) , 
2, 0.0243839, 1, 0, 0.526846,0.0176602)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337855,-0.0289233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594085,0.0050705) , 
6, 0.503498, 1, 0, 0.530592,-0.0159697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209823,-0.0680417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352575,-0.0160456) , 
4, 0.722468, 1, 0, 0.325734,-0.122711) , 
4, 0.687759, 1, 0, 0.465355,-0.0499617)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638826,0.0155352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342305,-0.045754) , 
0, 12.4924, 1, 0, 0.607832,0.0426123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32907,-0.0171012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524412,0.0220618) , 
8, 0.782745, 1, 0, 0.347129,-0.0632651) , 
2, 0.0249971, 1, 0, 0.515703,0.00519659)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571283,0.0108748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408293,-0.01724) , 
0, 5.51081, 1, 0, 0.525942,0.0137879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155842,-0.0571822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213852,-0.0372498) , 
7, 0.161597, 1, 0, 0.194099,-0.20841) , 
7, 0.147794, 1, 0, 0.493271,-0.00808867)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479279,-0.0082773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606685,0.0251668) , 
6, 0.762159, 1, 0, 0.496807,-0.0163537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14981,-0.0522725) , 
4, 0.916173, 1, 0, 0.469866,-0.0338091)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189359,-0.0389168) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357059,-0.0192292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583777,0.0107372) , 
6, 0.507735, 1, 0, 0.538886,0.0227748) , 
1, 0.0468242, 1, 0, 0.511592,0.00717415)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3224,-0.0222343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549818,0.0124081) , 
6, 0.720133, 1, 0, 0.412927,-0.0379331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215002,-0.0323924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662149,0.016205) , 
8, 0.419845, 1, 0, 0.628131,0.0570565) , 
1, 0.290308, 1, 0, 0.512931,0.00620802)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74712,0.0345602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498334,-0.0020875) , 
7, 0.00919349, 1, 0, 0.525243,0.0083428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189644,-0.0489706) , 
0, 43.9327, 1, 0, 0.507576,-0.00426566)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470416,-0.00907739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597683,0.0116121) , 
6, 0.607137, 1, 0, 0.53458,0.00663665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307737,-0.0127665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.169684,-0.0467157) , 
5, 0.835606, 1, 0, 0.235305,-0.140466) , 
7, 0.13482, 1, 0, 0.503019,-0.00887655)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.182553,-0.0410119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384181,-0.0219422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572875,0.0103689) , 
2, -0.0250841, 1, 0, 0.551632,0.030203) , 
8, 0.27795, 1, 0, 0.520412,0.0121091)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748976,0.0319929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.88256,0.0563864) , 
7, 0.0047855, 1, 0, 0.813224,0.189436) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503349,0.00770219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468858,-0.0124462) , 
3, 0.447026, 1, 0, 0.482509,-0.0200929) , 
7, 0.00923078, 1, 0, 0.514415,0.000121734)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647958,0.014155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321029,-0.0438136) , 
0, 15.7124, 1, 0, 0.618252,0.0401665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340133,-0.0192022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419734,0.0170008) , 
2, 0.265687, 1, 0, 0.359736,-0.0504454) , 
2, 0.0249971, 1, 0, 0.52909,0.0089145)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544533,-0.0119348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.875654,0.0535473) , 
7, 0.00334779, 1, 0, 0.744538,0.114926) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335336,-0.0185887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521679,0.000322493) , 
8, 0.505745, 1, 0, 0.457583,-0.0284844) , 
7, 0.012319, 1, 0, 0.495312,-0.00962861)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490671,-0.000146291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285637,-0.0385863) , 
3, 0.571331, 1, 0, 0.434971,-0.0485789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.750098,0.0342978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477418,-0.00592448) , 
0, 5.87755, 1, 0, 0.66038,0.0901003) , 
8, 0.686348, 1, 0, 0.498303,-0.00961513)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320864,-0.0294273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325554,-0.00965174) , 
7, 0.0459328, 1, 0, 0.32332,-0.0885095) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602581,0.00677555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202362,-0.039462) , 
3, 1.4821, 1, 0, 0.574696,0.0160919) , 
8, 0.517878, 1, 0, 0.489166,-0.0194986)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366916,-0.0217785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674986,0.0191401) , 
0, -18.2872, 1, 0, 0.621757,0.0525803) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282562,-0.023492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493985,0.0105622) , 
6, 0.712765, 1, 0, 0.342042,-0.0618724) , 
7, 0.0646608, 1, 0, 0.518683,0.010405)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656247,-0.00368313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.731459,0.0345866) , 
7, 0.0121821, 1, 0, 0.71348,0.115087) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470984,-0.0294485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445847,0.001818) , 
7, 0.033843, 1, 0, 0.456499,-0.0501983) , 
4, 0.412336, 1, 0, 0.50208,-0.0208812)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480278,-0.00772026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340778,-0.0428787) , 
6, 0.674991, 1, 0, 0.469307,-0.0466026) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439736,0.000159929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707033,0.0335646) , 
3, 0.24722, 1, 0, 0.598396,0.0932056) , 
6, 0.691863, 1, 0, 0.510516,-0.00197206)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.158156,-0.0453305) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429846,-0.0150259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602013,0.0114178) , 
6, 0.616779, 1, 0, 0.509011,-0.0122904) , 
1, 0.0467692, 1, 0, 0.47905,-0.027816)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264036,-0.0265699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560362,0.000518512) , 
1, 0.257202, 1, 0, 0.461129,-0.0376214) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327391,-0.0201779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669705,0.0247247) , 
1, 0.0749052, 1, 0, 0.585619,0.0635721) , 
6, 0.689611, 1, 0, 0.497997,-0.00765241)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69048,0.0229653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251068,-0.0379221) , 
3, 1.02346, 1, 0, 0.632522,0.0639804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398883,-0.00830475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325924,-0.051377) , 
1, 0.264003, 1, 0, 0.390883,-0.05878) , 
4, 0.556248, 1, 0, 0.500026,-0.00333186)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496139,-0.0120051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.769197,0.0303758) , 
6, 0.592643, 1, 0, 0.596754,0.0140657) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408689,-0.00503574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269804,-0.0376631) , 
8, 0.608035, 1, 0, 0.370596,-0.0633192) , 
4, 0.555667, 1, 0, 0.477538,-0.0267268)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469058,-0.0062447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565958,0.0211102) , 
6, 0.803838, 1, 0, 0.481103,-0.0119056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608914,0.00560936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.876195,0.0567538) , 
4, 0.274765, 1, 0, 0.756304,0.144818) , 
1, 0.513047, 1, 0, 0.500529,-0.000842985)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562475,0.0169479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500741,-0.0129247) , 
5, 0.929438, 1, 0, 0.528993,0.00506131) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.101148,-0.0660555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241444,-0.0275873) , 
7, 0.144352, 1, 0, 0.200658,-0.171543) , 
7, 0.13143, 1, 0, 0.492967,-0.0143165)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554386,0.00753987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170742,-0.0395276) , 
4, 0.419326, 1, 0, 0.316736,-0.0895728) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660999,0.0147541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354629,-0.0122746) , 
2, 0.0237616, 1, 0, 0.559624,0.0252854) , 
6, 0.495545, 1, 0, 0.515135,0.00424701)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327347,-0.0182523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69477,0.0193703) , 
8, 0.543101, 1, 0, 0.641341,0.0591069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408588,-0.0208805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391318,0.00155564) , 
7, 0.0400288, 1, 0, 0.398729,-0.0367185) , 
4, 0.557164, 1, 0, 0.51373,0.00870412)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530207,-0.010804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475134,0.00833117) , 
7, 0.0548624, 1, 0, 0.510458,-0.016638) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234481,-0.0103184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274489,-0.0322978) , 
6, 0.750259, 1, 0, 0.258935,-0.106454) , 
4, 0.844346, 1, 0, 0.47552,-0.0291141)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.812963,0.0456573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405797,-0.0107787) , 
7, 0.0091937, 1, 0, 0.435336,-0.0305319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696581,0.0216313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501161,-0.0113953) , 
8, 0.776096, 1, 0, 0.620502,0.0370029) , 
8, 0.675556, 1, 0, 0.496744,-0.0081346)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457868,0.00465507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163401,-0.0418814) , 
7, 0.0395905, 1, 0, 0.305002,-0.081269) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639948,0.0126873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380588,-0.00754022) , 
4, 0.699768, 1, 0, 0.551677,0.0250459) , 
6, 0.497447, 1, 0, 0.507456,0.00598724)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622791,0.0151635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28438,-0.0104763) , 
2, 0.149202, 1, 0, 0.568086,0.0480688) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190715,-0.0414678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509881,-0.00497455) , 
8, 0.513055, 1, 0, 0.395946,-0.0794124) , 
0, 5.51081, 1, 0, 0.519799,0.0123086)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198097,-0.0278584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525078,0.000785259) , 
6, 0.466409, 1, 0, 0.487496,-0.00938761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752209,0.0367076) , 
1, 0.542277, 1, 0, 0.49856,-0.0023401)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411593,-0.0160544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605599,0.0057794) , 
8, 0.735961, 1, 0, 0.463607,-0.0439407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441988,-0.00367194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.825675,0.0473989) , 
5, 0.452507, 1, 0, 0.606562,0.0789809) , 
6, 0.701893, 1, 0, 0.499369,-0.0131901)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448904,0.06101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44484,-0.011367) , 
8, 0.350107, 1, 0, 0.445106,-0.0311184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331978,-0.0149481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67747,0.0245549) , 
8, 0.403176, 1, 0, 0.580343,0.058606) , 
6, 0.628203, 1, 0, 0.512104,0.0133324)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462395,0.00780201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21549,-0.0443063) , 
7, 0.0764124, 1, 0, 0.31962,-0.100558) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512048,0.000365222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641385,0.026581) , 
6, 0.773611, 1, 0, 0.531861,0.019821) , 
2, -0.0251998, 1, 0, 0.50552,0.00488076)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.933955,0.0555023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555996,0.00891934) , 
2, 0.0131933, 1, 0, 0.828542,0.160379) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481159,-0.00384793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60034,0.0275695) , 
6, 0.801588, 1, 0, 0.494868,-2.43651e-05) , 
7, 0.0123073, 1, 0, 0.536264,0.0198755)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488975,0.00294241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483975,-0.0147725) , 
6, 0.630718, 1, 0, 0.486649,-0.0235908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654716,0.0373262) , 
6, 0.847508, 1, 0, 0.495891,-0.0127232)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406659,-0.0193151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487549,0.0219045) , 
5, 2.78788, 1, 0, 0.412945,-0.0675714) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630259,0.0120298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309048,-0.0273237) , 
7, 0.0857382, 1, 0, 0.539023,0.00130943) , 
6, 0.615921, 1, 0, 0.47547,-0.0334119)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678605,0.0151435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511841,-0.0653038) , 
8, 0.644956, 1, 0, 0.577461,-0.113769) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538526,-0.00714753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496307,0.00819489) , 
7, 0.0328431, 1, 0, 0.510608,0.0136346) , 
7, 0.0092055, 1, 0, 0.519132,-0.00260924)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248441,-0.0343945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497018,-0.00268615) , 
5, 0.309935, 1, 0, 0.479812,-0.0211974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523384,-0.00807175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701974,0.0333882) , 
0, -3.58057, 1, 0, 0.641825,0.0891141) , 
6, 0.801588, 1, 0, 0.496767,-0.00965282)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185491,-0.0418767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432103,-0.00927786) , 
6, 0.775951, 1, 0, 0.328858,-0.100388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314719,-0.0173933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584795,0.00595671) , 
6, 0.507847, 1, 0, 0.521808,0.00254948) , 
5, 0.309935, 1, 0, 0.491059,-0.0138551)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484553,0.00393096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504437,-0.0197243) , 
1, 0.353688, 1, 0, 0.491501,-0.018039) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484899,0.0256381) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789709,0.0586805) , 
6, 0.469404, 1, 0, 0.630573,0.17766) , 
5, 2.37765, 1, 0, 0.500811,-0.00493823)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323592,-0.0386205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350387,-0.00714085) , 
7, 0.0336737, 1, 0, 0.341382,-0.0797063) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6701,0.0252103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521423,-0.00711549) , 
3, 0.480772, 1, 0, 0.565131,0.00940235) , 
1, 0.233206, 1, 0, 0.461904,-0.031708)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29935,-0.0781193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.784459,0.0315816) , 
3, 0.583481, 1, 0, 0.496234,-0.150286) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351603,-0.0170281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549207,0.00753647) , 
0, -11.059, 1, 0, 0.503701,0.00795989) , 
4, 0.305854, 1, 0, 0.503145,-0.00381911)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443441,-0.0178297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455139,0.00514337) , 
2, -0.000416792, 1, 0, 0.449904,-0.0231602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367522,-0.0148077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698011,0.0245574) , 
3, 0.197005, 1, 0, 0.582825,0.0465888) , 
6, 0.692259, 1, 0, 0.492724,-0.000690817)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617115,0.0112956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314984,-0.00780708) , 
2, 0.0249971, 1, 0, 0.502923,0.0180875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727071,0.0130145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337913,-0.0444414) , 
7, 0.0366791, 1, 0, 0.514357,-0.0900009) , 
1, 0.455908, 1, 0, 0.50503,-0.00183277)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707411,0.0209833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442948,-0.0103653) , 
7, 0.0458929, 1, 0, 0.590972,0.0247657) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37999,-0.000352959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385159,-0.0241674) , 
8, 0.477024, 1, 0, 0.383031,-0.0621477) , 
4, 0.556226, 1, 0, 0.483534,-0.0201402)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.242667,-0.0447915) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531534,0.00277694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427527,-0.0138398) , 
0, 2.74823, 1, 0, 0.496579,-0.0125204) , 
0, -92.0087, 1, 0, 0.488661,-0.0183072)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267476,-0.0315069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349649,0.013199) , 
2, 0.373332, 1, 0, 0.286814,-0.0876883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563343,0.00411788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185823,-0.0368904) , 
3, 1.3293, 1, 0, 0.546075,0.00955122) , 
0, -19.7966, 1, 0, 0.500905,-0.00739035)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614668,0.0378068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27142,-0.00560674) , 
2, 0.024434, 1, 0, 0.45821,0.0843947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385797,-0.0352889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564,0.00464891) , 
5, 0.449273, 1, 0, 0.548554,0.00357712) , 
8, 0.44589, 1, 0, 0.528784,0.0212624)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183657,-0.0363346) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505792,-0.00223739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.748461,0.0481705) , 
6, 0.859499, 1, 0, 0.514049,-0.00150238) , 
8, 0.252204, 1, 0, 0.495988,-0.00956394)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384954,-0.0411032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517029,0.00618785) , 
4, 0.35507, 1, 0, 0.507043,0.0101942) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66569,0.0290066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.868445,0.0549149) , 
5, 2.16787, 1, 0, 0.768267,0.174081) , 
1, 0.513395, 1, 0, 0.523952,0.0208029)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530244,-0.00414552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481466,-0.0402153) , 
6, 0.585209, 1, 0, 0.510791,-0.0753158) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600104,0.0163375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414186,-0.00597588) , 
2, 2.44058e-05, 1, 0, 0.490955,0.0150008) , 
4, 0.437496, 1, 0, 0.496786,-0.0115513)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498419,-0.00503534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.74636,0.0295693) , 
8, 0.699738, 1, 0, 0.651361,0.0680706) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428368,-0.0219046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389357,-0.00386206) , 
7, 0.0585029, 1, 0, 0.41421,-0.0650539) , 
4, 0.447592, 1, 0, 0.473139,-0.0319744)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376211,-0.0293229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412016,0.00368982) , 
7, 0.0461876, 1, 0, 0.393898,-0.0571625) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724754,0.0240681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291619,-0.0157709) , 
4, 0.568097, 1, 0, 0.621372,0.0590196) , 
8, 0.626147, 1, 0, 0.484931,-0.0106678)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391107,-0.0489397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555309,0.00368947) , 
7, 0.00351702, 1, 0, 0.542708,-0.000925328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224673,-0.0461361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320735,0.00082558) , 
2, 0.0489226, 1, 0, 0.268703,-0.113562) , 
7, 0.0949245, 1, 0, 0.481665,-0.0260185)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.15241,-0.0182402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.141426,-0.0506479) , 
6, 0.743589, 1, 0, 0.145409,-0.160086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534813,0.00664955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484983,-0.0225516) , 
1, 0.475245, 1, 0, 0.526211,0.0064888) , 
1, 0.0584586, 1, 0, 0.483394,-0.0122409)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470471,0.0175192) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457291,-0.0147153) , 
6, 0.73194, 1, 0, 0.465068,0.0147022) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457463,-0.0265598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674438,0.0187513) , 
1, 0.492269, 1, 0, 0.516773,-0.0599292) , 
1, 0.362383, 1, 0, 0.483732,-0.0122365)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476636,0.00841578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546071,-0.00867381) , 
8, 0.590026, 1, 0, 0.518461,-0.00739783) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21569,-0.0179579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197238,-0.0441114) , 
1, 0.0498473, 1, 0, 0.208012,-0.118213) , 
4, 0.855846, 1, 0, 0.47152,-0.0241536)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406809,0.0125646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445447,-0.0144432) , 
0, -24.375, 1, 0, 0.436556,-0.035322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620675,0.0144452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299758,-0.0193515) , 
7, 0.0859092, 1, 0, 0.538195,0.0237369) , 
0, -1.44256, 1, 0, 0.486507,-0.00629692)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232564,-0.0514791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461954,0.000635263) , 
4, 0.351109, 1, 0, 0.446942,-0.0130807) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864489,0.045635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529504,0.0093746) , 
7, 0.0368373, 1, 0, 0.681186,0.097511) , 
8, 0.684222, 1, 0, 0.510505,0.0169291)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542832,0.0102424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479367,-0.0310658) , 
8, 0.788466, 1, 0, 0.539097,0.0327598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.740895,0.04422) , 
8, 0.81879, 1, 0, 0.548081,0.0390883)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534758,-0.0184037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.726817,0.0357192) , 
5, 2.18392, 1, 0, 0.574208,-0.0308778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504394,0.00851837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864226,0.0657685) , 
1, 0.341319, 1, 0, 0.523232,0.0482306) , 
4, 0.471609, 1, 0, 0.542385,0.0185071)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429633,-0.000281415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624985,0.0336925) , 
5, 0.443147, 1, 0, 0.48334,0.0375131) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488291,0.00658336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498672,-0.0205301) , 
6, 0.573587, 1, 0, 0.494338,-0.0383304) , 
5, 0.618348, 1, 0, 0.491092,-0.0159413)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355427,-0.00256477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714795,0.0441331) , 
6, 0.494512, 1, 0, 0.4495,0.039373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54162,-0.0390238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485663,-0.00603237) , 
7, 0.00615932, 1, 0, 0.490865,-0.0377175) , 
6, 0.533372, 1, 0, 0.481188,-0.0196839)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436,-0.00205648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277074,-0.045321) , 
1, 0.507674, 1, 0, 0.429299,-0.0174042) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761512,0.027785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247838,-0.0194649) , 
3, 1.25186, 1, 0, 0.688025,0.0827663) , 
8, 0.684459, 1, 0, 0.496511,0.00861817)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421251,-0.0168541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422909,0.0123815) , 
7, 0.046034, 1, 0, 0.422136,-0.00696182) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711648,0.0284116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406875,-0.0225443) , 
0, 15.7758, 1, 0, 0.666031,0.0815029) , 
1, 0.29033, 1, 0, 0.53051,0.0323473)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462236,-0.00825552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0429061,-0.0620181) , 
7, 0.174537, 1, 0, 0.441486,-0.0446493) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70034,0.0266461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529942,7.68976e-05) , 
6, 0.749804, 1, 0, 0.590153,0.0395719) , 
6, 0.693686, 1, 0, 0.483468,-0.0208659)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326347,-0.0512113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499067,0.0103331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519556,-0.00591521) , 
6, 0.583398, 1, 0, 0.512961,-0.00370719) , 
4, 0.267458, 1, 0, 0.506822,-0.0111068)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809669,0.0338683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237027,-0.0338331) , 
2, 0.2463, 1, 0, 0.690981,0.072879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450397,-0.00214697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437022,-0.022368) , 
8, 0.667334, 1, 0, 0.446383,-0.0335205) , 
4, 0.388435, 1, 0, 0.485211,-0.0166303)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622034,0.0114438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492238,-0.0207432) , 
7, 0.0196911, 1, 0, 0.548375,-0.029314) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644515,0.0313871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395247,0.00391619) , 
7, 0.0660304, 1, 0, 0.472465,0.0547124) , 
7, 0.0431076, 1, 0, 0.51348,0.0093119)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385744,-0.000862419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299592,-0.0385287) , 
8, 0.508973, 1, 0, 0.352792,-0.0662554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563286,-0.00126319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653809,0.0421113) , 
4, 0.634975, 1, 0, 0.572864,0.0149798) , 
1, 0.175367, 1, 0, 0.500431,-0.0117572)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561484,0.00456405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237467,-0.0241545) , 
7, 0.128692, 1, 0, 0.517113,0.00253187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225342,-0.03807) , 
0, 36.4632, 1, 0, 0.501594,-0.00645811)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329717,-0.0222619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536164,-0.00058288) , 
6, 0.502561, 1, 0, 0.496073,-0.019479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408516,0.0303233) , 
2, 0.42089, 1, 0, 0.491418,-0.0124298)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485406,-0.0125897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390423,0.0170202) , 
7, 0.101609, 1, 0, 0.471625,-0.0351595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729957,0.0416687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371731,-0.00842802) , 
6, 0.883651, 1, 0, 0.589279,0.100853) , 
6, 0.801841, 1, 0, 0.483349,-0.0216059)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561621,0.00803021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280246,-0.0267518) , 
0, 30.8475, 1, 0, 0.544856,0.0244936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.151012,-0.0479262) , 
3, 1.3357, 1, 0, 0.521905,0.0111697)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276669,-0.0354472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339155,0.00429164) , 
3, 0.609673, 1, 0, 0.297718,-0.0942084) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465604,-0.00795092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588556,0.0139846) , 
0, -1.52054, 1, 0, 0.534768,0.0177628) , 
0, -32.5465, 1, 0, 0.51231,0.00715467)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63235,0.0520286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230716,0.00504995) , 
2, 0.0740788, 1, 0, 0.435264,0.120884) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500871,-0.00585988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261247,-0.0565201) , 
5, 2.77929, 1, 0, 0.492346,-0.0328982) , 
6, 0.456259, 1, 0, 0.487653,-0.0202545)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500864,0.0278586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46694,-0.0115595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417338,0.0292601) , 
2, 0.349937, 1, 0, 0.463968,-0.0386673) , 
3, 0.15089, 1, 0, 0.465979,-0.0300911)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543987,-0.0320052) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.65531,0.0165051) , 
7, 0.00364737, 1, 0, 0.64167,0.0414069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366326,-0.0199514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513719,0.014925) , 
0, 5.59259, 1, 0, 0.396958,-0.0550723) , 
7, 0.0369195, 1, 0, 0.493317,-0.0170822)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576948,0.00046771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362763,-0.0264191) , 
7, 0.0437518, 1, 0, 0.538843,-0.0188612) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596866,0.0267716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361157,-0.0014227) , 
7, 0.0817046, 1, 0, 0.451387,0.0413667) , 
7, 0.0553785, 1, 0, 0.504478,0.00480455)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593955,0.0362421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587402,0.00632556) , 
1, 0.206133, 1, 0, 0.588427,0.0461233) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351694,0.00660013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313231,-0.0190755) , 
8, 0.393243, 1, 0, 0.330526,-0.0323103) , 
4, 0.760123, 1, 0, 0.529199,0.0281106)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277614,-0.0313106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337375,-0.00657678) , 
7, 0.0277127, 1, 0, 0.315844,-0.0680133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659899,0.0342432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555699,-0.00714855) , 
8, 0.623319, 1, 0, 0.585363,0.0203324) , 
8, 0.516334, 1, 0, 0.48334,-0.0131096)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553325,0.00675944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461292,-0.0146582) , 
6, 0.81378, 1, 0, 0.543118,0.0177035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242397,-0.0290778) , 
0, 43.9327, 1, 0, 0.530619,0.0118858)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579169,0.00987194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227006,-0.019429) , 
7, 0.132291, 1, 0, 0.53475,0.0261248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313712,-0.0542446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226886,-0.0243499) , 
3, 1.17235, 1, 0, 0.270341,-0.169576) , 
5, 2.97016, 1, 0, 0.517023,0.0130039)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682545,0.00600753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418445,-0.0237267) , 
4, 0.415269, 1, 0, 0.471212,-0.0790866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196279,-0.0270119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553122,0.0139041) , 
8, 0.277636, 1, 0, 0.520014,0.0411338) , 
2, -0.000576744, 1, 0, 0.498421,-0.0120592)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373102,-0.0202949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370191,0.0162246) , 
7, 0.0703543, 1, 0, 0.372531,-0.0534708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67339,0.0150935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386835,-0.00827181) , 
4, 0.687681, 1, 0, 0.562028,0.0234437) , 
6, 0.554512, 1, 0, 0.500336,-0.00159636)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405827,-0.00406101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237341,-0.0448889) , 
2, -0.0352896, 1, 0, 0.301856,-0.133394) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568345,-0.0170015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516224,0.00366605) , 
7, 0.00615428, 1, 0, 0.521678,0.00639441) , 
2, -0.0251914, 1, 0, 0.494667,-0.0107827)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356811,-0.00732755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583849,0.021235) , 
1, 0.174682, 1, 0, 0.467831,0.0283263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712847,0.0100167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362948,-0.0273848) , 
7, 0.045639, 1, 0, 0.534274,-0.0448456) , 
8, 0.638187, 1, 0, 0.497466,-0.00431062)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608877,0.0053049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364066,-0.0194571) , 
2, 0.00567142, 1, 0, 0.501656,-0.0222392) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288185,-0.00478463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438273,0.0370414) , 
3, 0.447313, 1, 0, 0.373889,0.0727154) , 
2, 0.272017, 1, 0, 0.491454,-0.0146572)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503304,0.00251892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394647,-0.0365561) , 
1, 0.463152, 1, 0, 0.491133,-0.00804485) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585742,0.00838725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.876037,0.0573241) , 
6, 0.556399, 1, 0, 0.69416,0.103498) , 
8, 0.772057, 1, 0, 0.515865,0.00554272)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292357,-0.0364481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339184,0.0138572) , 
7, 0.0521875, 1, 0, 0.30512,-0.0917682) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573118,0.000633511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506997,0.0309611) , 
2, 0.0974711, 1, 0, 0.563707,0.0210713) , 
6, 0.505385, 1, 0, 0.506616,-0.00384135)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631302,0.0427569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1681,-0.0217133) , 
2, 0.0751369, 1, 0, 0.430412,0.0662804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515874,0.0290433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534312,-0.00615884) , 
0, -29.5931, 1, 0, 0.532826,-0.0137951) , 
6, 0.508989, 1, 0, 0.514582,0.000469553)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396239,0.00871904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482745,-0.0132456) , 
8, 0.433503, 1, 0, 0.464198,-0.0349694) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481795,-0.011961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.784802,0.0347897) , 
6, 0.504771, 1, 0, 0.654546,0.0550226) , 
1, 0.467587, 1, 0, 0.488424,-0.0235159)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333932,-0.0231616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.768127,0.0209622) , 
8, 0.511679, 1, 0, 0.610167,0.0100534) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399874,0.0251947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410046,-0.0153026) , 
8, 0.372275, 1, 0, 0.408933,-0.0485614) , 
7, 0.0307917, 1, 0, 0.480851,-0.0276133)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599198,0.0192773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213026,-0.0368349) , 
4, 0.533643, 1, 0, 0.310792,-0.0966222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658001,0.0134205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455034,-0.004061) , 
2, -0.000299776, 1, 0, 0.522905,0.00777553) , 
2, -0.0249881, 1, 0, 0.495064,-0.00592725)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394195,0.007133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492571,-0.0119227) , 
1, 0.154403, 1, 0, 0.466948,-0.029263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712394,0.0114938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559829,0.0348107) , 
3, 0.894072, 1, 0, 0.63144,0.0921626) , 
5, 2.13173, 1, 0, 0.481779,-0.0183151)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315414,-0.0121173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234667,-0.0499753) , 
8, 0.607698, 1, 0, 0.277785,-0.135729) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610398,0.00729515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352378,-0.00813464) , 
4, 0.70016, 1, 0, 0.525797,0.00847005) , 
2, -0.0251914, 1, 0, 0.493273,-0.0104404)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504017,-0.0164426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373771,0.00858314) , 
2, 0.0247131, 1, 0, 0.460963,-0.0334974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.746259,0.0479842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540711,0.00353568) , 
6, 0.718109, 1, 0, 0.572775,0.0427992) , 
6, 0.687859, 1, 0, 0.495144,-0.0101736)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275851,-0.0426141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530244,0.00120624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20345,-0.022995) , 
7, 0.138444, 1, 0, 0.496649,-0.0048056) , 
0, -77.6342, 1, 0, 0.488334,-0.0116223)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826738,0.0442872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634352,0.013959) , 
8, 0.735809, 1, 0, 0.768939,0.126027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495644,-0.0196277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460724,0.0029992) , 
7, 0.0298499, 1, 0, 0.470747,-0.0130246) , 
7, 0.0091937, 1, 0, 0.50276,0.0019037)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390169,0.024144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538157,-0.000783025) , 
1, 0.168427, 1, 0, 0.512709,0.0131775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500804,0.00596534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.854815,0.0506247) , 
5, 0.452938, 1, 0, 0.616127,0.0849355) , 
6, 0.726456, 1, 0, 0.537472,0.0303602)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387931,-0.00714028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405978,-0.0333764) , 
8, 0.594101, 1, 0, 0.391545,-0.0523787) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79016,0.0262932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452956,-0.0101221) , 
3, 0.646342, 1, 0, 0.58842,0.0148904) , 
8, 0.650294, 1, 0, 0.464709,-0.0273797)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56187,-0.00184593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445857,0.0256029) , 
2, 0.0749901, 1, 0, 0.539462,0.0136908) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773585,0.0489919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400188,-0.0049788) , 
2, 0.022582, 1, 0, 0.636607,0.129394) , 
6, 0.804639, 1, 0, 0.549651,0.0258265)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582093,0.00945453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353896,-0.0218034) , 
0, 12.6815, 1, 0, 0.544717,0.016603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167093,-0.0374358) , 
4, 0.917248, 1, 0, 0.515119,0.00340588)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.353616,-0.0393926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635191,0.00110712) , 
3, 0.545986, 1, 0, 0.525893,-0.0630817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540225,0.00951549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3019,-0.00961657) , 
7, 0.0923046, 1, 0, 0.476264,0.0179091) , 
4, 0.411553, 1, 0, 0.488742,-0.00245295)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697966,-0.00219037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377902,-0.0294225) , 
7, 0.0305661, 1, 0, 0.492239,-0.0865919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490196,0.00166686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605772,0.0389685) , 
6, 0.859324, 1, 0, 0.499057,0.019424) , 
4, 0.447563, 1, 0, 0.496772,-0.0161095)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.82036,0.036175) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483629,-0.00613167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304075,-0.0388795) , 
8, 0.804312, 1, 0, 0.472755,-0.0340551) , 
4, 0.315463, 1, 0, 0.492507,-0.0247688)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425741,0.00735669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358896,-0.0272681) , 
8, 0.477065, 1, 0, 0.385472,-0.0566285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553252,-0.00474595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743317,0.0312844) , 
4, 0.479596, 1, 0, 0.59758,0.012811) , 
1, 0.285224, 1, 0, 0.489301,-0.0226372)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.338305,-0.0379135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398546,-0.00239782) , 
7, 0.0458537, 1, 0, 0.365832,-0.0957876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486617,-0.00152624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724517,0.0252359) , 
6, 0.661303, 1, 0, 0.535169,0.0150907) , 
5, 0.620909, 1, 0, 0.475985,-0.0236613)    );
   return;
};

// Clean up
inline void ReadBDT-0.3_fold10::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.3_fold10::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
