// Class: ReadBDT-0.3_fold2
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.3_fold2
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/00       [401408]
Creator        : htan
Date           : Fri Aug 16 14:18:06 2024
Host           : Linux 6772f6b99311 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May 9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gluster/home/htan/ZTTBDT
Training events: 104945
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
m_pT_asymm                    m_pT_asymm                    m_pT_asymm                    m_pT_asymm                                                      'F'    [1.16390037874e-05,0.946852445602]
m_sigmaCosDelPhi              m_sigmaCosDelPhi              m_sigmaCosDelPhi              m_sigmaCosDelPhi                                                'F'    [-0.049986757338,1.9745773077]
m_ratioMetTauPT               m_ratioMetTauPT               m_ratioMetTauPT               m_ratioMetTauPT                                                 'F'    [0.00113642180804,11.9963302612]
m_ratioMuonTauPT              m_ratioMuonTauPT              m_ratioMuonTauPT              m_ratioMuonTauPT                                                'F'    [0.0272991936654,0.999976694584]
m_ratioMetMuonPT              m_ratioMetMuonPT              m_ratioMetMuonPT              m_ratioMetMuonPT                                                'F'    [0.00152266630903,24.9829425812]
m_ratioMuonTauM3              m_ratioMuonTauM3              m_ratioMuonTauM3              m_ratioMuonTauM3                                                'F'    [0.00183517555706,0.996654033661]
m_ratioMuonMetM3              m_ratioMuonMetM3              m_ratioMuonMetM3              m_ratioMuonMetM3                                                'F'    [1.27644239001e-06,0.249402225018]
m_ratioMetTauM3               m_ratioMetTauM3               m_ratioMetTauM3               m_ratioMetTauM3                                                 'F'    [5.56223167223e-05,0.977119266987]
NSpec 1
m_event_number                m_event_number                m_event_number                I                                                               'F'    [113,1214786176]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.3_fold2Node

#ifndef BDT-0.3_fold2Node__def
#define BDT-0.3_fold2Node__def

class BDT-0.3_fold2Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.3_fold2Node ( BDT-0.3_fold2Node* left,BDT-0.3_fold2Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.3_fold2Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold2Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold2Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.3_fold2Node*   fLeft;     // pointer to the left daughter node
   BDT-0.3_fold2Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.3_fold2Node::~BDT-0.3_fold2Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.3_fold2Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.3_fold2Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.3_fold2 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.3_fold2( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.3_fold2" ),
        fNvars( 8 )
   {
      // the training input variables
      const char* inputVars[] = { "m_pT_asymm", "m_sigmaCosDelPhi", "m_ratioMetTauPT", "m_ratioMuonTauPT", "m_ratioMetMuonPT", "m_ratioMuonTauM3", "m_ratioMuonMetM3", "m_ratioMetTauM3" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.3_fold2() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.3_fold2Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.3_fold2::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.3_fold2Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.3_fold2Node*)current->GetRight();
         else current=(BDT-0.3_fold2Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.3_fold2::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376238,-0.0247525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713134,0.0426268) , 
7, 0.507245, 1, 0, 0.599763,0.0997627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.293206,-0.0413589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484518,-0.00309645) , 
5, 0.748598, 1, 0, 0.334221,-0.165779) , 
6, 0.06774, 1, 0, 0.507696,0.007696)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316941,-0.0373236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0942266,-0.0803702) , 
3, 0.592725, 1, 0, 0.248735,-0.252205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437118,-0.0118616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676268,0.0333152) , 
0, 0.280557, 1, 0, 0.54359,0.0411701) , 
5, 0.471225, 1, 0, 0.503766,0.00154564)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402029,-0.0200738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653965,0.028834) , 
1, -0.0106636, 1, 0, 0.563075,0.055747) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167706,-0.0631094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372123,-0.0257212) , 
7, 0.384598, 1, 0, 0.328351,-0.168219) , 
1, 0.024084, 1, 0, 0.48089,-0.0226719)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275187,-0.0410537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64662,0.0260519) , 
5, 0.469058, 1, 0, 0.609703,0.0964356) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244306,-0.0451613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498294,0.000684334) , 
0, 0.276999, 1, 0, 0.36053,-0.120186) , 
1, 0.0247092, 1, 0, 0.518867,0.0174661)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.251135,-0.0475931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363832,-0.0209304) , 
6, 0.0275697, 1, 0, 0.325327,-0.14921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38182,-0.0238428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641785,0.0231415) , 
5, 0.500822, 1, 0, 0.585691,0.064428) , 
7, 0.504532, 1, 0, 0.496669,-0.00861792)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635199,0.0212663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346617,-0.026717) , 
6, 0.0861433, 1, 0, 0.5736,0.0543347) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.157953,-0.0633845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385502,-0.0179635) , 
0, 0.0456116, 1, 0, 0.329834,-0.143895) , 
3, 0.688167, 1, 0, 0.492447,-0.0116589)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619402,0.0173147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334751,-0.0286029) , 
3, 0.844384, 1, 0, 0.58182,0.0552183) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25224,-0.03881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515728,0.00472621) , 
7, 0.564258, 1, 0, 0.373605,-0.0917696) , 
1, 0.025001, 1, 0, 0.512593,0.00634823)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423447,-0.00854218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.784145,0.0444432) , 
7, 0.551995, 1, 0, 0.64467,0.116761) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434351,-0.012181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225006,-0.0450219) , 
6, 0.135669, 1, 0, 0.39454,-0.0906991) , 
6, 0.0400288, 1, 0, 0.504337,0.000367559)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272518,-0.0409652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.544077,0.00232267) , 
0, 0.401185, 1, 0, 0.392406,-0.107252) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452084,-0.00491664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728662,0.0340179) , 
0, 0.28058, 1, 0, 0.561524,0.0507598) , 
5, 0.558326, 1, 0, 0.507129,-6.36243e-05)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583207,0.0217367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306068,-0.0274789) , 
6, 0.0123491, 1, 0, 0.333062,-0.110231) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681625,0.0206312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433039,-0.0141602) , 
6, 0.0490918, 1, 0, 0.576251,0.0275784) , 
7, 0.552253, 1, 0, 0.473415,-0.0306965)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396098,-0.00839252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173628,-0.055267) , 
4, 0.627852, 1, 0, 0.322813,-0.115667) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329863,-0.0347219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614855,0.0155425) , 
1, -0.0251962, 1, 0, 0.578486,0.0434905) , 
0, 0.186583, 1, 0, 0.489982,-0.0116038)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584182,0.010426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200435,-0.0453429) , 
3, 0.864046, 1, 0, 0.532428,0.0140051) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175366,-0.0642312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305452,-0.0226788) , 
6, 0.0460224, 1, 0, 0.255181,-0.188073) , 
1, 0.14997, 1, 0, 0.477462,-0.0260582)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.906454,0.0641794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629649,0.0238672) , 
6, 0.0366791, 1, 0, 0.779983,0.218778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409239,-0.0198647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527062,0.0112488) , 
5, 0.689611, 1, 0, 0.450783,-0.0424533) , 
3, 0.328375, 1, 0, 0.471952,-0.0256552)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658768,0.0230884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411802,-0.00791615) , 
1, 0.0250102, 1, 0, 0.572329,0.0590727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.158667,-0.049886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297776,-0.0191339) , 
0, 0.0266539, 1, 0, 0.225086,-0.166607) , 
3, 0.88065, 1, 0, 0.531056,0.0322486)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394092,-0.0208389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673822,0.0219819) , 
1, -0.0167754, 1, 0, 0.60031,0.0503392) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473246,-0.00127356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212547,-0.0353369) , 
3, 0.591614, 1, 0, 0.336874,-0.0884291) , 
1, 0.0247223, 1, 0, 0.503698,-0.000552374)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280493,-0.0261937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563859,0.00530289) , 
0, 0.0935446, 1, 0, 0.512716,-0.00170871) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786407,0.043873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255971,-0.0437626) , 
3, 0.373529, 1, 0, 0.334593,-0.149128) , 
2, 0.743162, 1, 0, 0.476343,-0.0318117)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557634,0.00132835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28104,-0.0307563) , 
1, 0.0496288, 1, 0, 0.468537,-0.0424789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.779415,0.0538562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382864,-0.0030119) , 
1, 0.0235135, 1, 0, 0.630133,0.156326) , 
5, 0.698825, 1, 0, 0.514972,0.014648)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316689,-0.0220243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2068,-0.0481608) , 
2, 0.805953, 1, 0, 0.261736,-0.165029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.242252,-0.031407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584115,0.012096) , 
7, 0.272547, 1, 0, 0.558819,0.0425644) , 
5, 0.46854, 1, 0, 0.518683,0.0145186)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543494,0.00198095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2579,-0.0402698) , 
6, 0.0368185, 1, 0, 0.38525,-0.101284) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725752,0.02644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433662,-0.00754661) , 
3, 0.551204, 1, 0, 0.539257,0.0216418) , 
5, 0.557755, 1, 0, 0.489349,-0.0181942)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76831,0.0339078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404752,-0.0141577) , 
3, 0.596316, 1, 0, 0.612841,0.0593943) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331455,-0.0257642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499,0.00890213) , 
5, 0.655732, 1, 0, 0.396805,-0.0579532) , 
6, 0.0400286, 1, 0, 0.495425,-0.00438432)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.143592,-0.0478555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540809,0.00158462) , 
7, 0.276361, 1, 0, 0.510817,-0.00908098) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274328,-0.0197248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123496,-0.0622352) , 
0, 0.208714, 1, 0, 0.190485,-0.204789) , 
6, 0.12886, 1, 0, 0.469366,-0.0344058)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291365,-0.0346471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518044,-0.00201991) , 
2, 0.352735, 1, 0, 0.471327,-0.0411749) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725691,0.045463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34438,-0.0119025) , 
3, 0.857628, 1, 0, 0.586288,0.117798) , 
5, 0.775583, 1, 0, 0.487028,-0.0194635)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628771,0.0090658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307259,-0.0287465) , 
6, 0.036708, 1, 0, 0.437855,-0.0623366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778665,0.0345325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427539,-0.00974027) , 
3, 0.555667, 1, 0, 0.535661,0.0159972) , 
5, 0.591357, 1, 0, 0.497769,-0.0143515)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852375,0.0470223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466985,-0.00452969) , 
3, 0.596535, 1, 0, 0.688364,0.110516) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404217,-0.018311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515291,0.00423612) , 
5, 0.691863, 1, 0, 0.438265,-0.0525243) , 
6, 0.0122736, 1, 0, 0.47262,-0.0301282)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809356,0.0426243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47785,-0.00383578) , 
1, 0.024118, 1, 0, 0.693658,0.118803) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.338178,-0.0218171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529491,0.00488323) , 
5, 0.608877, 1, 0, 0.464131,-0.0191393) , 
3, 0.43556, 1, 0, 0.522703,0.0160618)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.246185,-0.0581972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276965,-0.0229968) , 
3, 0.343847, 1, 0, 0.267184,-0.159305) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506065,-0.00104864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.841578,0.0462798) , 
0, 0.498044, 1, 0, 0.528978,0.00937871) , 
5, 0.485271, 1, 0, 0.485053,-0.0189237)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572508,-0.00147045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354709,-0.0213916) , 
3, 0.555667, 1, 0, 0.467871,-0.0508166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656375,0.0443258) , 
5, 0.838369, 1, 0, 0.478737,-0.0358314)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4908,0.000323473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361865,-0.0343881) , 
5, 0.667318, 1, 0, 0.472032,-0.0219739) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.820495,0.0475338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56793,0.0140048) , 
6, 0.0183111, 1, 0, 0.61253,0.0921472) , 
5, 0.701893, 1, 0, 0.512721,0.0110761)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504549,0.00723328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364948,-0.0205672) , 
2, 0.434511, 1, 0, 0.44035,-0.0254407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727348,0.0267239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236998,-0.0260075) , 
2, 1.1884, 1, 0, 0.628553,0.0720286) , 
7, 0.674369, 1, 0, 0.501242,0.00609469)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745651,0.0271838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37441,-0.0154344) , 
1, 0.0983965, 1, 0, 0.657897,0.0742002) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434258,0.00232895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34008,-0.0283765) , 
7, 0.60791, 1, 0, 0.411779,-0.0231472) , 
3, 0.555667, 1, 0, 0.527124,0.0224755)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3012,-0.0299956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.665574,0.01657) , 
1, -0.024989, 1, 0, 0.593484,0.0321606) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270243,-0.0442074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344593,-0.00271869) , 
6, 0.0429543, 1, 0, 0.315067,-0.0889839) , 
1, 0.025001, 1, 0, 0.486079,-0.0145734)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538545,-0.0167118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.821929,0.0441058) , 
6, 0.00317852, 1, 0, 0.724454,0.0984777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433372,-0.028968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450148,-0.00374242) , 
3, 0.375522, 1, 0, 0.447338,-0.0360012) , 
6, 0.0122576, 1, 0, 0.484937,-0.017755)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784688,0.0315214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410554,-0.00425494) , 
1, 0.123415, 1, 0, 0.687646,0.0940755) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476115,-0.00184045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192846,-0.0385381) , 
3, 0.923345, 1, 0, 0.451779,-0.0225802) , 
3, 0.436282, 1, 0, 0.507247,0.00485311)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80468,0.0412465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667094,-0.0123757) , 
4, 1.502, 1, 0, 0.760166,0.102619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354592,-0.0124761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572659,0.00396571) , 
0, 0.253859, 1, 0, 0.46756,-0.0181801) , 
6, 0.00923078, 1, 0, 0.497367,-0.00587442)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296055,-0.0282498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.694114,0.0192953) , 
7, 0.530897, 1, 0, 0.630968,0.0501035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439196,0.00154082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277407,-0.0298721) , 
4, 0.643949, 1, 0, 0.362963,-0.0594535) , 
3, 0.56764, 1, 0, 0.489645,-0.00766752)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.231761,-0.0321497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525323,0.00243408) , 
2, 0.333807, 1, 0, 0.481193,-0.0117078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529967,0.0117331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.792561,0.0428792) , 
7, 0.580432, 1, 0, 0.602522,0.0917646) , 
5, 0.689611, 1, 0, 0.517043,0.0188662)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29899,-0.0633978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448174,-0.0056376) , 
3, 0.347626, 1, 0, 0.441208,-0.0375392) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.82344,0.0313022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471727,-0.00267633) , 
6, 0.0365441, 1, 0, 0.621885,0.0451727) , 
7, 0.687619, 1, 0, 0.494347,-0.0132131)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.199656,-0.0531932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479869,0.0039774) , 
4, 1.55845, 1, 0, 0.343238,-0.106629) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567534,0.00990896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491586,-0.0128147) , 
2, 0.568813, 1, 0, 0.541645,0.0102596) , 
5, 0.517667, 1, 0, 0.497205,-0.0159213)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44234,-0.014661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534333,0.0264624) , 
6, 0.0398344, 1, 0, 0.490463,0.0298337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674694,0.00777007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350813,-0.024295) , 
6, 0.0398154, 1, 0, 0.49807,-0.045638) , 
4, 0.891424, 1, 0, 0.494539,-0.0106085)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461945,-0.00231581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.854536,0.0521991) , 
0, 0.426655, 1, 0, 0.480863,0.000606106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313893,-0.0462238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.659681,0.00451363) , 
7, 0.746636, 1, 0, 0.488018,-0.0942282) , 
0, 0.45474, 1, 0, 0.482124,-0.0161013)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278495,-0.0216783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592046,0.0133251) , 
5, 0.46854, 1, 0, 0.549314,0.0381923) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228899,-0.0411708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265126,-0.00982234) , 
1, 0.0736994, 1, 0, 0.2476,-0.114517) , 
6, 0.12886, 1, 0, 0.508256,0.0174111)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307666,-0.00783467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303003,-0.0231107) , 
7, 0.352705, 1, 0, 0.305027,-0.0742995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547732,0.0316899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583368,0.00406854) , 
0, 0.162634, 1, 0, 0.579542,0.0310164) , 
7, 0.468332, 1, 0, 0.496377,-0.000889301)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.187098,-0.0374307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533762,0.00216333) , 
7, 0.264646, 1, 0, 0.511263,-0.00122064) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219906,-0.019191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177824,-0.0438709) , 
5, 0.675961, 1, 0, 0.196377,-0.147687) , 
6, 0.159333, 1, 0, 0.490646,-0.0108105)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496004,0.0122105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525271,-0.0128484) , 
7, 0.591371, 1, 0, 0.512654,-0.0075811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149946,-0.0424043) , 
3, 0.939882, 1, 0, 0.489967,-0.0183647)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.910676,0.0491161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622184,0.025086) , 
6, 0.0305665, 1, 0, 0.766314,0.149806) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470361,-0.00308363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580063,0.0144222) , 
5, 0.765378, 1, 0, 0.489314,0.000482758) , 
3, 0.324048, 1, 0, 0.508529,0.0108412)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215474,-0.0316701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404229,-0.00634635) , 
5, 0.786856, 1, 0, 0.274541,-0.103471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67461,0.0133039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308628,-0.0206773) , 
6, 0.0795967, 1, 0, 0.576942,0.0161957) , 
7, 0.468233, 1, 0, 0.484569,-0.0203583)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308172,-0.0235845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538654,0.00151545) , 
1, -0.0253476, 1, 0, 0.506541,-0.00926653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.113481,-0.0540075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301127,-0.00210497) , 
6, 0.165016, 1, 0, 0.200343,-0.130004) , 
6, 0.135479, 1, 0, 0.469165,-0.0240042)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497238,0.000162949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357371,-0.03473) , 
5, 0.678303, 1, 0, 0.482055,-0.0157563) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167897,-0.0382109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695784,0.0290081) , 
0, 0.0461888, 1, 0, 0.601773,0.0784384) , 
5, 0.704055, 1, 0, 0.513425,0.00892537)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440168,-0.00635401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764247,0.0274263) , 
5, 0.497995, 1, 0, 0.671739,0.0723853) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238227,-0.0311669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450685,-0.0026748) , 
1, -0.0252837, 1, 0, 0.418467,-0.0308593) , 
3, 0.483598, 1, 0, 0.498426,0.00173536)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407943,-0.0514817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550753,-0.00280533) , 
6, 0.00361246, 1, 0, 0.538526,-0.0288144) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846315,0.0771419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447751,0.0157075) , 
6, 0.0655765, 1, 0, 0.486941,0.0959694) , 
6, 0.0585029, 1, 0, 0.520913,0.0137909)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48184,-0.0137292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.840823,0.0307944) , 
0, 0.441273, 1, 0, 0.551275,-0.0262001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617532,0.0308458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392508,0.000307133) , 
6, 0.0687124, 1, 0, 0.465387,0.0456287) , 
6, 0.0461488, 1, 0, 0.512287,0.00640634)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41678,-0.0104831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611311,0.012696) , 
5, 0.554512, 1, 0, 0.54388,0.0210174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.100816,-0.05177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259728,-0.0111321) , 
2, 0.402823, 1, 0, 0.166079,-0.148756) , 
6, 0.160111, 1, 0, 0.512156,0.00676131)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445265,0.00316373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385364,-0.0376053) , 
5, 0.547682, 1, 0, 0.417441,-0.0693247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603602,0.0124216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26793,-0.0245344) , 
1, 0.144958, 1, 0, 0.546166,0.0270852) , 
5, 0.615921, 1, 0, 0.481567,-0.0212972)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657567,0.0101594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465081,-0.0174284) , 
6, 0.0251133, 1, 0, 0.56493,-0.0151178) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465895,0.0135482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369485,-0.0244288) , 
0, 0.526047, 1, 0, 0.457652,0.0442252) , 
6, 0.0521585, 1, 0, 0.523433,0.00783709)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446151,0.00737925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210923,-0.0632139) , 
7, 0.622749, 1, 0, 0.330572,-0.131805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244277,-0.0247637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531105,-0.00161673) , 
7, 0.349997, 1, 0, 0.496126,-0.0187316) , 
1, -0.0249703, 1, 0, 0.475592,-0.0327561)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.164192,-0.0379881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563378,0.0179659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537696,-0.000119524) , 
4, 0.686475, 1, 0, 0.545335,0.0238411) , 
7, 0.265431, 1, 0, 0.521445,0.0127426)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262933,-0.0278274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525764,0.0133954) , 
5, 0.791567, 1, 0, 0.349293,-0.0598396) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624025,0.0245802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570048,-0.00499028) , 
0, 0.353982, 1, 0, 0.59465,0.0371566) , 
0, 0.174213, 1, 0, 0.513273,0.00498606)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650408,0.0135543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338688,-0.0207589) , 
6, 0.0929673, 1, 0, 0.605068,0.0354654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279906,-0.0488012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356081,-0.00427074) , 
6, 0.0152546, 1, 0, 0.343156,-0.0522129) , 
1, 0.0243662, 1, 0, 0.511727,0.00421841)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549834,0.00919359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40125,-0.0104572) , 
2, 0.667196, 1, 0, 0.508219,0.0156832) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562844,-0.00277218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266216,-0.082176) , 
5, 0.525695, 1, 0, 0.412564,-0.191328) , 
0, 0.549421, 1, 0, 0.50224,0.00274345)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341111,-0.0381202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615422,-0.00191887) , 
7, 0.61418, 1, 0, 0.529483,-0.0575689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652598,0.0407348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388493,-0.00202692) , 
3, 0.674178, 1, 0, 0.455847,0.0385002) , 
3, 0.581098, 1, 0, 0.495654,-0.013434)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603707,0.0175158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301239,-0.00797523) , 
1, 0.0249971, 1, 0, 0.493944,0.0382493) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708078,0.0118915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386965,-0.0339301) , 
3, 0.411567, 1, 0, 0.49603,-0.0789438) , 
7, 0.639369, 1, 0, 0.494908,-0.0158969)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.191912,-0.0507989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349618,-0.0180905) , 
1, -0.0348685, 1, 0, 0.2576,-0.17085) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513253,-0.0225946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502047,0.00105684) , 
3, 0.37972, 1, 0, 0.504333,-0.015229) , 
1, -0.0249921, 1, 0, 0.474275,-0.0341873)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668526,0.0199105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390089,0.000436537) , 
6, 0.0429546, 1, 0, 0.529773,0.0417119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445749,-0.0140311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.665636,0.011198) , 
4, 0.601142, 1, 0, 0.518356,-0.0271484) , 
5, 0.663358, 1, 0, 0.524684,0.0110158)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.164273,-0.0301684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542971,0.00609528) , 
7, 0.274257, 1, 0, 0.508773,0.0131851) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346061,-0.0795399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629926,0.0370459) , 
4, 2.36789, 1, 0, 0.471598,-0.110207) , 
7, 0.792592, 1, 0, 0.504667,-0.000442749)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167676,-0.0322128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521728,0.0120616) , 
0, 0.0446335, 1, 0, 0.479685,0.0304184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434449,-0.0328573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609616,8.88155e-05) , 
0, 0.426242, 1, 0, 0.533526,-0.0602114) , 
0, 0.361462, 1, 0, 0.499264,-0.00254001)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522575,0.00858758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415275,-0.0109078) , 
4, 0.911562, 1, 0, 0.485129,0.00739734) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809058,0.0500879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614525,0.00862942) , 
7, 0.737706, 1, 0, 0.677555,0.0897403) , 
7, 0.687678, 1, 0, 0.540918,0.0312703)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443733,0.00505346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702971,0.0429009) , 
4, 0.455588, 1, 0, 0.501219,0.0559525) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423434,-0.0195294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630651,0.00923342) , 
7, 0.687376, 1, 0, 0.50761,-0.0351285) , 
4, 0.59479, 1, 0, 0.50577,-0.00889431)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472432,-0.0372338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606824,0.0111374) , 
6, 0.00394128, 1, 0, 0.595929,0.0312498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285903,-0.0249513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345665,0.0149369) , 
1, 0.123125, 1, 0, 0.302761,-0.0621518) , 
6, 0.079772, 1, 0, 0.50644,0.00273908)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647711,0.0150235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428176,-0.0127709) , 
2, 0.691225, 1, 0, 0.597648,0.0369575) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.249971,-0.0439723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307285,-0.00148495) , 
6, 0.0459318, 1, 0, 0.286781,-0.0724541) , 
1, 0.0749901, 1, 0, 0.516651,0.00845003)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58714,0.0219296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171831,-0.0411424) , 
1, 0.368407, 1, 0, 0.549592,0.0696118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430811,-0.0226553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569105,0.00312968) , 
4, 1.44352, 1, 0, 0.498615,-0.0429507) , 
4, 0.880724, 1, 0, 0.520407,0.00516911)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431162,-0.0315507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459325,0.00771151) , 
6, 0.0304594, 1, 0, 0.448795,-0.0313243) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769838,0.0270211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414587,-0.00536018) , 
1, 0.0489406, 1, 0, 0.670833,0.0684378) , 
7, 0.651605, 1, 0, 0.532869,0.00645038)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535466,-0.0351767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564093,0.00387515) , 
6, 0.00615428, 1, 0, 0.561056,8.0809e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237621,-0.0505211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334354,-0.0136798) , 
3, 0.714859, 1, 0, 0.319304,-0.0819298) , 
3, 0.687759, 1, 0, 0.480419,-0.0272742)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455199,-0.00612348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432219,-0.0423799) , 
7, 0.673823, 1, 0, 0.453014,-0.0410821) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568624,0.00213672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.880683,0.049022) , 
0, 0.489751, 1, 0, 0.641362,0.0492358) , 
7, 0.699738, 1, 0, 0.504318,-0.0164804)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.250038,-0.00666608) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553876,0.0292497) , 
7, 0.30543, 1, 0, 0.427902,0.0654092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341394,-0.0262698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588522,0.00332651) , 
7, 0.50259, 1, 0, 0.560924,-0.000720887) , 
7, 0.457861, 1, 0, 0.531318,0.0139972)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558509,-0.00810289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715355,0.0343703) , 
3, 0.496921, 1, 0, 0.58451,-0.00403291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404031,-0.00665018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31756,-0.0397077) , 
0, 0.208073, 1, 0, 0.371321,-0.0837146) , 
3, 0.555637, 1, 0, 0.465287,-0.0485936)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209305,-0.0259091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586892,0.0108502) , 
5, 0.468511, 1, 0, 0.487709,0.00710947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461531,-0.0156523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397748,-0.0613057) , 
0, 0.376492, 1, 0, 0.453933,-0.0882089) , 
5, 0.651767, 1, 0, 0.472506,-0.0357953)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74007,0.0266973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483708,-0.0120122) , 
6, 0.00923776, 1, 0, 0.516385,-0.0311057) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396862,0.0120049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.731164,0.0670615) , 
5, 0.796543, 1, 0, 0.45778,0.0972332) , 
6, 0.0831349, 1, 0, 0.504529,-0.00514359)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652392,0.00786501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822155,0.0482796) , 
3, 0.386536, 1, 0, 0.699875,0.076481) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463278,0.0024333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326819,-0.0450005) , 
0, 0.358191, 1, 0, 0.439887,-0.0245292) , 
3, 0.425545, 1, 0, 0.498941,-0.0015856)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422819,-0.0193252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747292,0.0183956) , 
1, -0.00847109, 1, 0, 0.528127,-0.035052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506854,0.00841033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269579,-0.0371577) , 
7, 0.840578, 1, 0, 0.493381,0.0235731) , 
1, -0.00052964, 1, 0, 0.506973,0.000638644)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622311,7.89931e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466207,-0.0616566) , 
4, 1.23739, 1, 0, 0.534743,-0.123099) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532464,0.0100917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478564,-0.0116731) , 
5, 0.66748, 1, 0, 0.50963,0.0023609) , 
6, 0.00615428, 1, 0, 0.512069,-0.00982628)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419703,-0.0115126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.65004,0.0150718) , 
7, 0.695948, 1, 0, 0.482206,-0.0201295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653031,0.0444064) , 
5, 0.861555, 1, 0, 0.489889,-0.0103802)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668738,0.0198522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516119,-0.0168865) , 
1, 0.00680455, 1, 0, 0.643893,0.056842) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234666,-0.0499842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364699,0.00182719) , 
6, 0.0153416, 1, 0, 0.33793,-0.0370568) , 
1, 0.0242083, 1, 0, 0.531006,0.0221975)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340342,-0.0601463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652983,-0.00331309) , 
4, 2.1933, 1, 0, 0.468655,-0.153799) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430248,-0.00421388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.636976,0.0161449) , 
0, 0.334342, 1, 0, 0.492974,0.00686003) , 
3, 0.332003, 1, 0, 0.490078,-0.0122705)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566208,0.0107079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499098,-0.00682824) , 
2, 0.447026, 1, 0, 0.524112,-0.00053668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179143,-0.0386051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202083,-0.0207714) , 
6, 0.1791, 1, 0, 0.190196,-0.12485) , 
6, 0.159333, 1, 0, 0.498438,-0.0100946)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478723,-0.00357066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715906,0.0328589) , 
4, 1.44065, 1, 0, 0.507896,0.0027607) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476026,-0.00237388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350806,-0.0604093) , 
5, 0.536998, 1, 0, 0.432965,-0.0942859) , 
4, 1.852, 1, 0, 0.49385,-0.0154309)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480544,-0.020272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.658461,0.0152407) , 
2, 0.581995, 1, 0, 0.535861,-0.0404807) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653405,0.039301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424796,0.008949) , 
3, 0.423552, 1, 0, 0.461792,0.0594959) , 
6, 0.0554237, 1, 0, 0.508142,-0.00306618)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661725,0.0105517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.716774,0.0356482) , 
6, 0.0115673, 1, 0, 0.678499,0.0708756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452819,-0.0176997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376951,0.00779362) , 
1, 0.0745272, 1, 0, 0.435612,-0.0524283) , 
6, 0.0183737, 1, 0, 0.484883,-0.0274155)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153753,-0.011211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573581,0.0372017) , 
0, 0.2557, 1, 0, 0.451435,0.100773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552709,-0.00163658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195385,-0.0303506) , 
6, 0.134731, 1, 0, 0.508372,-0.0216212) , 
5, 0.486161, 1, 0, 0.500711,-0.00515373)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550602,-0.00259285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.857144,0.0483838) , 
5, 0.723741, 1, 0, 0.586944,0.014247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373802,-0.000385521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289277,-0.0295461) , 
0, 0.125495, 1, 0, 0.341128,-0.0499318) , 
3, 0.701739, 1, 0, 0.511332,-0.00549417)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604111,0.0192773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345534,-0.0236733) , 
6, 0.00920584, 1, 0, 0.377027,-0.0763322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604706,0.0100092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270006,-0.017067) , 
6, 0.129321, 1, 0, 0.556952,0.0255322) , 
5, 0.546934, 1, 0, 0.503282,-0.00485309)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358388,-0.0266741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343902,0.0102359) , 
3, 0.867923, 1, 0, 0.355085,-0.0810594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707964,0.0196053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424597,-0.00296007) , 
6, 0.0428773, 1, 0, 0.568019,0.0316068) , 
2, 0.297314, 1, 0, 0.513693,0.00286215)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583144,0.00382913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.76407,0.0636458) , 
3, 0.655096, 1, 0, 0.593102,0.0300995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29817,-0.00338751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335689,-0.0311304) , 
5, 0.742225, 1, 0, 0.318123,-0.0819708) , 
3, 0.687732, 1, 0, 0.498217,-0.00857173)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456357,-0.00759686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600934,0.0195261) , 
5, 0.80218, 1, 0, 0.474122,-0.0167959) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.816286,0.0424525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645179,0.00341682) , 
4, 2.47618, 1, 0, 0.754659,0.106889) , 
0, 0.490966, 1, 0, 0.501204,-0.00485584)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.200632,-0.043657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508378,-0.00534526) , 
5, 0.520999, 1, 0, 0.458959,-0.0472699) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753966,0.0303828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358597,-0.00751413) , 
6, 0.0430726, 1, 0, 0.517392,0.0248604) , 
2, 0.595378, 1, 0, 0.478394,-0.0232791)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583306,-0.0156749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525459,0.0094431) , 
3, 0.35148, 1, 0, 0.533821,0.0240171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545472,0.00102106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190584,-0.0441173) , 
1, 0.0234765, 1, 0, 0.376098,-0.0893942) , 
5, 0.823648, 1, 0, 0.514773,0.0103204)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598263,-0.00821189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173225,-0.0570609) , 
1, 0.199468, 1, 0, 0.550357,-0.0552254) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466694,0.00766722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322123,-0.036839) , 
7, 0.79256, 1, 0, 0.452368,0.0129775) , 
6, 0.0338707, 1, 0, 0.492811,-0.0151716)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467016,0.00727011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551084,-0.0124324) , 
7, 0.648224, 1, 0, 0.502804,-0.00293367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73565,0.0627199) , 
5, 0.872674, 1, 0, 0.510626,0.0070927)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742365,0.0230032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424354,-0.008555) , 
6, 0.0122762, 1, 0, 0.468052,-0.0183152) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47538,0.00170675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.763032,0.032616) , 
7, 0.549626, 1, 0, 0.593557,0.0576663) , 
5, 0.655288, 1, 0, 0.516937,0.0112801)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.789681,0.0383481) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507355,-0.0339038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470215,-0.00310218) , 
6, 0.00612963, 1, 0, 0.473362,-0.0230681) , 
3, 0.303492, 1, 0, 0.48918,-0.0148229)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681528,0.00761018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485753,-0.032215) , 
3, 0.296561, 1, 0, 0.531096,-0.0894099) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515388,-0.00607491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500782,0.0144118) , 
6, 0.033843, 1, 0, 0.506795,0.0254554) , 
3, 0.389644, 1, 0, 0.511925,0.00120898)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401078,-0.0440345) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.108087,-0.0423509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554421,0.00722656) , 
5, 0.393849, 1, 0, 0.531552,0.0201888) , 
3, 0.268414, 1, 0, 0.527047,0.0129458)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554487,0.00535241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339571,-0.0160788) , 
3, 0.763731, 1, 0, 0.499284,-0.00148034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433526,-0.0378672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540669,-0.00326505) , 
7, 0.818676, 1, 0, 0.471082,-0.0995708) , 
7, 0.770671, 1, 0, 0.494828,-0.016979)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469062,-0.00523615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491168,-0.0345361) , 
7, 0.723569, 1, 0, 0.473005,-0.0419027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25897,-0.012316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715932,0.0294126) , 
0, 0.39489, 1, 0, 0.546848,0.0548947) , 
4, 2.16041, 1, 0, 0.480806,-0.0316771)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468186,-0.00214182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710236,0.017836) , 
7, 0.626218, 1, 0, 0.572248,0.0241178) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193376,-0.0561639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331927,0.00263526) , 
6, 0.102569, 1, 0, 0.298249,-0.0539285) , 
6, 0.0949963, 1, 0, 0.516356,0.00819741)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499619,0.00346618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223511,-0.025559) , 
3, 0.861649, 1, 0, 0.453935,-0.00516922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440188,-0.0704418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535022,-0.0113654) , 
6, 0.0122364, 1, 0, 0.509218,-0.102965) , 
0, 0.418049, 1, 0, 0.467667,-0.0294605)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.790348,0.0283494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499426,0.000650083) , 
3, 0.594822, 1, 0, 0.672434,0.0617797) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409141,-0.0220043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416761,0.004823) , 
6, 0.0500715, 1, 0, 0.414685,-0.0111807) , 
6, 0.0369496, 1, 0, 0.513452,0.0167771)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427543,-0.0158304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308259,0.00388725) , 
6, 0.0583048, 1, 0, 0.394425,-0.0416208) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614007,0.0103958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263495,-0.016912) , 
6, 0.141636, 1, 0, 0.569065,0.0289752) , 
5, 0.557755, 1, 0, 0.510173,0.00516904)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559664,-0.00305579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326479,-0.0356284) , 
6, 0.0413532, 1, 0, 0.513572,-0.039399) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426531,0.00366596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.679626,0.0479979) , 
0, 0.455898, 1, 0, 0.446599,0.0311392) , 
6, 0.0523447, 1, 0, 0.486816,-0.0112179)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437098,0.012991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548852,-0.0107905) , 
0, 0.478153, 1, 0, 0.468252,0.0249733) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460954,0.00784571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501592,-0.0219706) , 
7, 0.491757, 1, 0, 0.490083,-0.0541112) , 
5, 0.582677, 1, 0, 0.482453,-0.0264722)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533359,-0.00626828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367472,0.0123186) , 
1, 0.0745276, 1, 0, 0.49625,-0.00987637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175667,-0.0582055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.657576,-0.00676118) , 
7, 0.683771, 1, 0, 0.439046,-0.134498) , 
0, 0.49098, 1, 0, 0.488744,-0.0262286)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297538,-0.0419069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582715,0.00204916) , 
4, 0.621657, 1, 0, 0.535073,-0.0231587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7945,0.0682281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380171,0.00151367) , 
3, 0.701498, 1, 0, 0.434061,0.0448372) , 
3, 0.664182, 1, 0, 0.499125,0.00103971)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433069,0.0135672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515988,-0.0111467) , 
7, 0.455217, 1, 0, 0.496312,-0.0225568) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757737,0.0393622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274733,-0.0123103) , 
1, 0.246476, 1, 0, 0.6153,0.0938404) , 
4, 2.07796, 1, 0, 0.509262,-0.00988894)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477506,-0.0066945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704176,0.0209424) , 
4, 2.11735, 1, 0, 0.495335,-0.0193217) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.165425,-0.0226966) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103036,-0.0550945) , 
7, 0.827519, 1, 0, 0.12968,-0.167289) , 
2, 1.33473, 1, 0, 0.469222,-0.0298889)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610462,0.0143669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552465,-0.0297286) , 
7, 0.7861, 1, 0, 0.605546,0.0448433) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432672,-0.00376991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445752,-0.0280923) , 
0, 0.408117, 1, 0, 0.436159,-0.0427566) , 
1, -0.00018552, 1, 0, 0.501771,-0.00882472)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311407,-0.00943077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194067,-0.0563378) , 
7, 0.608723, 1, 0, 0.259945,-0.136302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536991,-0.0142957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487957,0.00278403) , 
6, 0.0215368, 1, 0, 0.504021,-0.0106703) , 
1, -0.0249881, 1, 0, 0.474115,-0.0260639)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339496,0.0285664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468014,-0.0092658) , 
7, 0.398428, 1, 0, 0.453637,-0.0231221) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489183,-0.000215669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.770241,0.0364763) , 
4, 0.493524, 1, 0, 0.594498,0.0547336) , 
5, 0.699687, 1, 0, 0.493154,-0.00128067)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54484,-0.0170924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448433,0.021885) , 
6, 0.085584, 1, 0, 0.531033,-0.0451751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480648,0.00415164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.765377,0.0457611) , 
0, 0.335276, 1, 0, 0.508761,0.0343358) , 
3, 0.463056, 1, 0, 0.51665,0.00617188)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482512,0.0459015) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670216,0.0141141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435786,-0.00722986) , 
6, 0.0306219, 1, 0, 0.519294,-0.000858084) , 
2, 0.122309, 1, 0, 0.517303,0.00907527)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599282,0.00439256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398263,-0.016479) , 
3, 0.605076, 1, 0, 0.524356,-0.0157071) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587943,0.0442963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329452,0.00182134) , 
3, 0.884504, 1, 0, 0.441434,0.0871115) , 
3, 0.820087, 1, 0, 0.512959,-0.00157531)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388515,-0.00839733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574911,0.0100255) , 
5, 0.551377, 1, 0, 0.501698,0.0116703) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454382,-0.00893051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437884,-0.0420129) , 
2, 0.347137, 1, 0, 0.449905,-0.0764219) , 
5, 0.728787, 1, 0, 0.487992,-0.0116413)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431784,-0.000587364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742893,0.0288433) , 
0, 0.285746, 1, 0, 0.484145,0.016403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.835212,0.0372614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442996,-0.0278848) , 
6, 0.00914114, 1, 0, 0.485552,-0.0876793) , 
0, 0.350693, 1, 0, 0.484712,-0.0255776)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429449,-0.0134879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377622,0.0133395) , 
6, 0.100578, 1, 0, 0.42096,-0.0396009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833139,0.0387424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567903,0.000164679) , 
3, 0.329727, 1, 0, 0.616811,0.0266231) , 
7, 0.662331, 1, 0, 0.485135,-0.0179011)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485194,-0.0251633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48379,0.000149332) , 
6, 0.0153117, 1, 0, 0.48408,-0.0197684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280145,-0.0385701) , 
5, 0.883865, 1, 0, 0.471092,-0.0292443)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661331,0.014781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46283,-0.00299657) , 
3, 0.492124, 1, 0, 0.535404,0.013474) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.204923,-0.0285459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30194,0.0094262) , 
1, 0.296196, 1, 0, 0.229604,-0.0776239) , 
6, 0.12932, 1, 0, 0.497348,0.002137)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730245,0.0223821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426429,-0.00992114) , 
6, 0.0523497, 1, 0, 0.609939,0.0352138) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314098,-0.0226109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360361,0.00924456) , 
6, 0.0523018, 1, 0, 0.336569,-0.03161) , 
1, 0.0249971, 1, 0, 0.510743,0.0109658)    );
   return;
};

// Clean up
inline void ReadBDT-0.3_fold2::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.3_fold2::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
