// Class: ReadBDT-0.3_fold7
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.3_fold7
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/00       [401408]
Creator        : htan
Date           : Fri Aug 16 14:19:05 2024
Host           : Linux 6772f6b99311 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May 9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gluster/home/htan/ZTTBDT
Training events: 89003
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
m_pT_asymm                    m_pT_asymm                    m_pT_asymm                    m_pT_asymm                                                      'F'    [1.16390037874e-05,0.946852445602]
m_sigmaCosDelPhi              m_sigmaCosDelPhi              m_sigmaCosDelPhi              m_sigmaCosDelPhi                                                'F'    [-0.049986757338,1.9745773077]
m_ratioMetTauPT               m_ratioMetTauPT               m_ratioMetTauPT               m_ratioMetTauPT                                                 'F'    [0.00113642180804,11.9963302612]
m_ratioMuonTauPT              m_ratioMuonTauPT              m_ratioMuonTauPT              m_ratioMuonTauPT                                                'F'    [0.0272991936654,0.999976694584]
m_ratioMetMuonPT              m_ratioMetMuonPT              m_ratioMetMuonPT              m_ratioMetMuonPT                                                'F'    [0.00152266630903,24.9829425812]
m_ratioMuonTauM3              m_ratioMuonTauM3              m_ratioMuonTauM3              m_ratioMuonTauM3                                                'F'    [0.00183517555706,0.996654033661]
m_ratioMuonMetM3              m_ratioMuonMetM3              m_ratioMuonMetM3              m_ratioMuonMetM3                                                'F'    [1.27644239001e-06,0.249402225018]
m_ratioMetTauM3               m_ratioMetTauM3               m_ratioMetTauM3               m_ratioMetTauM3                                                 'F'    [5.56223167223e-05,0.977119266987]
NSpec 1
m_event_number                m_event_number                m_event_number                I                                                               'F'    [113,1214786176]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.3_fold7Node

#ifndef BDT-0.3_fold7Node__def
#define BDT-0.3_fold7Node__def

class BDT-0.3_fold7Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.3_fold7Node ( BDT-0.3_fold7Node* left,BDT-0.3_fold7Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.3_fold7Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold7Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold7Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.3_fold7Node*   fLeft;     // pointer to the left daughter node
   BDT-0.3_fold7Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.3_fold7Node::~BDT-0.3_fold7Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.3_fold7Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.3_fold7Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.3_fold7 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.3_fold7( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.3_fold7" ),
        fNvars( 8 )
   {
      // the training input variables
      const char* inputVars[] = { "m_pT_asymm", "m_sigmaCosDelPhi", "m_ratioMetTauPT", "m_ratioMuonTauPT", "m_ratioMetMuonPT", "m_ratioMuonTauM3", "m_ratioMuonMetM3", "m_ratioMetTauM3" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.3_fold7() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.3_fold7Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.3_fold7::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.3_fold7Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.3_fold7Node*)current->GetRight();
         else current=(BDT-0.3_fold7Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.3_fold7::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44319,-0.011362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.735358,0.0470717) , 
7, 0.567561, 1, 0, 0.620931,0.120931) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274149,-0.0451701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48095,-0.00380998) , 
5, 0.700011, 1, 0, 0.339674,-0.160326) , 
6, 0.064431, 1, 0, 0.51474,0.0147402)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173179,-0.0640376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392108,-0.0199313) , 
7, 0.224338, 1, 0, 0.352486,-0.139508) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687428,0.0357937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412258,-0.0192533) , 
2, 0.758871, 1, 0, 0.608261,0.099634) , 
7, 0.504449, 1, 0, 0.519405,0.0165566)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699133,0.0369723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23836,-0.0542253) , 
1, 0.105414, 1, 0, 0.632913,0.118871) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278754,-0.0450328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487639,-0.00278573) , 
5, 0.554512, 1, 0, 0.419346,-0.0827194) , 
6, 0.024514, 1, 0, 0.480845,-0.0246686)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720347,0.0392486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480528,-0.00372567) , 
3, 0.550334, 1, 0, 0.591594,0.0803109) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432963,-0.0127651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232594,-0.0514298) , 
3, 0.580197, 1, 0, 0.329903,-0.162639) , 
1, 0.0243195, 1, 0, 0.488703,-0.0152114)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725216,0.0362827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434429,-0.0131569) , 
3, 0.527258, 1, 0, 0.55196,0.0333329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26767,-0.0414834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452991,-0.00431594) , 
5, 0.69742, 1, 0, 0.312817,-0.160829) , 
1, 0.0499917, 1, 0, 0.485361,-0.0207395)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688413,0.0312046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336293,-0.0259957) , 
1, 0.0250092, 1, 0, 0.559606,0.0507237) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155777,-0.0619728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352486,-0.0246818) , 
7, 0.328176, 1, 0, 0.277211,-0.193402) , 
3, 0.755024, 1, 0, 0.487303,-0.0117815)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.159691,-0.0587911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286317,-0.0269872) , 
6, 0.0784618, 1, 0, 0.200902,-0.237682) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644519,0.02208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380226,-0.0185583) , 
6, 0.0615421, 1, 0, 0.549662,0.0366019) , 
7, 0.313816, 1, 0, 0.506528,0.00267941)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388226,-0.023824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743951,0.0393432) , 
5, 0.504775, 1, 0, 0.632647,0.0946115) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467241,-0.00102256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238634,-0.0469446) , 
4, 0.875947, 1, 0, 0.405021,-0.0664841) , 
3, 0.557164, 1, 0, 0.50985,0.00770516)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.28296,-0.0409193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667764,0.0259371) , 
0, 0.433793, 1, 0, 0.397331,-0.102704) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21332,-0.0451261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583539,0.0150501) , 
0, 0.0467859, 1, 0, 0.549995,0.0469695) , 
5, 0.580974, 1, 0, 0.491807,-0.0100782)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773801,0.0387966) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502036,-0.00271523) , 
6, 0.039737, 1, 0, 0.647406,0.0927939) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.324386,-0.0287106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655776,0.0367796) , 
5, 0.764471, 1, 0, 0.402712,-0.0645509) , 
3, 0.556248, 1, 0, 0.510354,0.00466579)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21148,-0.0512771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580466,0.00625353) , 
0, 0.445728, 1, 0, 0.303073,-0.178974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421758,-0.00949877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.709441,0.0279158) , 
0, 0.249175, 1, 0, 0.556537,0.0375226) , 
5, 0.533372, 1, 0, 0.483244,-0.0250811)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.736286,0.0316431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354834,-0.0262487) , 
1, 0.0252611, 1, 0, 0.630069,0.0715959) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477301,-0.00558289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294796,-0.0299849) , 
3, 0.696455, 1, 0, 0.409563,-0.0709701) , 
6, 0.0276139, 1, 0, 0.476072,-0.0279694)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382439,-0.00964283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286999,-0.041113) , 
7, 0.489231, 1, 0, 0.353862,-0.0931884) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722506,0.0286402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451487,-0.00629496) , 
6, 0.0458829, 1, 0, 0.596001,0.057534) , 
7, 0.542869, 1, 0, 0.487763,-0.00983991)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298573,-0.0341766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535082,0.00973415) , 
7, 0.796182, 1, 0, 0.340293,-0.125635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.783035,0.0396221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510995,0.00722743) , 
3, 0.483617, 1, 0, 0.58412,0.075086) , 
5, 0.517667, 1, 0, 0.522406,0.0242822)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408338,-0.0206433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619713,0.0169282) , 
1, -0.0136642, 1, 0, 0.563263,0.0316442) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233608,-0.0418535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357222,-0.00919088) , 
6, 0.0646273, 1, 0, 0.292822,-0.125883) , 
1, 0.123116, 1, 0, 0.513626,0.00273165)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219554,-0.0361727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519618,-0.00185906) , 
7, 0.408296, 1, 0, 0.470927,-0.0347646) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.781051,0.0574426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311629,-0.0233431) , 
1, 0.0711595, 1, 0, 0.653983,0.175775) , 
5, 0.789396, 1, 0, 0.49239,-0.0100797)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7912,0.0355108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52088,9.25329e-05) , 
6, 0.0243678, 1, 0, 0.607276,0.0510215) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474309,0.00103185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245251,-0.0306931) , 
3, 0.579661, 1, 0, 0.353129,-0.0732051) , 
1, 0.0243839, 1, 0, 0.513807,0.00533394)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.123462,-0.0584078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34687,-0.0170173) , 
5, 0.46854, 1, 0, 0.304101,-0.116325) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676823,0.0264841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491997,-0.00965601) , 
2, 0.425215, 1, 0, 0.528189,-0.0111804) , 
7, 0.470494, 1, 0, 0.46342,-0.0415707)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30654,-0.0528867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318988,-0.0174227) , 
3, 0.339752, 1, 0, 0.314968,-0.134896) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652174,0.0172888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384428,-0.0115922) , 
1, 0.0236275, 1, 0, 0.563502,0.0353415) , 
5, 0.505385, 1, 0, 0.50888,-0.00207236)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667609,0.0188564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.86792,0.0601154) , 
2, 0.583481, 1, 0, 0.782438,0.196121) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489269,-0.00386792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196996,-0.0468825) , 
6, 0.150141, 1, 0, 0.464106,-0.0358337) , 
3, 0.327508, 1, 0, 0.485889,-0.0199615)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874852,0.0515509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494561,0.00681984) , 
1, 0.00889625, 1, 0, 0.734803,0.154236) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418415,-0.0169507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523721,0.00812275) , 
5, 0.691863, 1, 0, 0.452236,-0.0408907) , 
6, 0.0092055, 1, 0, 0.479473,-0.0220822)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656982,0.0180456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293015,-0.0271574) , 
3, 0.336189, 1, 0, 0.354452,-0.0899758) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403373,-0.00925591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682585,0.0225611) , 
0, 0.175353, 1, 0, 0.572854,0.0457283) , 
5, 0.533974, 1, 0, 0.512354,0.00813693)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321976,-0.0491315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.208904,-0.0347329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552759,0.00583229) , 
7, 0.276219, 1, 0, 0.525425,0.0122503) , 
3, 0.24345, 1, 0, 0.517706,0.00284786)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400274,-0.011727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144568,-0.0775087) , 
0, 0.501994, 1, 0, 0.386869,-0.0713587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730572,0.0250713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323137,-0.019273) , 
2, 0.886254, 1, 0, 0.625127,0.0598841) , 
7, 0.627306, 1, 0, 0.488097,-0.0155977)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.856847,0.055228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5137,-0.000938941) , 
3, 0.291474, 1, 0, 0.527684,0.00601373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.156682,-0.0540097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28453,-0.0161179) , 
1, 0.0738341, 1, 0, 0.216705,-0.170347) , 
6, 0.131756, 1, 0, 0.487966,-0.016511)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.172143,-0.0433452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295187,-0.00669081) , 
6, 0.0935407, 1, 0, 0.216387,-0.136567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540121,0.00264499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67757,0.0296151) , 
5, 0.705898, 1, 0, 0.576392,0.0461002) , 
7, 0.313681, 1, 0, 0.531011,0.0230739)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669439,0.0250242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.910909,0.0584944) , 
4, 0.815611, 1, 0, 0.823524,0.192361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53235,0.0113592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466175,-0.01221) , 
2, 0.47428, 1, 0, 0.493919,-0.0105186) , 
6, 0.00923078, 1, 0, 0.528388,0.010698)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448034,-0.00874982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617614,0.00840422) , 
7, 0.683822, 1, 0, 0.506774,-0.0136502) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.853291,0.0540717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520454,0.00578237) , 
3, 0.737541, 1, 0, 0.645214,0.110457) , 
5, 0.774704, 1, 0, 0.527075,0.00454853)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407793,-0.00213395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256173,-0.0571551) , 
7, 0.621579, 1, 0, 0.334765,-0.139214) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379164,-0.0143568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.599513,0.00765507) , 
0, 0.233824, 1, 0, 0.504219,-0.00980563) , 
1, -0.0249921, 1, 0, 0.485618,-0.0240105)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478915,0.00351698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199879,-0.054117) , 
1, -0.0353356, 1, 0, 0.316188,-0.142117) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58557,0.00950324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311174,-0.0159183) , 
1, 0.096719, 1, 0, 0.515589,0.0137599) , 
1, -0.0252713, 1, 0, 0.489535,-0.00660751)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38676,-0.0129685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185549,-0.0432677) , 
3, 0.895106, 1, 0, 0.352191,-0.0839686) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.844509,0.0672171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583907,0.00426352) , 
7, 0.574798, 1, 0, 0.598202,0.0346486) , 
7, 0.553992, 1, 0, 0.489645,-0.0176933)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.84647,0.0408728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545332,0.00337899) , 
6, 0.0210775, 1, 0, 0.624918,0.0552754) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313202,-0.0185535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484878,0.0202883) , 
4, 1.85457, 1, 0, 0.340299,-0.05566) , 
1, 0.0247092, 1, 0, 0.520249,0.0144788)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645889,0.0105027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283459,-0.0251623) , 
3, 0.400291, 1, 0, 0.387906,-0.0658361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399349,-0.00677691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723231,0.0257174) , 
0, 0.175376, 1, 0, 0.586607,0.0522317) , 
5, 0.557755, 1, 0, 0.520939,0.0132115)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290392,-0.026874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523486,0.00196568) , 
1, -0.0250841, 1, 0, 0.491123,-0.00949034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730908,0.0329557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365459,-0.0108832) , 
1, 0.0223102, 1, 0, 0.596319,0.0763678) , 
5, 0.691863, 1, 0, 0.523089,0.0165995)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315898,-0.0202666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654776,0.0116018) , 
7, 0.503116, 1, 0, 0.540698,0.00328758) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298103,-0.0293921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411715,0.0198957) , 
1, 0.296199, 1, 0, 0.31434,-0.105856) , 
6, 0.073635, 1, 0, 0.468814,-0.0313728)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316555,-0.0286769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533128,0.00127114) , 
2, 0.403792, 1, 0, 0.478331,-0.0287132) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722477,0.0356447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203896,-0.035428) , 
1, 0.0947196, 1, 0, 0.605622,0.0898109) , 
5, 0.761361, 1, 0, 0.499433,-0.00906431)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6653,0.0067397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794824,0.0433618) , 
3, 0.357259, 1, 0, 0.715591,0.0892836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387363,0.00709456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448326,-0.016475) , 
7, 0.476895, 1, 0, 0.428376,-0.0402926) , 
3, 0.425531, 1, 0, 0.49182,-0.0116704)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494361,-0.0148368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.849072,0.0431606) , 
5, 0.601992, 1, 0, 0.61029,0.0141921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387724,-0.00550562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299827,-0.0348523) , 
0, 0.207269, 1, 0, 0.357889,-0.0707265) , 
3, 0.568358, 1, 0, 0.475193,-0.0312603)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326954,-0.0251698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674199,0.0215162) , 
1, -0.0206866, 1, 0, 0.59531,0.0462923) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23656,-0.0432875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364275,0.00568768) , 
6, 0.0428799, 1, 0, 0.312638,-0.0648308) , 
1, 0.0749901, 1, 0, 0.520676,0.0169525)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511646,0.00721222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.873261,0.05285) , 
0, 0.340715, 1, 0, 0.620088,0.0888659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380329,-0.0435405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45366,-0.0062481) , 
3, 0.351525, 1, 0, 0.44235,-0.0526703) , 
1, -0.000521349, 1, 0, 0.505445,-0.00242605)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0916357,-0.0551821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398465,-0.00745021) , 
4, 1.24704, 1, 0, 0.281051,-0.105357) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.820156,0.039886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503276,0.00281596) , 
6, 0.0214778, 1, 0, 0.577848,0.0457907) , 
5, 0.483385, 1, 0, 0.531974,0.0224288)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319825,-0.0216736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62991,0.010007) , 
7, 0.459093, 1, 0, 0.553488,0.00770268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388373,0.0233508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244215,-0.0371162) , 
7, 0.396198, 1, 0, 0.276859,-0.110361) , 
6, 0.0922965, 1, 0, 0.491514,-0.0187471)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211356,-0.0190927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156953,-0.0404984) , 
7, 0.222381, 1, 0, 0.173619,-0.139991) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608692,0.0490079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519239,-0.00568983) , 
7, 0.374911, 1, 0, 0.522642,-0.0154313) , 
7, 0.300241, 1, 0, 0.484127,-0.0291765)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.868779,0.0501555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432126,-0.0123227) , 
6, 0.0091937, 1, 0, 0.465306,-0.0353168) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698075,0.0632834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595983,0.00883735) , 
7, 0.666144, 1, 0, 0.610975,0.0716914) , 
4, 1.54605, 1, 0, 0.499144,-0.0104595)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424277,-0.0522706) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518299,-0.00037528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207445,-0.0386822) , 
3, 0.936719, 1, 0, 0.500242,-0.0115012) , 
3, 0.268414, 1, 0, 0.497221,-0.019874)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333955,-0.0329769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.658262,0.00428302) , 
2, 0.335927, 1, 0, 0.564617,-0.0313353) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265915,-0.0081086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529815,0.0163769) , 
5, 0.552726, 1, 0, 0.450699,0.0430229) , 
6, 0.0459625, 1, 0, 0.514004,0.00170185)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569395,-0.0143247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36669,-0.0386796) , 
6, 0.0211355, 1, 0, 0.521676,-0.0850704) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213098,-0.0309217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493075,0.00439926) , 
5, 0.471732, 1, 0, 0.458534,0.00187639) , 
6, 0.027615, 1, 0, 0.479439,-0.026911)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374545,-0.0189563) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624625,0.00642125) , 
7, 0.699681, 1, 0, 0.467154,-0.0426196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374334,-0.0132334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.768235,0.0399371) , 
4, 0.441331, 1, 0, 0.54585,0.041076) , 
5, 0.689611, 1, 0, 0.4896,-0.0187473)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226421,-0.0406305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410091,-0.0110679) , 
6, 0.0756423, 1, 0, 0.293654,-0.132275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468214,-0.00865811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593474,0.0149628) , 
5, 0.628203, 1, 0, 0.530911,0.0141116) , 
1, -0.0249921, 1, 0, 0.496835,-0.00691329)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619242,0.00797493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318838,-0.0188741) , 
3, 0.556415, 1, 0, 0.473993,-0.0219959) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494007,0.0119659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.878,0.0643215) , 
4, 0.274287, 1, 0, 0.646809,0.146012) , 
5, 0.787865, 1, 0, 0.497116,0.000484257)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535263,0.00243734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.687045,0.034092) , 
5, 0.801588, 1, 0, 0.553236,0.0271054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165255,-0.0446616) , 
6, 0.190744, 1, 0, 0.538174,0.0182934)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189188,-0.0420164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529281,0.000871815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.821933,0.0694739) , 
5, 0.858207, 1, 0, 0.540097,0.0159641) , 
0, 0.046788, 1, 0, 0.509562,-0.00162966)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33699,-0.00548708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251879,-0.0466446) , 
7, 0.451827, 1, 0, 0.310761,-0.0804743) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461273,-0.0152909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666412,0.0128004) , 
5, 0.587836, 1, 0, 0.571429,-0.00204365) , 
7, 0.494619, 1, 0, 0.478598,-0.029975)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534979,0.0138493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439109,-0.0165853) , 
5, 0.822416, 1, 0, 0.520591,0.0368691) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745993,0.014065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38212,-0.0293223) , 
6, 0.0397653, 1, 0, 0.560897,-0.0415833) , 
0, 0.396458, 1, 0, 0.532468,0.013751)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391654,-0.0306404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549384,0.0113088) , 
3, 0.332023, 1, 0, 0.540234,0.0370946) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65059,0.00698543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329883,-0.0348967) , 
6, 0.0393795, 1, 0, 0.467973,-0.0766539) , 
7, 0.748019, 1, 0, 0.525437,0.0138032)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444622,-0.0152841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390865,0.0197104) , 
1, 0.346562, 1, 0, 0.441259,-0.0562727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.928291,0.0730578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491281,-0.00648575) , 
5, 0.831685, 1, 0, 0.628902,0.072534) , 
5, 0.787865, 1, 0, 0.46484,-0.0400854)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568396,-0.0122883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549652,0.0183732) , 
6, 0.02674, 1, 0, 0.556419,0.0324801) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255903,-0.00995183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204387,-0.0441018) , 
5, 0.661061, 1, 0, 0.221604,-0.148789) , 
6, 0.135367, 1, 0, 0.516421,0.0108251)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305646,-0.0730964) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340582,-0.0155135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556305,0.000691497) , 
0, 0.185132, 1, 0, 0.479722,-0.0218224) , 
3, 0.268424, 1, 0, 0.470586,-0.0373374)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548037,0.0025414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265968,-0.0250413) , 
6, 0.128374, 1, 0, 0.519229,-0.00166933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495028,0.0485238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423379,0.0196619) , 
1, 0.424016, 1, 0, 0.448693,0.118752) , 
1, 0.299938, 1, 0, 0.513243,0.00855074)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3555,-0.0145038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637826,0.0219371) , 
2, 0.228239, 1, 0, 0.553777,0.0456749) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419105,-0.0245073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480007,0.00144914) , 
1, -0.000416792, 1, 0, 0.453518,-0.0419327) , 
2, 0.556121, 1, 0, 0.50785,0.00554332)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372976,-0.0528635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697724,0.0243134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433646,-0.00099203) , 
6, 0.0395412, 1, 0, 0.546435,0.0394685) , 
6, 0.00307778, 1, 0, 0.534736,0.0222166)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356782,-0.0298484) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680905,0.0182007) , 
2, 0.36707, 1, 0, 0.632852,0.0442222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391513,0.00936916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37028,-0.027955) , 
7, 0.482685, 1, 0, 0.379272,-0.0536982) , 
3, 0.556226, 1, 0, 0.492804,-0.00985773)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574856,0.00701018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302174,-0.0167887) , 
6, 0.0861435, 1, 0, 0.502134,0.00203415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6463,0.0131651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274775,-0.0754426) , 
5, 0.569452, 1, 0, 0.478086,-0.124918) , 
0, 0.499321, 1, 0, 0.499142,-0.0137581)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408558,-0.0317827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612433,0.00324148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366419,-0.0118469) , 
3, 0.557446, 1, 0, 0.478018,-0.021623) , 
3, 0.268424, 1, 0, 0.475065,-0.0267671)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623732,0.00520008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45838,-0.0349896) , 
5, 0.665799, 1, 0, 0.561403,-0.0430361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54407,0.0171253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250705,-0.019816) , 
6, 0.15946, 1, 0, 0.508424,0.0548762) , 
6, 0.0306216, 1, 0, 0.529115,0.0166358)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610787,0.00848635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689037,0.0625121) , 
1, 0.0720695, 1, 0, 0.614658,0.046728) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270816,-0.0196263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342712,0.00648383) , 
6, 0.0615313, 1, 0, 0.308112,-0.0260915) , 
1, 0.123494, 1, 0, 0.548925,0.0311133)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68138,0.0219852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486086,-0.0297046) , 
3, 0.296973, 1, 0, 0.511469,-0.0932031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521009,0.0074017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193907,-0.0289894) , 
3, 0.934799, 1, 0, 0.492394,0.0188015) , 
3, 0.472281, 1, 0, 0.499201,-0.0211696)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558018,0.0194896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482986,-0.0116758) , 
5, 0.731532, 1, 0, 0.524056,0.019349) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511769,-0.023948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384344,0.00686369) , 
6, 0.0583041, 1, 0, 0.473207,-0.0586872) , 
2, 0.53587, 1, 0, 0.500916,-0.0161635)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447112,-0.0164181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.853294,0.0474427) , 
7, 0.651498, 1, 0, 0.744208,0.120148) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436774,-0.0100902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390828,-0.0358422) , 
7, 0.715152, 1, 0, 0.428791,-0.0619049) , 
3, 0.391649, 1, 0, 0.475068,-0.0351944)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.221438,-0.0627751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431883,-0.0070858) , 
3, 0.34394, 1, 0, 0.415949,-0.0502538) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874698,0.0505889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574411,-0.00153477) , 
3, 0.339907, 1, 0, 0.646196,0.0439766) , 
7, 0.686407, 1, 0, 0.482208,-0.0231366)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192541,-0.0294668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488476,-0.0055616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.668881,0.0206166) , 
5, 0.750461, 1, 0, 0.521166,-0.00255938) , 
0, 0.0467859, 1, 0, 0.498497,-0.0104893)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493557,0.000438965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39858,-0.0247468) , 
5, 0.73686, 1, 0, 0.466612,-0.0292396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374114,-0.0510683) , 
0, 0.54942, 1, 0, 0.461991,-0.0389486)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582,0.0206324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586078,-0.0071632) , 
4, 0.62876, 1, 0, 0.584778,0.00867462) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352386,-0.00196557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269255,-0.0317595) , 
5, 0.655732, 1, 0, 0.317697,-0.0618243) , 
1, 0.0249971, 1, 0, 0.483862,-0.0179632)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6513,0.0113605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345778,-0.0115139) , 
1, 0.0242143, 1, 0, 0.538395,0.01071) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224877,-0.00791057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243918,-0.0305982) , 
5, 0.730279, 1, 0, 0.236997,-0.0955208) , 
3, 0.820467, 1, 0, 0.481915,-0.00919699)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612128,0.0109253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339608,-0.00570078) , 
1, 0.0247305, 1, 0, 0.509125,0.0191436) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363919,-0.0935015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406977,-0.00992985) , 
2, 0.715694, 1, 0, 0.393212,-0.142249) , 
7, 0.792594, 1, 0, 0.494869,-0.000706254)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112741,-0.0446068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405087,0.00244358) , 
4, 1.55482, 1, 0, 0.236449,-0.0922058) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516961,0.00171441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.657195,0.0220858) , 
4, 1.52661, 1, 0, 0.545702,0.0241699) , 
5, 0.443977, 1, 0, 0.512611,0.0117175)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605497,0.0103232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451393,-0.00783631) , 
1, 2.47884e-06, 1, 0, 0.511796,-0.00316325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.716075,0.0464029) , 
7, 0.818857, 1, 0, 0.519981,0.00461685)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56163,0.0188446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188744,-0.022707) , 
3, 0.934623, 1, 0, 0.525399,0.062971) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499588,-0.0286574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719311,0.0210957) , 
2, 0.583481, 1, 0, 0.614212,-0.0112856) , 
0, 0.359979, 1, 0, 0.557668,0.0359907)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559954,0.0274987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232536,-0.00941703) , 
1, 0.024803, 1, 0, 0.401205,0.0464076) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45847,-0.0205185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739614,0.0334412) , 
0, 0.511766, 1, 0, 0.482768,-0.0675672) , 
0, 0.16368, 1, 0, 0.461881,-0.0383795)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375318,0.00338454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693138,0.047634) , 
5, 0.488056, 1, 0, 0.498466,0.0810514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541038,0.000106609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402212,-0.0314899) , 
2, 0.623066, 1, 0, 0.508551,-0.0299986) , 
5, 0.533372, 1, 0, 0.506436,-0.00671415)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234918,-0.0503388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441172,-0.0033183) , 
3, 0.351512, 1, 0, 0.426685,-0.0285835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.853435,0.0425721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571074,0.00799782) , 
1, -0.00018552, 1, 0, 0.677734,0.0803143) , 
7, 0.69583, 1, 0, 0.484709,-0.00341462)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701326,0.0196383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502453,-0.0187716) , 
6, 0.00954637, 1, 0, 0.549919,-0.0418063) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459685,0.0211672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462068,-0.0068928) , 
7, 0.612417, 1, 0, 0.460763,0.0329134) , 
6, 0.0429543, 1, 0, 0.505984,-0.00498487)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410232,0.00780299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678726,0.0526261) , 
0, 0.139589, 1, 0, 0.453973,0.0630096) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514118,-0.00613081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441555,-0.0306127) , 
0, 0.486025, 1, 0, 0.499734,-0.0452309) , 
0, 0.161538, 1, 0, 0.489153,-0.0202045)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490955,0.000849647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424555,-0.0255776) , 
5, 0.622289, 1, 0, 0.4721,-0.0279081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37491,-0.00884492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715945,0.0248568) , 
4, 0.340578, 1, 0, 0.58477,0.0481018) , 
5, 0.680171, 1, 0, 0.511075,-0.00161453)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316696,0.00852062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223732,-0.0394372) , 
5, 0.745373, 1, 0, 0.254376,-0.106559) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524609,-7.12142e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.803894,0.0520041) , 
5, 0.834293, 1, 0, 0.536222,0.00938241) , 
0, 0.069996, 1, 0, 0.499672,-0.00565268)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255004,-0.0314808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743723,0.0239713) , 
5, 0.468508, 1, 0, 0.621927,0.0381235) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376236,-0.0306293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405579,0.00617648) , 
6, 0.0430725, 1, 0, 0.391751,-0.0495122) , 
3, 0.556229, 1, 0, 0.497251,-0.00934484)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.249812,-0.0463686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374489,-0.0142268) , 
1, -0.0350195, 1, 0, 0.301626,-0.148587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541207,0.00409512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628777,0.0508673) , 
5, 0.862546, 1, 0, 0.546305,0.028406) , 
1, -0.025247, 1, 0, 0.518425,0.00823865)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406306,-0.00239762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480349,0.0281786) , 
2, 0.335602, 1, 0, 0.430506,0.0310138) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37389,-0.03678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583287,-0.00360998) , 
7, 0.614955, 1, 0, 0.518834,-0.0598626) , 
7, 0.540249, 1, 0, 0.485453,-0.0255182)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384019,-0.0223352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521925,-0.0003905) , 
1, -0.0135775, 1, 0, 0.492371,-0.0223812) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395134,0.01849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506006,0.0435999) , 
4, 1.23767, 1, 0, 0.45272,0.126332) , 
1, 0.371324, 1, 0, 0.489941,-0.0132683)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503355,-0.00465517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445844,-0.0304744) , 
7, 0.784158, 1, 0, 0.495748,-0.0335883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465554,0.0233877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229947,-0.0146443) , 
6, 0.188518, 1, 0, 0.421197,0.0703433) , 
6, 0.101248, 1, 0, 0.483553,-0.0165869)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408226,-0.00666155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569027,0.0230665) , 
4, 0.540256, 1, 0, 0.491766,0.0358903) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649749,0.0083042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400721,-0.0357457) , 
3, 0.424295, 1, 0, 0.554918,-0.0379443) , 
0, 0.357676, 1, 0, 0.514845,0.00890735)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682866,0.0195814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21737,-0.0287281) , 
6, 0.1302, 1, 0, 0.64259,0.0607424) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405224,0.00150198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291848,-0.0479714) , 
0, 0.264449, 1, 0, 0.390024,-0.0227098) , 
3, 0.555648, 1, 0, 0.508033,0.0162824)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687562,0.0166284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366566,-0.0104866) , 
1, 0.0247167, 1, 0, 0.598229,0.0340132) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371377,-0.00191636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334763,-0.0225464) , 
7, 0.607756, 1, 0, 0.35639,-0.0465593) , 
6, 0.0646078, 1, 0, 0.51162,0.00515803)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456906,-0.0134738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430135,0.0258379) , 
1, 0.374932, 1, 0, 0.455369,-0.0463163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652797,0.039937) , 
5, 0.862953, 1, 0, 0.463455,-0.0370192)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69499,0.0144337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203092,-0.0292756) , 
1, 0.174611, 1, 0, 0.643267,0.0355021) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394419,-0.0140582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56581,0.0281965) , 
4, 2.16281, 1, 0, 0.408547,-0.0445759) , 
6, 0.0307665, 1, 0, 0.483193,-0.0191095)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454848,-0.0430526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534777,0.00180285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209341,-0.0253209) , 
6, 0.136773, 1, 0, 0.492562,-0.00678064) , 
6, 0.003078, 1, 0, 0.490424,-0.0158394)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631362,0.0586648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55202,0.00545445) , 
2, 0.120869, 1, 0, 0.555353,0.0325462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17837,-0.0237703) , 
3, 0.916932, 1, 0, 0.527123,0.0238061)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3006,-0.0353457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333803,-0.00753273) , 
6, 0.0275098, 1, 0, 0.322133,-0.0746102) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727142,0.0194573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394521,-0.0114262) , 
3, 0.554877, 1, 0, 0.608306,0.0317772) , 
7, 0.552468, 1, 0, 0.472687,-0.0186403)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295608,-0.00737188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572122,0.019195) , 
5, 0.521181, 1, 0, 0.511818,0.0574245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74684,0.0106508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381112,-0.0279092) , 
6, 0.0396043, 1, 0, 0.545647,-0.0519584) , 
7, 0.675671, 1, 0, 0.52427,0.0171625)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.218143,-0.0102602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653609,0.021608) , 
7, 0.294322, 1, 0, 0.593347,0.0711765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361801,-0.0132581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16095,-0.0674687) , 
7, 0.86346, 1, 0, 0.335138,-0.0874064) , 
2, 0.708044, 1, 0, 0.520509,0.0264421)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694375,0.0117527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883825,0.0604536) , 
6, 0.00798547, 1, 0, 0.747252,0.0893263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489726,-0.0390364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455732,-0.00455467) , 
6, 0.0180084, 1, 0, 0.458898,-0.031626) , 
6, 0.0122041, 1, 0, 0.49701,-0.0156395)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315156,-0.00891092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251719,-0.0407469) , 
5, 0.625134, 1, 0, 0.28391,-0.110637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493879,-0.00469159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580003,0.0376367) , 
5, 0.87007, 1, 0, 0.49701,-0.0122171) , 
1, -0.0252594, 1, 0, 0.472443,-0.0235633)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612092,0.0123172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357195,-0.011735) , 
3, 0.689161, 1, 0, 0.520778,0.0137591) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666761,-0.00408414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.169962,-0.0622958) , 
6, 0.0482456, 1, 0, 0.409842,-0.164336) , 
0, 0.537724, 1, 0, 0.513,0.00127282)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688426,0.017601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469243,-0.0228253) , 
5, 0.727207, 1, 0, 0.634181,0.0251231) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380483,-0.036971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406627,-0.001723) , 
6, 0.0471671, 1, 0, 0.400946,-0.0396333) , 
6, 0.0367357, 1, 0, 0.491986,-0.0143566)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520848,-0.0738414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555789,-0.00895095) , 
6, 0.00609452, 1, 0, 0.552205,-0.0549697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446031,0.0233272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486223,-0.00375413) , 
7, 0.500716, 1, 0, 0.468253,0.0330773) , 
3, 0.50826, 1, 0, 0.503796,-0.00419875)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210646,-0.0017799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667797,0.0630073) , 
5, 0.681585, 1, 0, 0.423099,0.12711) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510335,-0.00505561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681221,0.0201971) , 
7, 0.76804, 1, 0, 0.534919,-0.00669669) , 
7, 0.325743, 1, 0, 0.524194,0.00613742)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323926,-0.0245043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33418,0.00847434) , 
1, 0.0492161, 1, 0, 0.326587,-0.0711083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567892,0.000965937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.866881,0.0484291) , 
5, 0.7101, 1, 0, 0.617179,0.0336939) , 
7, 0.51623, 1, 0, 0.503523,-0.00729639)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494458,-0.0283606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48597,-0.00367427) , 
6, 0.0170231, 1, 0, 0.488183,-0.0399944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512372,0.0572797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353573,0.020576) , 
6, 0.177839, 1, 0, 0.433904,0.149606) , 
6, 0.153205, 1, 0, 0.484908,-0.0285562)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522784,-0.0305393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555232,0.00461064) , 
6, 0.00454567, 1, 0, 0.551969,0.00491438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288145,-0.0352136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358641,0.00635561) , 
6, 0.101708, 1, 0, 0.325666,-0.0595003) , 
6, 0.0736352, 1, 0, 0.485202,-0.0140901)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563039,0.0496372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180191,-0.0137159) , 
1, 0.0977804, 1, 0, 0.424179,0.11216) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51474,-0.00291429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362219,-0.039791) , 
5, 0.821451, 1, 0, 0.502129,-0.0261757) , 
7, 0.350107, 1, 0, 0.494353,-0.0123759)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364445,0.01791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43137,-0.0133922) , 
7, 0.357716, 1, 0, 0.421319,-0.0378985) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749857,0.0252843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500189,-0.0183833) , 
0, 0.555828, 1, 0, 0.691297,0.058148) , 
0, 0.41977, 1, 0, 0.470988,-0.0202283)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455994,-0.00576158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458314,-0.0426806) , 
7, 0.735194, 1, 0, 0.45632,-0.0436175) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794802,0.0461348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25574,-0.0232985) , 
1, 0.222028, 1, 0, 0.622688,0.086897) , 
4, 2.13457, 1, 0, 0.471376,-0.0318067)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573735,-0.00106339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676672,0.0424071) , 
6, 0.0534399, 1, 0, 0.584924,0.0154728) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270313,-0.0337847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415068,0.0217871) , 
1, 0.0243744, 1, 0, 0.321466,-0.066567) , 
6, 0.0646078, 1, 0, 0.481903,-0.0166073)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436878,-0.00452445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27183,-0.0544872) , 
5, 0.575327, 1, 0, 0.408866,-0.0536659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3847,-0.00658069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733851,0.0249084) , 
0, 0.163663, 1, 0, 0.573097,0.0400801) , 
5, 0.589855, 1, 0, 0.50564,0.00157414)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568145,0.00565409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271793,-0.0197291) , 
6, 0.0861441, 1, 0, 0.486691,-0.00602615) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.273016,-0.0580845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64571,0.0013946) , 
2, 0.583481, 1, 0, 0.466806,-0.125623) , 
0, 0.499321, 1, 0, 0.484544,-0.0189375)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465328,-0.0210018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.785891,0.0257746) , 
5, 0.647903, 1, 0, 0.512296,-0.0605102) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409501,0.0268935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482712,-0.00367294) , 
5, 0.626249, 1, 0, 0.461282,0.0177639) , 
3, 0.507616, 1, 0, 0.483819,-0.0168164)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701393,0.00567087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3593,-0.0252863) , 
3, 0.673776, 1, 0, 0.597656,-0.0198657) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77589,0.0412333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478469,0.00934979) , 
6, 0.0298508, 1, 0, 0.511763,0.0529215) , 
6, 0.0214513, 1, 0, 0.534291,0.0338309)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432768,-0.0132346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393559,0.0131506) , 
6, 0.0980516, 1, 0, 0.426351,-0.0371679) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228269,-0.0193235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747329,0.0217768) , 
0, 0.278159, 1, 0, 0.661037,0.055037) , 
7, 0.710482, 1, 0, 0.479405,-0.0163235)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539232,0.0377473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556894,0.00457593) , 
0, 0.113201, 1, 0, 0.554271,0.0398605) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684726,0.00129429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215792,-0.0575466) , 
6, 0.0397812, 1, 0, 0.426463,-0.140698) , 
7, 0.796182, 1, 0, 0.539394,0.0188439)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425163,-0.00445078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.791885,0.0286338) , 
1, -0.0112534, 1, 0, 0.595044,0.0386589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769099,0.0439922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421199,-0.0143912) , 
6, 0.00306935, 1, 0, 0.441706,-0.0454634) , 
1, -0.00018552, 1, 0, 0.500966,-0.0129527)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185395,-0.0324413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537424,0.0096989) , 
2, 0.484834, 1, 0, 0.431048,-0.0131526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6757,0.0232594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270094,-0.0181434) , 
6, 0.135367, 1, 0, 0.607187,0.0646635) , 
5, 0.59433, 1, 0, 0.528844,0.0300523)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489362,0.000876673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493921,0.0466562) , 
6, 0.150141, 1, 0, 0.489585,0.0123843) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701819,-0.00033653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340953,-0.0367699) , 
6, 0.0397356, 1, 0, 0.510262,-0.0876933) , 
0, 0.384798, 1, 0, 0.496241,-0.0198306)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474122,-0.0327779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435855,-0.00937669) , 
6, 0.0153201, 1, 0, 0.444187,-0.0579064) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.856117,0.0458596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511705,-0.00540835) , 
6, 0.0244068, 1, 0, 0.578433,0.0137929) , 
5, 0.690111, 1, 0, 0.487252,-0.0349061)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472128,-0.0214159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.904089,0.0483452) , 
5, 0.536341, 1, 0, 0.74058,0.0663456) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477083,-0.0219739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418148,0.00252657) , 
6, 0.0533603, 1, 0, 0.451178,-0.0452145) , 
6, 0.00917781, 1, 0, 0.483179,-0.0328786)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34193,-0.0153036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400602,-0.0490423) , 
7, 0.504272, 1, 0, 0.356927,-0.104072) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542223,0.0071897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288311,-0.0431126) , 
0, 0.579446, 1, 0, 0.524703,0.0128654) , 
4, 0.620909, 1, 0, 0.465391,-0.0284739)    );
   return;
};

// Clean up
inline void ReadBDT-0.3_fold7::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.3_fold7::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
