// Class: ReadBDT-0.3_fold8
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.3_fold8
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/00       [401408]
Creator        : htan
Date           : Mon Aug 12 11:28:18 2024
Host           : Linux 6772f6b99311 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May 9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gluster/home/htan/ZTTBDT
Training events: 104961
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
m_met_pT                      m_met_pT                      m_met_pT                      m_met_pT                                                        'F'    [0.129616737366,1149.01928711]
m_mWT                         m_mWT                         m_mWT                         m_mWT                                                           'F'    [0.000240040215431,39.9999656677]
m_d_zeta                      m_d_zeta                      m_d_zeta                      m_d_zeta                                                        'F'    [-1859.73010254,1223.64221191]
m_ratioMetTauPT               m_ratioMetTauPT               m_ratioMetTauPT               m_ratioMetTauPT                                                 'F'    [0.00113642180804,11.9963302612]
m_etaSeparation               m_etaSeparation               m_etaSeparation               m_etaSeparation                                                 'F'    [-4.54272270203,4.61262607574]
m_pTSumMag                    m_pTSumMag                    m_pTSumMag                    m_pTSumMag                                                      'F'    [2.89208579063,2552.09106445]
m_pTSumPhi                    m_pTSumPhi                    m_pTSumPhi                    m_pTSumPhi                                                      'F'    [-3.14139199257,3.1415784359]
m_pTSumEta                    m_pTSumEta                    m_pTSumEta                    m_pTSumEta                                                      'F'    [-7.66828012466,7.56654691696]
NSpec 1
m_event_number                m_event_number                m_event_number                I                                                               'F'    [113,1214786176]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.3_fold8Node

#ifndef BDT-0.3_fold8Node__def
#define BDT-0.3_fold8Node__def

class BDT-0.3_fold8Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.3_fold8Node ( BDT-0.3_fold8Node* left,BDT-0.3_fold8Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.3_fold8Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold8Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold8Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.3_fold8Node*   fLeft;     // pointer to the left daughter node
   BDT-0.3_fold8Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.3_fold8Node::~BDT-0.3_fold8Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.3_fold8Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.3_fold8Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.3_fold8 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.3_fold8( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.3_fold8" ),
        fNvars( 8 )
   {
      // the training input variables
      const char* inputVars[] = { "m_met_pT", "m_mWT", "m_d_zeta", "m_ratioMetTauPT", "m_etaSeparation", "m_pTSumMag", "m_pTSumPhi", "m_pTSumEta" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.3_fold8() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.3_fold8Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.3_fold8::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.3_fold8Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.3_fold8Node*)current->GetRight();
         else current=(BDT-0.3_fold8Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.3_fold8::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425489,-0.0149021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682071,0.0364142) , 
2, -14.9511, 1, 0, 0.629429,0.129429) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425452,-0.0149096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202221,-0.0595557) , 
1, 28.8067, 1, 0, 0.373517,-0.126483) , 
1, 13.3335, 1, 0, 0.535651,0.0356506)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565683,0.0115265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230953,-0.0546329) , 
4, 1.75281, 1, 0, 0.540633,0.0328441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.125793,-0.0691667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297502,-0.0347686) , 
4, -0.69126, 1, 0, 0.228308,-0.242301) , 
1, 28.642, 1, 0, 0.512634,0.00817802)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705497,0.0373983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378782,-0.0261165) , 
4, 1.11285, 1, 0, 0.638353,0.121491) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232237,-0.0539601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483488,-0.0041893) , 
4, -1.38526, 1, 0, 0.451177,-0.0527968) , 
1, 4.44463, 1, 0, 0.502764,-0.00476215)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396928,-0.0232586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60463,0.0180024) , 
3, 0.26756, 1, 0, 0.565499,0.0510139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.156272,-0.0597513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377616,-0.0192266) , 
4, -1.04065, 1, 0, 0.320771,-0.146701) , 
1, 20.7408, 1, 0, 0.52395,0.0174469)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622044,0.0194648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332653,-0.026564) , 
1, 17.2844, 1, 0, 0.545862,0.0368113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622894,0.021749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316578,-0.0367001) , 
6, -2.13275, 1, 0, 0.352305,-0.148928) , 
4, 0.884296, 1, 0, 0.492472,-0.0144221)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274759,-0.0419512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560219,0.0143605) , 
5, 339.375, 1, 0, 0.328461,-0.155028) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670356,0.0275692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38138,-0.0195854) , 
1, 11.8502, 1, 0, 0.556853,0.0449664) , 
3, 0.269204, 1, 0, 0.504298,-0.00105397)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306941,-0.0340494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60521,0.0172547) , 
4, -1.47286, 1, 0, 0.56882,0.0545913) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291689,-0.0386151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51143,0.00898876) , 
6, 1.28044, 1, 0, 0.343029,-0.136336) , 
4, 1.10873, 1, 0, 0.521324,0.0144292)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283043,-0.0432356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610432,0.015226) , 
4, -1.65346, 1, 0, 0.584462,0.0521854) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498082,0.0173401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295532,-0.0311061) , 
7, -2.5555, 1, 0, 0.335913,-0.105886) , 
1, 17.284, 1, 0, 0.526122,0.015082)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618649,0.0151415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379513,-0.0229761) , 
4, 0.898217, 1, 0, 0.552781,0.0226801) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.231154,-0.0390317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449221,0.0061031) , 
4, 0.59495, 1, 0, 0.276177,-0.143895) , 
1, 21.2348, 1, 0, 0.504002,-0.00669563)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316754,-0.0339517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517064,0.00130137) , 
2, -11.3705, 1, 0, 0.474,-0.0306744) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.849543,0.0647643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633019,0.0210473) , 
5, 403.48, 1, 0, 0.693703,0.163683) , 
5, 349.08, 1, 0, 0.515446,0.00599033)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620225,0.0141083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30409,-0.0522835) , 
3, 0.891506, 1, 0, 0.591103,0.0391348) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239799,-0.043847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420346,-0.00942145) , 
5, 128.778, 1, 0, 0.346004,-0.115612) , 
1, 11.8523, 1, 0, 0.492426,-0.023166)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37498,-0.0204957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601645,0.0142816) , 
3, 0.355024, 1, 0, 0.518803,0.0077499) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210154,-0.0563804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348469,-0.0292695) , 
5, 121.931, 1, 0, 0.292699,-0.197145) , 
3, 0.7759, 1, 0, 0.48032,-0.0271233)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.271846,-0.0397113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557388,0.00801514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332134,-0.0289334) , 
3, 0.817162, 1, 0, 0.520235,0.00927229) , 
0, 12.443, 1, 0, 0.498568,-0.00848191)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350923,-0.0265419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556503,0.00778791) , 
4, -1.00055, 1, 0, 0.505788,-0.0028009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228155,-0.0427573) , 
4, 1.74854, 1, 0, 0.483396,-0.019326)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714762,0.0332809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551533,-0.000205047) , 
6, -0.42657, 1, 0, 0.613097,0.0605244) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439,0.00179777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299163,-0.0315264) , 
3, 0.539208, 1, 0, 0.372851,-0.0679947) , 
1, 11.8524, 1, 0, 0.516673,0.00894251)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484626,-0.00382855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.71955,0.0338041) , 
5, 340.263, 1, 0, 0.530075,0.0168074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382424,-0.0165764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193173,-0.05771) , 
6, 2.05556, 1, 0, 0.331177,-0.134916) , 
3, 0.74158, 1, 0, 0.490984,-0.0130126)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715173,0.0297674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497365,-0.00021766) , 
1, 3.95083, 1, 0, 0.547219,0.0319769) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184178,-0.0513586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306692,-0.0246044) , 
6, -0.813943, 1, 0, 0.255786,-0.171548) , 
3, 1.03977, 1, 0, 0.522865,0.0149687)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228423,-0.0461344) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417507,-0.0168992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55631,0.00583461) , 
2, -1.80029, 1, 0, 0.488298,-0.0256397) , 
0, 13.59, 1, 0, 0.467552,-0.0414232)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611722,0.0199252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273528,-0.0389731) , 
7, -2.07788, 1, 0, 0.350513,-0.12321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605396,0.0171243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331622,-0.0400785) , 
2, 17.4637, 1, 0, 0.564061,0.0407269) , 
2, -13.074, 1, 0, 0.51474,0.00286434)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598544,0.0156374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164691,-0.0402036) , 
1, 29.1351, 1, 0, 0.549171,0.0464009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278632,-0.0473828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51336,-0.00108368) , 
6, -1.27984, 1, 0, 0.400244,-0.112903) , 
2, 5.51081, 1, 0, 0.507672,0.00201066)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.850626,0.0546931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637766,0.00704958) , 
5, 238.442, 1, 0, 0.765381,0.169086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153269,-0.0592498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473566,-0.005646) , 
4, -1.94909, 1, 0, 0.456687,-0.0405252) , 
1, 1.97554, 1, 0, 0.488245,-0.0190971)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421751,-0.0117086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256798,-0.0545873) , 
5, 411.247, 1, 0, 0.398825,-0.0849006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586975,0.0117977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260717,-0.0352544) , 
3, 0.944136, 1, 0, 0.54624,0.0283352) , 
4, -0.708663, 1, 0, 0.503667,-0.00436677)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.158692,-0.0572539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326192,-0.0151202) , 
6, -0.0359715, 1, 0, 0.231889,-0.186361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614418,0.00875003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359519,-0.0138244) , 
1, 11.8518, 1, 0, 0.512251,-0.00121672) , 
0, 14.5401, 1, 0, 0.47936,-0.0229376)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500512,-0.00157128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.811349,0.0513156) , 
5, 506.438, 1, 0, 0.52001,0.00825564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193999,-0.0560127) , 
2, 43.9327, 1, 0, 0.503878,-0.0052612)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239058,-0.0376186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487758,-0.00309445) , 
4, -1.57811, 1, 0, 0.452924,-0.0372909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769426,0.0358384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450595,-0.0015894) , 
1, 7.90148, 1, 0, 0.583666,0.0657796) , 
0, 39.831, 1, 0, 0.53027,0.0236851)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515037,0.00211724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346408,-0.0278508) , 
4, 0.882669, 1, 0, 0.469866,-0.0286299) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486375,-0.0124466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68309,0.0297482) , 
6, -1.97744, 1, 0, 0.648738,0.106281) , 
5, 253.872, 1, 0, 0.526617,0.0141733)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726251,0.0268128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883974,0.0566117) , 
7, -1.42838, 1, 0, 0.829623,0.21209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468528,-0.00827202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558256,0.0124125) , 
4, 0.0665079, 1, 0, 0.507138,0.00319261) , 
1, 1.9755, 1, 0, 0.537298,0.0227297)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327083,-0.0595853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490092,-0.000279252) , 
1, 0.988121, 1, 0, 0.475859,-0.0253344) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759013,0.0399871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608039,0.00937574) , 
0, 51.4763, 1, 0, 0.695012,0.127024) , 
5, 285.478, 1, 0, 0.534199,0.0152244)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476164,-0.0042222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299336,-0.0455068) , 
3, 0.433414, 1, 0, 0.426785,-0.0751066) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786693,0.036107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404589,-0.0117238) , 
1, 7.90185, 1, 0, 0.555737,0.0319098) , 
0, 40.0578, 1, 0, 0.496237,-0.0174692)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370608,-0.0219294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569098,0.00800418) , 
2, -9.90301, 1, 0, 0.5171,0.000731062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269981,-0.0359173) , 
0, 105.263, 1, 0, 0.503449,-0.0085656)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590183,0.0200134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405632,-0.015454) , 
6, -1.97791, 1, 0, 0.437913,-0.04306) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674196,0.0217967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373417,-0.0309671) , 
4, 0.88461, 1, 0, 0.605182,0.0433734) , 
5, 251.772, 1, 0, 0.490386,-0.0159457)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405547,-0.0209617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701729,0.0208551) , 
3, 0.232735, 1, 0, 0.659155,0.0679506) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366584,-0.00739955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265309,-0.0365712) , 
7, 2.9029, 1, 0, 0.348404,-0.0583471) , 
1, 11.8488, 1, 0, 0.52747,0.0144301)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371358,-0.0224571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620933,0.0116446) , 
4, -0.994833, 1, 0, 0.548842,0.008227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24843,-0.0547837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389413,-0.0119278) , 
6, -1.82227, 1, 0, 0.352876,-0.108957) , 
4, 0.9254, 1, 0, 0.501822,-0.0198903)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470798,-0.00145384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297844,-0.0385104) , 
6, -0.0441259, 1, 0, 0.368243,-0.109459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59137,0.0119516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30044,-0.0365093) , 
2, 32.3464, 1, 0, 0.570373,0.0389218) , 
2, -13.4742, 1, 0, 0.525484,0.00596949)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705789,0.0185065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302883,-0.037768) , 
4, 1.35941, 1, 0, 0.643687,0.0424182) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426867,-0.00799203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24613,-0.0334309) , 
4, 0.915455, 1, 0, 0.38166,-0.0669554) , 
1, 7.90137, 1, 0, 0.489355,-0.0220019)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648576,0.0135002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289589,-0.0170903) , 
1, 18.2714, 1, 0, 0.553341,0.0251971) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468935,0.00965299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297005,-0.0315948) , 
5, 102.169, 1, 0, 0.33462,-0.106267) , 
4, 0.882669, 1, 0, 0.493834,-0.0105702)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405781,-0.0398946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456703,0.00299155) , 
1, 10.3622, 1, 0, 0.426694,-0.101962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55585,0.0127807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458366,-0.0147549) , 
7, 1.96121, 1, 0, 0.521647,0.0138013) , 
7, -2.82268, 1, 0, 0.50597,-0.00531102)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275893,-0.0352663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485853,-0.00476818) , 
2, -7.16619, 1, 0, 0.426807,-0.0610949) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328658,-0.0367558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643978,0.0159923) , 
3, 0.170768, 1, 0, 0.603981,0.0408403) , 
5, 254.665, 1, 0, 0.480987,-0.0299232)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40111,-0.000201407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350805,-0.0340066) , 
4, -1.27679, 1, 0, 0.371064,-0.0946713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625735,0.0199613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47945,-0.00899351) , 
2, 5.87755, 1, 0, 0.587147,0.0559203) , 
4, -0.708663, 1, 0, 0.519728,0.008935)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518106,0.00297722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25858,-0.0458163) , 
2, 25.6127, 1, 0, 0.498866,-0.00292263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401993,-0.0627051) , 
5, 666.572, 1, 0, 0.495423,-0.0119674)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726499,0.0191516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.843946,0.0495207) , 
1, 2.87718, 1, 0, 0.758314,0.118612) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380655,-0.0292463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487791,0.00313145) , 
6, -2.44305, 1, 0, 0.472947,-0.00624036) , 
1, 3.95076, 1, 0, 0.532478,0.0198051)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354009,-0.0188719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.599159,0.00981517) , 
4, -0.996036, 1, 0, 0.541515,0.014135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179176,-0.0502847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375728,-0.00242051) , 
6, -0.0383071, 1, 0, 0.253374,-0.149987) , 
4, 1.44326, 1, 0, 0.49921,-0.00996144)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506396,0.00331981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752106,0.0423411) , 
4, -0.327529, 1, 0, 0.646227,0.115602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740242,0.0231679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427397,-0.0151658) , 
1, 1.97554, 1, 0, 0.457803,-0.0531218) , 
6, -2.59842, 1, 0, 0.472043,-0.0403702)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537257,0.00524464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219205,-0.0406897) , 
2, 38.171, 1, 0, 0.519764,0.0126089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402103,-0.0212719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463099,-0.0316713) , 
0, 35.0718, 1, 0, 0.427354,-0.112532) , 
7, 3.03936, 1, 0, 0.508619,-0.00248398)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305444,-0.0279116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514284,-0.00190646) , 
2, -17.8898, 1, 0, 0.476562,-0.0299118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.837009,0.0531783) , 
5, 638.918, 1, 0, 0.487874,-0.0213821)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367046,-0.0162021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642129,0.0212323) , 
2, -16.1463, 1, 0, 0.563049,0.0465727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326903,-0.0393096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55573,0.0109049) , 
6, 0.659417, 1, 0, 0.408392,-0.0965363) , 
2, 5.51081, 1, 0, 0.522144,0.00872206)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444127,-0.0190728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617657,0.00131717) , 
0, 39.831, 1, 0, 0.542951,-0.0355234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.17109,-0.0246079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457402,0.0152812) , 
4, -1.62044, 1, 0, 0.428355,0.0524846) , 
1, 12.8398, 1, 0, 0.503757,-0.00542324)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.13075,-0.0518694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383474,-0.00422045) , 
2, -2.82761, 1, 0, 0.24354,-0.130728) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595217,0.00669703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358045,-0.0202621) , 
4, 0.895103, 1, 0, 0.526892,-0.00523984) , 
4, -1.53275, 1, 0, 0.499531,-0.017357)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183285,-0.0450718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450082,0.0190013) , 
5, 184.727, 1, 0, 0.274469,-0.103253) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619965,0.0138159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405035,-0.0108034) , 
4, 0.607031, 1, 0, 0.535547,0.0185874) , 
4, -1.38526, 1, 0, 0.502177,0.00301416)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535213,-0.00569209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479486,0.0194869) , 
1, 13.8874, 1, 0, 0.521902,0.00129786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207611,-0.0161234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142839,-0.0523189) , 
5, 205.102, 1, 0, 0.172939,-0.156477) , 
1, 33.0862, 1, 0, 0.494274,-0.0111934)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675244,0.0107166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393324,-0.0154655) , 
1, 5.92618, 1, 0, 0.485746,-0.0325857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689417,0.0413194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532305,0.00320684) , 
5, 130.881, 1, 0, 0.574037,0.0592399) , 
7, 0.302879, 1, 0, 0.525012,0.00825274)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.738789,0.0392757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471371,-0.00279195) , 
3, 0.658984, 1, 0, 0.679008,0.13489) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445114,-0.0125535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562594,0.00929772) , 
6, 1.27989, 1, 0, 0.477912,-0.0283269) , 
7, -2.37461, 1, 0, 0.512394,-0.000340455)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637806,0.00724249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325305,-0.0428521) , 
2, 15.5787, 1, 0, 0.593794,8.84235e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323027,-0.0193396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662971,0.0252238) , 
5, 569.381, 1, 0, 0.345449,-0.0737613) , 
1, 9.38289, 1, 0, 0.468346,-0.0372156)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504113,-0.020374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.736169,0.0129413) , 
3, 0.593492, 1, 0, 0.580557,-0.0413539) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584755,0.0266347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407879,-0.00621001) , 
3, 0.535586, 1, 0, 0.499256,0.049264) , 
1, 5.92544, 1, 0, 0.530364,0.0145905)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479185,-0.00175804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641365,0.0162151) , 
5, 256.784, 1, 0, 0.533564,0.0186841) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464603,-0.00114209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148139,-0.0542948) , 
3, 1.22941, 1, 0, 0.250721,-0.166718) , 
0, 93.3957, 1, 0, 0.505671,0.00040032)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.227342,-0.0433718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440562,0.00201247) , 
4, -0.270753, 1, 0, 0.330677,-0.0929685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564202,0.00656569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257138,-0.0415959) , 
0, 99.5726, 1, 0, 0.548647,0.0182565) , 
2, -13.222, 1, 0, 0.498269,-0.00745033)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347469,-0.0382116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462244,-0.00854901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551913,0.00911373) , 
4, 0.0210245, 1, 0, 0.504246,-0.00110899) , 
7, -3.43118, 1, 0, 0.496277,-0.00979921)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366823,-0.0226374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.684801,0.0248494) , 
3, 0.257346, 1, 0, 0.57989,0.0375771) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333465,-0.0361883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459804,-0.00867807) , 
7, -1.90644, 1, 0, 0.442398,-0.0558375) , 
7, -2.37104, 1, 0, 0.467782,-0.0385911)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566178,0.00305692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291282,-0.0192787) , 
1, 16.787, 1, 0, 0.494195,-0.0122488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632939,0.0328429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527031,0.00523749) , 
6, 1.7015, 1, 0, 0.566939,0.0690782) , 
6, 0.659495, 1, 0, 0.5202,0.0168246)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637764,0.0219153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269699,-0.0117142) , 
1, 22.7086, 1, 0, 0.563956,0.068831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396875,-0.0168793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558674,0.00389451) , 
2, -1.47375, 1, 0, 0.469106,-0.0337556) , 
6, -1.20204, 1, 0, 0.495367,-0.0053526)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45558,-0.0075555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622912,0.0171905) , 
2, -3.73772, 1, 0, 0.552329,0.0298715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229434,-0.0451086) , 
2, 43.2344, 1, 0, 0.538015,0.0198197)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30229,-0.0414385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47633,-0.0012662) , 
7, -2.80169, 1, 0, 0.45993,-0.0224255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405651,-0.0315135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.761776,0.0347736) , 
6, -2.21002, 1, 0, 0.684165,0.0853264) , 
5, 347.045, 1, 0, 0.503215,-0.0016255)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35208,-0.0221384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561279,0.00428977) , 
2, -9.07979, 1, 0, 0.493893,-0.0184863) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278845,-0.0509694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351612,-0.00862155) , 
1, 10.8584, 1, 0, 0.305422,-0.161704) , 
2, 14.0545, 1, 0, 0.46894,-0.037448)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266015,-0.0506922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364546,0.0012668) , 
1, 8.39863, 1, 0, 0.326507,-0.0857973) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285066,-0.0229863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587685,0.00742136) , 
4, -1.39565, 1, 0, 0.550183,0.0166996) , 
2, -20.0474, 1, 0, 0.511451,-0.00104862)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.845327,0.0561038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561277,0.0103746) , 
7, -2.06912, 1, 0, 0.620196,0.0862997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407722,-0.0221791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506973,-5.96394e-06) , 
6, -1.0287, 1, 0, 0.489999,-0.0169014) , 
6, -1.90015, 1, 0, 0.513175,0.00146926)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501087,0.000793522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647687,0.0254749) , 
0, 53.2829, 1, 0, 0.548425,0.0366708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52528,0.00100267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352914,-0.0345662) , 
0, 66.0406, 1, 0, 0.463271,-0.0526854) , 
2, 5.51982, 1, 0, 0.526236,0.0133869)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401462,0.00203995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225527,-0.0521251) , 
5, 244.077, 1, 0, 0.299233,-0.138262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559931,0.00450441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291297,-0.0201109) , 
4, 1.43258, 1, 0, 0.528069,0.00689701) , 
3, 0.149225, 1, 0, 0.506859,-0.00655688)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66167,0.0240528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462595,-0.00572273) , 
6, -2.28798, 1, 0, 0.486152,-0.00960084) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568255,-0.00696409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313484,-0.0567467) , 
3, 0.559781, 1, 0, 0.460746,-0.122246) , 
5, 419.745, 1, 0, 0.482016,-0.0279365)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284412,-0.0468319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435675,-0.00930118) , 
7, -2.05458, 1, 0, 0.406264,-0.0742566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336979,-0.0481832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617294,0.0166203) , 
6, -2.59793, 1, 0, 0.584659,0.0384951) , 
5, 225.223, 1, 0, 0.472077,-0.0326605)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449373,0.00359545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215881,-0.0552563) , 
0, 39.5521, 1, 0, 0.33366,-0.117252) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45984,-0.0187223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525848,0.0058189) , 
7, -2.72903, 1, 0, 0.513603,0.00486646) , 
5, 58.6654, 1, 0, 0.491428,-0.0101828)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264406,-0.0496881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737336,0.0407329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482169,-0.00389709) , 
6, -2.3148, 1, 0, 0.501371,-0.00253368) , 
6, -2.83113, 1, 0, 0.484172,-0.0184899)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219353,-0.0393679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501703,-0.00319722) , 
0, 13.6319, 1, 0, 0.474849,-0.0293542) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749758,0.0371297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272424,-0.0125576) , 
1, 17.2835, 1, 0, 0.591797,0.0929579) , 
6, 2.13315, 1, 0, 0.491093,-0.0123655)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223001,-0.0357788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518912,0.00235172) , 
3, 0.0988637, 1, 0, 0.493942,-0.00418552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456404,-0.010435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322661,-0.0539641) , 
7, 2.49737, 1, 0, 0.432705,-0.0774164) , 
0, 53.0647, 1, 0, 0.470627,-0.0320666)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424256,-0.00914545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574382,0.00827398) , 
5, 194.318, 1, 0, 0.488043,-0.00752954) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292519,-0.0525107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543445,-0.00253941) , 
4, 0.0193626, 1, 0, 0.395178,-0.140062) , 
6, 2.67612, 1, 0, 0.48009,-0.0188789)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555719,0.0116353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388012,-0.0147178) , 
0, 70.0792, 1, 0, 0.516191,0.023576) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320793,-0.0401906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475411,-0.00861963) , 
7, 2.57723, 1, 0, 0.435865,-0.0737057) , 
7, 2.31783, 1, 0, 0.495868,-0.00103712)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545112,0.00818687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117343,-0.0440598) , 
4, 2.00743, 1, 0, 0.525944,0.0262188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50355,-0.00909335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241194,-0.0478269) , 
1, 11.3639, 1, 0, 0.377768,-0.129212) , 
6, 2.75368, 1, 0, 0.514476,0.0141901)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59089,0.0141398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351661,-0.0431276) , 
4, -0.0048598, 1, 0, 0.467291,-0.0731068) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578715,0.0143417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327513,-0.0156852) , 
2, 12.6815, 1, 0, 0.537062,0.0408228) , 
7, -2.7611, 1, 0, 0.526735,0.0239608)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369442,-0.0310854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56622,0.0102512) , 
7, -3.27556, 1, 0, 0.55089,0.0300824) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275032,-0.0744377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682478,0.0340133) , 
4, 0.00775643, 1, 0, 0.428125,-0.138054) , 
6, 2.59849, 1, 0, 0.538133,0.0126111)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385599,-0.0125953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54888,0.00409368) , 
4, -0.659563, 1, 0, 0.496751,-0.00512977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434239,-0.0575369) , 
5, 632.324, 1, 0, 0.494743,-0.0123788)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460311,-0.0346622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50714,0.00307509) , 
1, 0.987888, 1, 0, 0.502703,-0.00133838) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482072,-0.00365415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330596,-0.0514149) , 
6, 0.271604, 1, 0, 0.390014,-0.142458) , 
7, 2.3396, 1, 0, 0.477312,-0.0331353)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677284,0.0136512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.887905,0.0492999) , 
6, -0.0394515, 1, 0, 0.77497,0.119437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417919,-0.0082422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646291,0.0180745) , 
5, 350.024, 1, 0, 0.458667,-0.0152318) , 
1, 1.97575, 1, 0, 0.490964,-0.00148117)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275614,-0.0280535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422932,0.0112053) , 
0, 57.083, 1, 0, 0.327972,-0.0583882) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61526,-0.00414711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516648,0.0126045) , 
1, 6.91465, 1, 0, 0.55914,0.0244837) , 
2, -12.8978, 1, 0, 0.503773,0.00463493)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479627,-0.00157028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167201,-0.0473016) , 
2, 22.6416, 1, 0, 0.456589,-0.0212961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722004,0.033222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60079,0.00731016) , 
4, -0.0770084, 1, 0, 0.650478,0.0770542) , 
5, 285.478, 1, 0, 0.504776,0.00314676)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493989,-0.0170968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44314,0.012053) , 
1, 11.358, 1, 0, 0.47611,-0.029937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395999,-0.0137227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641378,0.0216484) , 
5, 81.2891, 1, 0, 0.585677,0.0570668) , 
6, 0.737191, 1, 0, 0.513808,-2.24369e-06)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468961,-0.00152454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414342,-0.0360437) , 
4, -0.300678, 1, 0, 0.455494,-0.0436802) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38163,-0.013395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.623025,0.0193958) , 
0, 29.9595, 1, 0, 0.545673,0.0374159) , 
4, -0.0215628, 1, 0, 0.499113,-0.00445475)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493779,-0.00784891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52783,0.00968134) , 
7, -1.86507, 1, 0, 0.514155,0.0114728) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425537,-0.0215181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568862,0.0162725) , 
3, 0.582034, 1, 0, 0.457479,-0.0569605) , 
7, 2.25247, 1, 0, 0.500369,-0.0051733)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601265,0.0170422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452284,-0.0101787) , 
6, -1.43479, 1, 0, 0.487749,-0.0160864) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596869,0.0184272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469686,-0.0104162) , 
6, 1.66787, 1, 0, 0.565171,0.0484835) , 
4, 0.0665079, 1, 0, 0.523473,0.0137074)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436541,-0.00857684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556244,0.0113539) , 
3, 0.479169, 1, 0, 0.495754,0.00503123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567504,-0.00195916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346337,-0.049881) , 
3, 0.495708, 1, 0, 0.439164,-0.129485) , 
5, 412.023, 1, 0, 0.485205,-0.0200436)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373559,-0.0155303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576982,0.00829697) , 
3, 0.346495, 1, 0, 0.511093,0.00178356) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.119981,-0.067702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166885,-0.0335844) , 
3, 1.56716, 1, 0, 0.145231,-0.216353) , 
3, 1.33326, 1, 0, 0.485831,-0.0132786)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503705,-0.0342493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505254,0.0073667) , 
1, 1.48194, 1, 0, 0.505097,0.0142541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318481,-0.052419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492557,-0.00544955) , 
7, 1.83932, 1, 0, 0.467742,-0.0545014) , 
7, 1.65776, 1, 0, 0.491732,-0.0103457)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552171,0.00750861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417433,-0.0176008) , 
7, 2.91035, 1, 0, 0.531163,0.0152286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18081,-0.0399484) , 
3, 1.33543, 1, 0, 0.513674,0.0058562)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370724,-0.0160048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541827,0.00250144) , 
4, -0.619287, 1, 0, 0.486407,-0.0148498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668477,0.0391731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500908,-0.00323116) , 
3, 0.532562, 1, 0, 0.581014,0.0736954) , 
6, 2.13319, 1, 0, 0.500827,-0.00135387)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617443,0.010268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427403,-0.00740385) , 
1, 5.92609, 1, 0, 0.496114,-0.00559007) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55317,0.0248683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201448,-0.0872477) , 
5, 262.549, 1, 0, 0.345824,-0.179111) , 
6, 2.67617, 1, 0, 0.483608,-0.0200295)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520404,0.0333359) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432053,-0.0134599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.65707,0.0142491) , 
5, 349.08, 1, 0, 0.470125,-0.0375855) , 
3, 0.15089, 1, 0, 0.472979,-0.0273118)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455315,0.011538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152256,-0.0550654) , 
6, 1.00434, 1, 0, 0.301922,-0.0980581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232245,-0.0342724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557539,0.00283156) , 
2, -16.971, 1, 0, 0.521945,-0.00498001) , 
2, -31.7139, 1, 0, 0.497878,-0.0151609)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491414,-0.0316068) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533262,0.00614822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196633,-0.0240449) , 
1, 31.8121, 1, 0, 0.504063,0.0159975) , 
1, 0.987882, 1, 0, 0.503092,0.00484761)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421912,-0.0023059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633073,0.020137) , 
2, -2.35722, 1, 0, 0.532732,0.0405739) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393308,-0.0385264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649606,0.012323) , 
5, 491.29, 1, 0, 0.528224,-0.0533482) , 
5, 412.023, 1, 0, 0.532037,0.0260822)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688567,0.0268687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504553,-0.00247719) , 
6, -2.0553, 1, 0, 0.531412,0.00774296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.208824,-0.0487087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389973,0.00173331) , 
7, -0.706111, 1, 0, 0.285958,-0.123649) , 
4, 1.32292, 1, 0, 0.492241,-0.0132256)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430611,-0.0212552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508527,0.00393059) , 
7, -1.41241, 1, 0, 0.474986,-0.0295924) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827147,0.045033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483128,0.0118936) , 
1, 7.89722, 1, 0, 0.609962,0.0993742) , 
6, 0.659417, 1, 0, 0.52178,0.0151181)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595132,0.0156329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486767,-0.00693938) , 
7, 1.47549, 1, 0, 0.553389,0.0286964) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531018,0.00197405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217841,-0.0323298) , 
1, 11.8489, 1, 0, 0.363351,-0.0704838) , 
3, 0.708321, 1, 0, 0.504577,0.00322184)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79747,0.0393701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692782,0.0133218) , 
6, -0.193767, 1, 0, 0.736779,0.0957895) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504517,-0.00150553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294782,-0.0256938) , 
4, 1.0956, 1, 0, 0.460819,-0.0284645) , 
1, 3.45701, 1, 0, 0.510659,-0.00602347)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522504,0.00707637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480727,-0.0216107) , 
5, 411.071, 1, 0, 0.516108,0.0105495) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35531,-0.0287005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539133,-0.00133943) , 
5, 181.891, 1, 0, 0.440856,-0.0690522) , 
6, 1.12484, 1, 0, 0.489663,-0.0174242)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.312954,-0.0407494) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531854,-0.0300187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518508,0.00374108) , 
1, 0.987888, 1, 0, 0.519493,0.00601605) , 
6, -2.83112, 1, 0, 0.503943,-0.0080517)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697153,0.0296064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490498,-0.00461377) , 
6, -2.36549, 1, 0, 0.511773,-0.00501486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637993,0.0473384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340796,0.00534278) , 
4, 1.76525, 1, 0, 0.490573,0.116793) , 
4, 1.32113, 1, 0, 0.509403,0.00860604)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474451,-0.0109684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.810722,0.0396287) , 
5, 588.512, 1, 0, 0.490915,-0.0363952) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445035,-0.0202359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532553,0.0155647) , 
6, -2.21008, 1, 0, 0.514433,0.0334947) , 
4, 0.579319, 1, 0, 0.498048,-0.0151974)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150993,-0.0422088) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568036,0.0243652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538431,0.000285628) , 
0, 28.7624, 1, 0, 0.545179,0.0253759) , 
4, -1.94306, 1, 0, 0.526131,0.0158661)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322852,-0.0365586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207303,-0.0282195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572634,0.00865155) , 
4, -1.46799, 1, 0, 0.524571,0.0178106) , 
7, -3.30579, 1, 0, 0.507451,0.00233545)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672496,0.0287042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402154,-0.0184113) , 
6, -1.97764, 1, 0, 0.438177,-0.0512903) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374888,-0.0324144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570603,0.00562998) , 
6, -2.59842, 1, 0, 0.548457,0.0055183) , 
5, 191.282, 1, 0, 0.489152,-0.0250313)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392397,0.027314) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506754,-0.00690296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137991,-0.0413257) , 
1, 36.0494, 1, 0, 0.495,-0.0340424) , 
4, -1.63781, 1, 0, 0.489795,-0.0272238)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294284,-0.0475039) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50414,-0.000447287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41147,-0.0255114) , 
7, 3.28285, 1, 0, 0.497538,-0.00964513) , 
6, -2.90851, 1, 0, 0.486268,-0.0210384)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722481,0.0371295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476245,-0.00445834) , 
4, 0.465909, 1, 0, 0.617334,0.0813822) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453833,-0.0110533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542466,0.0111025) , 
4, 0.355439, 1, 0, 0.486092,-0.0124701) , 
7, -2.34663, 1, 0, 0.511816,0.00592521)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4933,0.000402957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459537,-0.0188722) , 
3, 0.426049, 1, 0, 0.472414,-0.0491706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471132,0.0329505) , 
3, 1.07671, 1, 0, 0.472348,-0.0399258)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237585,-0.0571789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52066,-0.00692289) , 
0, 36.9301, 1, 0, 0.407204,-0.119439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611613,0.00810422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317656,-0.0135241) , 
1, 11.8506, 1, 0, 0.476371,-0.00789882) , 
6, -1.97774, 1, 0, 0.462672,-0.02999)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339265,-0.0247989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496061,-0.000814313) , 
7, -3.2068, 1, 0, 0.481756,-0.0133505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.763783,0.0270597) , 
5, 588.512, 1, 0, 0.494781,-0.00756331)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52903,0.0125876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406071,-0.0286473) , 
0, 28.3358, 1, 0, 0.441804,-0.0675525) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48647,-0.00983091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537853,0.0127159) , 
6, -1.58986, 1, 0, 0.523208,0.0259872) , 
7, -1.91943, 1, 0, 0.497478,-0.00357869)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.817033,0.0376329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425595,-0.00819707) , 
1, 1.97552, 1, 0, 0.460839,-0.0182921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760026,0.0445189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699782,0.0187315) , 
5, 627.359, 1, 0, 0.742256,0.149773) , 
5, 445.284, 1, 0, 0.488956,-0.00150036)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414496,0.00325881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715008,0.0507225) , 
3, 0.233592, 1, 0, 0.500952,0.0746974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465614,-0.0253664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52224,0.00146864) , 
7, -2.76317, 1, 0, 0.515117,-0.00850893) , 
0, 26.5972, 1, 0, 0.5121,0.00921369)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390033,-0.002675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419508,-0.0340563) , 
4, -0.778148, 1, 0, 0.402071,-0.0677017) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633907,0.0133818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357387,-0.0127772) , 
4, 0.95155, 1, 0, 0.516044,0.0087994) , 
4, -0.247851, 1, 0, 0.465311,-0.0252535)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537536,0.00812622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702428,0.044999) , 
7, 2.77742, 1, 0, 0.550026,0.0465373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382624,-0.0357558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662525,0.01379) , 
6, 0.349337, 1, 0, 0.478376,-0.0857509) , 
5, 445.169, 1, 0, 0.539803,0.0276624)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629857,0.0209526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683846,0.0443102) , 
5, 204.012, 1, 0, 0.652183,0.132322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405532,-0.0143361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58197,0.0051655) , 
0, 41.5372, 1, 0, 0.498944,-0.0182617) , 
6, -2.67599, 1, 0, 0.511084,-0.00633168)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306577,-0.0350892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487337,-0.00590523) , 
3, 0.362611, 1, 0, 0.438793,-0.0605334) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51683,0.00641906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413496,-0.0218178) , 
6, 2.69715, 1, 0, 0.504817,0.0130888) , 
6, -1.35737, 1, 0, 0.485558,-0.00838684)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443325,-0.0125951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501057,0.00632668) , 
4, 0.57482, 1, 0, 0.460401,-0.0296399) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731351,0.0540304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571477,0.00139351) , 
4, -0.816461, 1, 0, 0.595994,0.0396807) , 
5, 288.111, 1, 0, 0.498706,-0.0100567)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580938,0.0148951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37004,-0.0139985) , 
0, 73.0771, 1, 0, 0.541545,0.0406842) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511331,-0.0034621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277081,-0.0375594) , 
4, 1.10361, 1, 0, 0.462909,-0.0469988) , 
6, 0.116445, 1, 0, 0.502112,-0.00328466)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408449,-0.0170911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279929,-0.0640811) , 
7, -2.98433, 1, 0, 0.366286,-0.142659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560239,0.00839646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374505,-0.0193904) , 
2, 6.82121, 1, 0, 0.513293,0.00521443) , 
7, -2.74343, 1, 0, 0.48545,-0.0227927)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475845,-0.0045377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604255,0.0241168) , 
7, 2.6233, 1, 0, 0.487334,-0.0086463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337421,-0.0475116) , 
7, 3.44256, 1, 0, 0.479092,-0.0193714)    );
   return;
};

// Clean up
inline void ReadBDT-0.3_fold8::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.3_fold8::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
