// Class: ReadBDT-0.3_fold1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.3_fold1
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.32/00       [401408]
Creator        : htan
Date           : Mon Aug 12 11:26:53 2024
Host           : Linux 6772f6b99311 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May 9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gluster/home/htan/ZTTBDT
Training events: 88982
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
m_met_pT                      m_met_pT                      m_met_pT                      m_met_pT                                                        'F'    [0.129616737366,1149.01928711]
m_mWT                         m_mWT                         m_mWT                         m_mWT                                                           'F'    [0.000240040215431,39.9999656677]
m_d_zeta                      m_d_zeta                      m_d_zeta                      m_d_zeta                                                        'F'    [-1859.73010254,1223.64221191]
m_ratioMetTauPT               m_ratioMetTauPT               m_ratioMetTauPT               m_ratioMetTauPT                                                 'F'    [0.00113642180804,11.9963302612]
m_etaSeparation               m_etaSeparation               m_etaSeparation               m_etaSeparation                                                 'F'    [-4.54272270203,4.61262607574]
m_pTSumMag                    m_pTSumMag                    m_pTSumMag                    m_pTSumMag                                                      'F'    [2.89208579063,2552.09106445]
m_pTSumPhi                    m_pTSumPhi                    m_pTSumPhi                    m_pTSumPhi                                                      'F'    [-3.14139199257,3.1415784359]
m_pTSumEta                    m_pTSumEta                    m_pTSumEta                    m_pTSumEta                                                      'F'    [-7.66828012466,7.56654691696]
NSpec 1
m_event_number                m_event_number                m_event_number                I                                                               'F'    [113,1214786176]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.3_fold1Node

#ifndef BDT-0.3_fold1Node__def
#define BDT-0.3_fold1Node__def

class BDT-0.3_fold1Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.3_fold1Node ( BDT-0.3_fold1Node* left,BDT-0.3_fold1Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.3_fold1Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold1Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold1Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.3_fold1Node*   fLeft;     // pointer to the left daughter node
   BDT-0.3_fold1Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.3_fold1Node::~BDT-0.3_fold1Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.3_fold1Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.3_fold1Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.3_fold1 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.3_fold1( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.3_fold1" ),
        fNvars( 8 )
   {
      // the training input variables
      const char* inputVars[] = { "m_met_pT", "m_mWT", "m_d_zeta", "m_ratioMetTauPT", "m_etaSeparation", "m_pTSumMag", "m_pTSumPhi", "m_pTSumEta" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.3_fold1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.3_fold1Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.3_fold1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.3_fold1Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.3_fold1Node*)current->GetRight();
         else current=(BDT-0.3_fold1Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.3_fold1::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639323,0.0278647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.151929,-0.0696143) , 
3, 1.48376, 1, 0, 0.614642,0.114642) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494265,-0.00114696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257649,-0.0484701) , 
3, 0.557413, 1, 0, 0.36655,-0.13345) , 
1, 12.344, 1, 0, 0.516426,0.0164261)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449485,-0.0126166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.82596,0.0625494) , 
2, -10.8077, 1, 0, 0.753419,0.240136) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685347,0.0363078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425933,-0.0151259) , 
7, -2.36852, 1, 0, 0.475713,-0.0262502) , 
1, 3.45747, 1, 0, 0.52711,0.0230517)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39991,-0.023815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664508,0.0291341) , 
3, 0.303154, 1, 0, 0.604743,0.0855995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331507,-0.0311253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502914,0.00234864) , 
5, 272.786, 1, 0, 0.380385,-0.107673) , 
1, 11.852, 1, 0, 0.512106,0.0057976)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294166,-0.0457104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682233,0.0307536) , 
4, -1.37791, 1, 0, 0.632137,0.103816) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443938,-0.00888912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225287,-0.0504578) , 
1, 29.0388, 1, 0, 0.398262,-0.0875062) , 
1, 9.38301, 1, 0, 0.518208,0.0106154)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527004,-0.00173903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.83486,0.054856) , 
3, 0.356986, 1, 0, 0.742103,0.185488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.260223,-0.044966) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499649,-0.000196506) , 
5, 53.6781, 1, 0, 0.473073,-0.025667) , 
1, 3.45723, 1, 0, 0.52089,0.0118633)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360362,-0.026923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.160655,-0.0692066) , 
4, 1.14117, 1, 0, 0.304858,-0.192858) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320539,-0.0358777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638793,0.0230164) , 
2, -10.733, 1, 0, 0.541635,0.0244312) , 
3, 0.299249, 1, 0, 0.481274,-0.0309612)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517298,-0.00339328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.735386,0.0356858) , 
0, 44.3265, 1, 0, 0.621681,0.0749595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425095,-0.00833744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291723,-0.038102) , 
5, 288.651, 1, 0, 0.369703,-0.103001) , 
1, 9.38406, 1, 0, 0.488258,-0.0192707)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610209,0.0166185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392011,-0.0270096) , 
4, 1.39978, 1, 0, 0.586165,0.05812) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469496,0.00435099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275592,-0.0350705) , 
0, 21.2898, 1, 0, 0.305353,-0.143291) , 
1, 18.7656, 1, 0, 0.51946,0.0102762)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40896,-0.0138374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174104,-0.0556784) , 
4, 1.0858, 1, 0, 0.335714,-0.132896) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605787,0.0155265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359084,-0.0269545) , 
0, 88.0356, 1, 0, 0.572501,0.047841) , 
3, 0.298958, 1, 0, 0.515201,0.00410508)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58873,0.00936585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326271,-0.023949) , 
1, 15.8046, 1, 0, 0.513676,-0.00100876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.16143,-0.0645579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290606,-0.0374472) , 
6, -0.813944, 1, 0, 0.231196,-0.244804) , 
3, 1.04333, 1, 0, 0.486656,-0.0243288)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623879,0.0168716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340853,-0.0419371) , 
2, 18.0394, 1, 0, 0.588346,0.0464671) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60316,0.0311454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296147,-0.0261747) , 
7, -2.47079, 1, 0, 0.34135,-0.0859704) , 
1, 16.2966, 1, 0, 0.517438,0.00844641)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228193,-0.0530286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607915,0.0173531) , 
4, -1.96738, 1, 0, 0.588364,0.0664944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464604,-0.00526425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229706,-0.0504121) , 
6, -1.12423, 1, 0, 0.280407,-0.198389) , 
4, 1.0956, 1, 0, 0.517886,0.00587396)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61157,0.0135184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281184,-0.0431271) , 
2, 19.1233, 1, 0, 0.572916,0.0333629) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22217,-0.0429601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377227,-0.00711546) , 
4, -0.112592, 1, 0, 0.294087,-0.128486) , 
1, 18.2715, 1, 0, 0.510341,-0.00295935)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.09345,-0.0830668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394847,-0.0212612) , 
5, 92.0996, 1, 0, 0.315758,-0.183715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599611,0.0145385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403896,-0.0188817) , 
4, 0.902234, 1, 0, 0.540706,0.0216051) , 
4, -1.04696, 1, 0, 0.497176,-0.0181267)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491405,0.0024948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224757,-0.051431) , 
7, -0.187195, 1, 0, 0.330694,-0.14599) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582641,0.0110222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168311,-0.0471011) , 
1, 31.6009, 1, 0, 0.55316,0.0336611) , 
2, -19.7966, 1, 0, 0.515125,0.0029465)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544728,-0.000630454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239964,-0.0430399) , 
1, 6.91881, 1, 0, 0.325659,-0.150534) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569348,0.00959674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332365,-0.0331041) , 
3, 0.89123, 1, 0, 0.538103,0.0189985) , 
4, -0.925795, 1, 0, 0.489447,-0.0198296)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0894986,-0.0730333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469345,-0.00897571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605895,0.0177589) , 
5, 308.829, 1, 0, 0.504111,-0.01029) , 
4, -1.98546, 1, 0, 0.485218,-0.025824)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556413,0.00394287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197169,-0.0390734) , 
1, 29.1357, 1, 0, 0.517752,-0.00267274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18379,-0.0493817) , 
4, 1.79142, 1, 0, 0.491192,-0.0211659)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226832,-0.0558269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363631,-0.0141885) , 
1, 6.41951, 1, 0, 0.300727,-0.163446) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602503,0.00812587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288444,-0.0237317) , 
1, 16.7903, 1, 0, 0.523154,0.000775882) , 
3, 0.240153, 1, 0, 0.480686,-0.0305791)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496752,-0.0191017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.802102,0.0407204) , 
4, -0.888007, 1, 0, 0.727748,0.119626) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405627,-0.0151892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.782621,0.0567665) , 
5, 569.638, 1, 0, 0.418652,-0.0607935) , 
1, 3.45954, 1, 0, 0.472519,-0.0293515)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258109,-0.0362105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508055,0.00621975) , 
5, 428.201, 1, 0, 0.300425,-0.13836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688956,0.022286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363171,-0.0117603) , 
1, 11.8506, 1, 0, 0.549153,0.0364425) , 
3, 0.241797, 1, 0, 0.502195,0.00344119)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224335,-0.0526632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383735,-0.0164892) , 
4, -0.647805, 1, 0, 0.328065,-0.138998) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483113,-0.00942181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641141,0.0234858) , 
6, -1.59004, 1, 0, 0.592033,0.062356) , 
2, -13.222, 1, 0, 0.52734,0.0130084)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685464,0.0275428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206802,-0.0392062) , 
1, 28.6329, 1, 0, 0.626014,0.0913226) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345538,-0.0304846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482996,-0.00532414) , 
4, -0.607362, 1, 0, 0.441576,-0.0604575) , 
7, -1.49614, 1, 0, 0.49646,-0.0152916)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508377,-0.0020059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.763485,0.0441492) , 
0, 68.4127, 1, 0, 0.528023,0.00726199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406844,-0.0142317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152761,-0.0798201) , 
4, 1.10374, 1, 0, 0.349169,-0.13834) , 
3, 0.744474, 1, 0, 0.491791,-0.0222343)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.338424,-0.0218627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606276,0.0151743) , 
2, -19.7966, 1, 0, 0.559621,0.0414078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.203895,-0.0218227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0861233,-0.056329) , 
4, 0.167006, 1, 0, 0.129144,-0.18911) , 
1, 31.1107, 1, 0, 0.512105,0.0159631)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228977,-0.0429127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283448,-0.0233813) , 
0, 9.40847, 1, 0, 0.250873,-0.167202) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560959,0.00824565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186992,-0.0517138) , 
3, 1.35002, 1, 0, 0.541545,0.02404) , 
0, 14.3134, 1, 0, 0.501519,-0.0022945)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.312647,-0.0228993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67229,0.029993) , 
0, 18.5762, 1, 0, 0.528742,0.0411991) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237281,-0.0477064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50977,-0.0073662) , 
5, 71.6943, 1, 0, 0.459312,-0.0693128) , 
3, 0.445403, 1, 0, 0.485955,-0.0269051)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379608,-0.0337642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488738,-0.00140971) , 
7, -1.84763, 1, 0, 0.455493,-0.0524073) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446615,-0.0216173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.760333,0.0449997) , 
6, -1.8226, 1, 0, 0.676731,0.126886) , 
5, 350.024, 1, 0, 0.497624,-0.0182639)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385697,-0.0264013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468847,-0.00223791) , 
7, -0.904714, 1, 0, 0.433052,-0.0586037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706713,0.0307676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532131,-0.00975008) , 
0, 53.4224, 1, 0, 0.628304,0.0592451) , 
5, 333.782, 1, 0, 0.47183,-0.0351981)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580887,0.0110457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409624,-0.0141889) , 
4, 0.879534, 1, 0, 0.537416,0.0217796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159894,-0.0500743) , 
3, 1.25624, 1, 0, 0.514427,0.00674218)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468282,-0.00561275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620697,0.0191429) , 
2, 0.381895, 1, 0, 0.527054,0.0183151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554493,0.0176761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386179,-0.0300426) , 
3, 0.351456, 1, 0, 0.430035,-0.0818773) , 
7, 1.75547, 1, 0, 0.492833,-0.0170252)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398514,-0.0224915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498345,0.0047223) , 
3, 0.598678, 1, 0, 0.430651,-0.0648586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670479,0.0262809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434353,-0.020246) , 
2, 17.4874, 1, 0, 0.621719,0.0765001) , 
5, 232.593, 1, 0, 0.498365,-0.0147615)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462321,-0.0176992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.85583,0.0446068) , 
4, -0.876528, 1, 0, 0.770293,0.132751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487965,-0.00108386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296593,-0.0287808) , 
4, 0.885511, 1, 0, 0.439796,-0.0367402) , 
1, 3.45747, 1, 0, 0.491805,-0.0100679)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290648,-0.0464977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373107,-0.012916) , 
7, -2.00843, 1, 0, 0.344563,-0.113873) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442676,-0.0102303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612353,0.015687) , 
0, 40.0519, 1, 0, 0.543036,0.0226601) , 
4, -0.934196, 1, 0, 0.497155,-0.00890211)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513392,-0.0186905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.731179,0.0280107) , 
7, -2.79862, 1, 0, 0.693737,0.0906903) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419177,-0.000849124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277487,-0.0380269) , 
6, 1.6677, 1, 0, 0.383582,-0.0478138) , 
1, 7.90171, 1, 0, 0.505255,0.00652093)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40534,-0.0306357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358483,-0.00431628) , 
1, 10.3738, 1, 0, 0.385803,-0.0916587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576546,0.00608679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29437,-0.024141) , 
4, 1.3298, 1, 0, 0.516582,-0.00111291) , 
4, -0.51073, 1, 0, 0.471729,-0.0321674)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524367,0.00359633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444306,-0.0171033) , 
3, 0.541118, 1, 0, 0.484719,-0.0303328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.159875,-0.0824098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197384,-0.035205) , 
1, 8.3883, 1, 0, 0.179174,-0.271383) , 
0, 106.207, 1, 0, 0.466347,-0.0448262)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167402,-0.0458106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497048,-0.000712851) , 
4, -1.87571, 1, 0, 0.479554,-0.0140665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.136807,-0.0678937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217853,-0.0400721) , 
0, 49.0758, 1, 0, 0.17922,-0.242104) , 
2, 43.5861, 1, 0, 0.462166,-0.0272689)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281668,-0.0476788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.165285,-0.041271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567916,0.012334) , 
4, -1.97956, 1, 0, 0.544324,0.0422365) , 
6, -2.90843, 1, 0, 0.526645,0.0243697)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239916,-0.0406631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379533,-0.0106861) , 
0, 40.268, 1, 0, 0.319436,-0.105875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67019,0.0168677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354325,-0.00816275) , 
1, 11.8489, 1, 0, 0.536022,0.0282492) , 
2, -19.7966, 1, 0, 0.500568,0.00629391)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.158063,-0.0556599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470578,0.0133262) , 
6, 0.119606, 1, 0, 0.275703,-0.140738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770119,0.0266364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473436,-0.00114628) , 
1, 4.44425, 1, 0, 0.540945,0.0217823) , 
3, 0.149225, 1, 0, 0.514314,0.00546482)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477394,-0.0366105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545655,0.0106112) , 
1, 0.989443, 1, 0, 0.539594,0.0298218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335201,-0.0397946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390569,0.00294091) , 
1, 15.7973, 1, 0, 0.347746,-0.142179) , 
2, 12.6815, 1, 0, 0.508961,0.00235871)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429296,-0.0101098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192763,-0.045247) , 
4, 0.991025, 1, 0, 0.361298,-0.0919052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548721,0.00617816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326426,-0.0457238) , 
7, 3.05538, 1, 0, 0.526429,0.00577582) , 
3, 0.350158, 1, 0, 0.471248,-0.026866)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413037,-0.0172498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54896,0.010915) , 
2, 0.381895, 1, 0, 0.459374,-0.0345818) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759878,0.0516003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545865,0.0117786) , 
6, 1.93016, 1, 0, 0.603544,0.1012) , 
6, 1.35746, 1, 0, 0.494395,-0.00159807)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561763,0.0108471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396916,-0.019155) , 
7, -2.43608, 1, 0, 0.453663,-0.039156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748342,0.0258883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461283,0.00148724) , 
1, 6.42129, 1, 0, 0.567741,0.0463191) , 
7, 0.0186295, 1, 0, 0.505125,-0.000597245)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441791,-0.0474786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454474,-0.00469314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642556,0.021248) , 
5, 256.112, 1, 0, 0.511788,0.014439) , 
1, 0.987832, 1, 0, 0.506646,-0.001277)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428117,-0.0408077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521716,0.00404574) , 
1, 0.988213, 1, 0, 0.513712,0.0014583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.203598,-0.0526574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52535,0.0039386) , 
6, -1.58991, 1, 0, 0.336083,-0.139007) , 
2, 14.4072, 1, 0, 0.490391,-0.0169838)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41819,-0.0121611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272538,-0.0474159) , 
5, 208.676, 1, 0, 0.347886,-0.135801) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593162,0.0172112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472448,-0.00657689) , 
6, -0.497439, 1, 0, 0.516224,0.00958363) , 
6, -2.75356, 1, 0, 0.502753,-0.00205089)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677824,0.0414001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418705,-0.0126595) , 
6, -2.52058, 1, 0, 0.436919,-0.0409518) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758325,0.0342888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514713,0.00176013) , 
3, 0.54375, 1, 0, 0.576441,0.0439639) , 
0, 40.0519, 1, 0, 0.512979,0.00533983)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539588,0.00473995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262624,-0.0268687) , 
4, 1.54667, 1, 0, 0.510623,0.00653439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281121,-0.0527612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49015,-0.00409467) , 
7, 2.60742, 1, 0, 0.422996,-0.089151) , 
7, 2.31606, 1, 0, 0.487994,-0.0181762)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606571,0.0236843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509563,-0.00351593) , 
6, -2.0553, 1, 0, 0.524592,0.00327888) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130496,-0.0467737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156509,-0.0334757) , 
7, -0.260336, 1, 0, 0.143316,-0.169374) , 
1, 34.0736, 1, 0, 0.500596,-0.00758723)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359027,-0.0291786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419698,0.0157862) , 
1, 8.8896, 1, 0, 0.384866,-0.0497303) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626067,0.0144622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407536,-0.00918164) , 
4, 0.940848, 1, 0, 0.560962,0.0334968) , 
4, -0.987746, 1, 0, 0.524733,0.0163741)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.221184,-0.0341005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578315,0.0109373) , 
3, 0.10153, 1, 0, 0.551052,0.0337352) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.145852,-0.0601779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366557,-0.0132789) , 
6, -1.97766, 1, 0, 0.294179,-0.131072) , 
3, 0.89123, 1, 0, 0.519354,0.013398)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295336,-0.024707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522776,-0.000853704) , 
2, -17.8898, 1, 0, 0.481201,-0.0229576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387592,-0.0455375) , 
5, 615.893, 1, 0, 0.476108,-0.0327618)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399884,-0.0244692) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399924,-0.0120124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592196,0.0129916) , 
4, -0.860823, 1, 0, 0.541431,0.0277456) , 
7, -3.15426, 1, 0, 0.526907,0.0137252)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345346,-0.0182921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587096,0.0115359) , 
2, -15.8033, 1, 0, 0.538733,0.0249527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288792,-0.0634811) , 
5, 695.232, 1, 0, 0.530197,0.0148122)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215173,-0.0600939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364672,-0.00913118) , 
1, 3.46169, 1, 0, 0.32846,-0.0988131) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553243,0.00551882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163778,-0.0573365) , 
3, 1.1794, 1, 0, 0.531742,0.00827496) , 
2, -13.074, 1, 0, 0.481975,-0.0179419)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.789906,0.0334937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468746,-0.0288032) , 
2, 8.11277, 1, 0, 0.737616,0.0971408) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747464,0.0462695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400677,-0.0114355) , 
7, -3.15426, 1, 0, 0.416801,-0.0388547) , 
1, 5.43251, 1, 0, 0.509511,0.000445469)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52712,0.00101962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266882,-0.0414114) , 
2, 49.3773, 1, 0, 0.518499,-0.00194695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0956043,-0.0466894) , 
1, 37.037, 1, 0, 0.501353,-0.00924187)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581204,0.0110913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399337,-0.0115529) , 
4, 0.882669, 1, 0, 0.535731,0.0239322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142846,-0.0366641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186458,-0.00923328) , 
4, 0.364371, 1, 0, 0.15669,-0.111187) , 
1, 31.6045, 1, 0, 0.498693,0.010729)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468805,-0.00872094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610485,0.0119455) , 
4, 0.08115, 1, 0, 0.527067,-0.00127625) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225086,-0.0474056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250998,-0.0140542) , 
1, 7.90654, 1, 0, 0.239671,-0.128757) , 
4, 1.37234, 1, 0, 0.486075,-0.0194591)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368669,-0.00337058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710413,0.0371596) , 
3, 0.233832, 1, 0, 0.512472,0.0622065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534705,-0.000333933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382749,-0.0337725) , 
7, 2.2467, 1, 0, 0.495507,-0.0400527) , 
3, 0.355721, 1, 0, 0.499874,-0.0137276)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247314,-0.0589045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480277,-0.00998085) , 
7, -2.87836, 1, 0, 0.449764,-0.0732237) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521265,-0.000458042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637505,0.0337453) , 
4, 0.664982, 1, 0, 0.551011,0.0361975) , 
6, -0.116093, 1, 0, 0.498783,-0.0202466)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457249,-0.0106327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565553,0.0118858) , 
6, -0.0386391, 1, 0, 0.506363,-0.00203444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25986,-0.0928099) , 
5, 668.094, 1, 0, 0.495995,-0.0185956)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238913,-0.0482877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510619,-0.00138778) , 
6, -2.83113, 1, 0, 0.485896,-0.0247695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764005,0.0516105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600668,0.0134226) , 
6, 0.19363, 1, 0, 0.684283,0.148423) , 
7, 2.66645, 1, 0, 0.510527,-0.00326637)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502266,-0.0234764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559722,0.0109382) , 
1, 1.48206, 1, 0, 0.552266,0.0295512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443898,-0.00430771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183026,-0.0634004) , 
5, 414.421, 1, 0, 0.390766,-0.0753994) , 
4, 0.656611, 1, 0, 0.49936,-0.00482972)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211181,-0.0278526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663933,0.0461985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557678,0.00588312) , 
4, -1.20561, 1, 0, 0.565571,0.0395681) , 
4, -1.75622, 1, 0, 0.537577,0.027237)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38062,-0.0241379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552709,0.00654621) , 
5, 54.9365, 1, 0, 0.535312,0.0145488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.84663,0.0602626) , 
5, 664.684, 1, 0, 0.545424,0.0229427)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495007,-0.0226594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556116,0.00735921) , 
1, 0.988231, 1, 0, 0.550797,0.0206987) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194475,-0.0632087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331035,-0.0143818) , 
1, 9.38247, 1, 0, 0.266147,-0.17073) , 
2, 19.8192, 1, 0, 0.516889,-0.00210506)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275717,-0.0242621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537795,0.00155605) , 
3, 0.230717, 1, 0, 0.491503,-0.0127602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374859,-0.0430518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453314,0.0109698) , 
1, 13.829, 1, 0, 0.395803,-0.125019) , 
6, 1.82291, 1, 0, 0.46862,-0.0396026)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508686,-0.000266449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321294,-0.0550008) , 
4, -0.222663, 1, 0, 0.388623,-0.156622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535282,0.00440733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23923,-0.0331318) , 
2, 22.2878, 1, 0, 0.500745,0.000295214) , 
7, -2.91114, 1, 0, 0.486417,-0.0197576)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658887,0.010053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372073,-0.0228298) , 
4, 1.0811, 1, 0, 0.598602,0.0117535) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407576,-0.00309607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259475,-0.0302106) , 
7, -1.08533, 1, 0, 0.30964,-0.0945544) , 
1, 11.8521, 1, 0, 0.481394,-0.0313668)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526358,-0.00492334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601754,0.0220643) , 
7, -1.38971, 1, 0, 0.5774,0.0592242) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432751,-0.0201258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512047,0.00921328) , 
4, 0.568343, 1, 0, 0.454888,-0.0520341) , 
6, -0.426417, 1, 0, 0.503389,-0.00798779)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577399,-0.000549327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468034,0.0226622) , 
1, 12.3472, 1, 0, 0.539059,0.032835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235978,-0.0635502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525472,-0.00205725) , 
7, 1.6717, 1, 0, 0.488832,-0.0438689) , 
7, 1.46532, 1, 0, 0.520874,0.00506393)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72391,0.0462794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527734,0.00359343) , 
5, 361.738, 1, 0, 0.676148,0.155697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282357,-0.0321892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499593,-0.00788735) , 
4, -1.09369, 1, 0, 0.454783,-0.0573743) , 
6, -1.74497, 1, 0, 0.490683,-0.0228195)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525647,0.0165174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458613,-0.0121847) , 
5, 101.074, 1, 0, 0.477347,-0.0183817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640549,-0.0128611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666824,0.0318992) , 
1, 3.94975, 1, 0, 0.660987,0.101924) , 
5, 388.378, 1, 0, 0.505147,-0.000169292)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497453,-0.0276313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471853,0.00196449) , 
1, 6.91471, 1, 0, 0.484206,-0.0522146) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794715,0.0538089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53128,0.00354234) , 
6, -2.28795, 1, 0, 0.562102,0.0410249) , 
4, 0.243968, 1, 0, 0.515262,-0.0150416)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654567,0.0333412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399473,-0.0117044) , 
6, 1.82287, 1, 0, 0.588527,0.0956893) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376755,-0.0314611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531173,0.00293057) , 
6, -1.90031, 1, 0, 0.496666,-0.0214439) , 
5, 99.0373, 1, 0, 0.516648,0.00403539)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521257,0.00240269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734979,0.0353062) , 
5, 351.105, 1, 0, 0.560703,0.0372843) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364567,-0.0259006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.705566,0.0197149) , 
5, 455.759, 1, 0, 0.404581,-0.0894473) , 
6, 1.66772, 1, 0, 0.518957,0.00339764)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534339,0.00597574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379977,-0.0285056) , 
7, 3.29658, 1, 0, 0.519335,0.0113826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534841,0.00463649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371735,-0.0421322) , 
5, 218.986, 1, 0, 0.454333,-0.0821168) , 
0, 57.083, 1, 0, 0.497443,-0.0201066)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556989,-0.00535442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.76607,0.0290991) , 
0, 46.0943, 1, 0, 0.650518,0.0379627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308566,-0.054481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438764,-0.00335458) , 
1, 6.71314, 1, 0, 0.423438,-0.041645) , 
1, 5.43271, 1, 0, 0.493354,-0.0171344)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421312,-0.0191593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489873,-0.000512016) , 
7, -1.26519, 1, 0, 0.462236,-0.0352033) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806793,0.0409343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569466,0.00117527) , 
7, 2.39268, 1, 0, 0.683801,0.0861738) , 
5, 506.891, 1, 0, 0.478149,-0.0264858)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673657,0.0310579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560282,0.00828304) , 
7, -0.579953, 1, 0, 0.608854,0.0788356) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686604,0.064078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481414,-0.00740752) , 
3, 0.151185, 1, 0, 0.492812,-0.0149777) , 
6, -0.426582, 1, 0, 0.535364,0.0194229)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295045,-0.0437676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431125,-0.00792604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576542,0.00791686) , 
2, -1.80029, 1, 0, 0.501441,-0.00115447) , 
6, -2.90844, 1, 0, 0.48854,-0.0136035)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503973,0.000156081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700783,0.0439279) , 
6, -0.167764, 1, 0, 0.527625,0.0229871) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707695,0.019935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399229,-0.0179561) , 
1, 3.45887, 1, 0, 0.445583,-0.0557119) , 
6, 0.349333, 1, 0, 0.489865,-0.0132348)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35424,-0.0397395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634073,-0.00012874) , 
2, -15.5831, 1, 0, 0.582732,-0.0338423) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543378,0.0292546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512793,0.00800375) , 
0, 28.8642, 1, 0, 0.520685,0.0593887) , 
1, 4.44435, 1, 0, 0.537738,0.0337652)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435137,-0.024798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535247,0.00532966) , 
6, -0.348907, 1, 0, 0.488259,-0.0388769) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632888,0.0162659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310939,-0.00861758) , 
1, 16.2948, 1, 0, 0.545099,0.0409991) , 
7, -0.521077, 1, 0, 0.517327,0.00197208)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545415,0.00943515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510176,-0.00807665) , 
3, 0.447026, 1, 0, 0.523853,-0.00570984) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.200556,-0.0738501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258972,-0.0223966) , 
1, 6.91594, 1, 0, 0.241834,-0.163243) , 
2, 22.6889, 1, 0, 0.493435,-0.0227011)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677711,0.0121399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435771,-0.0195682) , 
1, 3.84119, 1, 0, 0.501401,-0.0509663) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669266,0.0456984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314987,-0.00288994) , 
1, 21.035, 1, 0, 0.437996,0.0663722) , 
1, 14.8149, 1, 0, 0.484502,-0.0196917)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432171,-0.0157284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52552,0.00149217) , 
5, 117.809, 1, 0, 0.493498,-0.0194865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690938,0.0425492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444329,-0.00373551) , 
2, 6.79282, 1, 0, 0.578232,0.0947808) , 
6, 2.44347, 1, 0, 0.49995,-0.0107858)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415627,-0.0148355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692425,0.0457491) , 
6, 1.97762, 1, 0, 0.448224,-0.0345234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720716,0.0308965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404849,-0.00661815) , 
3, 0.753073, 1, 0, 0.610297,0.0754315) , 
0, 40.1826, 1, 0, 0.533357,0.0232332)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47799,-0.00970234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595832,0.0191841) , 
6, -0.767449, 1, 0, 0.538764,0.0206964) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425626,-0.0396695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406292,-0.00631099) , 
1, 6.90847, 1, 0, 0.414581,-0.0892378) , 
6, 2.05563, 1, 0, 0.513039,-0.00207692)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.186445,-0.0370799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515218,-0.00190484) , 
0, 14.5401, 1, 0, 0.481305,-0.0233792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392316,-0.0307292) , 
7, 3.2551, 1, 0, 0.473793,-0.0333326)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582876,0.00511939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2658,-0.0203344) , 
1, 19.2596, 1, 0, 0.512845,-0.00173068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323223,-0.0426287) , 
7, 3.40527, 1, 0, 0.500204,-0.0141822)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518314,-0.00440278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391689,-0.0345059) , 
4, 0.874663, 1, 0, 0.500247,-0.0387876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594167,0.032705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31312,-0.00234138) , 
4, 1.71689, 1, 0, 0.460091,0.0717171) , 
4, 1.21327, 1, 0, 0.49469,-0.0234954)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490835,-0.0249386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470085,0.00772292) , 
1, 7.40777, 1, 0, 0.480166,-0.0349343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710505,0.0352241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446342,0.00312665) , 
3, 0.74158, 1, 0, 0.645613,0.118552) , 
6, 1.20245, 1, 0, 0.521674,0.00357285)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315906,-0.0410374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561102,0.00516814) , 
6, 0.737375, 1, 0, 0.398576,-0.115655) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749094,0.0384202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464579,-0.00690975) , 
7, -2.28251, 1, 0, 0.48593,-0.0153094) , 
7, -2.76687, 1, 0, 0.471727,-0.0316245)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553566,0.00658362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297688,-0.0229021) , 
4, 1.30492, 1, 0, 0.515873,0.00977453) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330549,-0.0359932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626455,0.0122906) , 
5, 465.949, 1, 0, 0.405155,-0.106625) , 
7, 2.48827, 1, 0, 0.494641,-0.0125475)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759792,0.0276378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.898407,0.0582016) , 
5, 227.67, 1, 0, 0.815186,0.156195) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366893,-0.0171271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497662,0.000437103) , 
5, 193.157, 1, 0, 0.427917,-0.038532) , 
1, 3.45841, 1, 0, 0.48394,-0.0103623)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472871,-0.00325868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229898,-0.070587) , 
5, 320.014, 1, 0, 0.461001,-0.0278072) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731944,0.0265837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336295,-0.0217757) , 
2, 25.9979, 1, 0, 0.652291,0.0695484) , 
5, 345.297, 1, 0, 0.497471,-0.00924576)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423607,0.000560831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167249,-0.0442804) , 
4, 0.201625, 1, 0, 0.266409,-0.117805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619417,0.0184161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497079,-0.00197949) , 
7, -0.709162, 1, 0, 0.546325,0.0265017) , 
2, -30.8508, 1, 0, 0.509628,0.00758312)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291053,-0.0172927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680135,0.0439322) , 
2, -6.60058, 1, 0, 0.517006,0.0833541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67519,0.00837419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3681,-0.0172179) , 
1, 8.39543, 1, 0, 0.507623,-0.0261159) , 
4, -0.832854, 1, 0, 0.509411,-0.00525906)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509095,0.0237322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44238,-0.0188362) , 
4, -1.24962, 1, 0, 0.456926,-0.0429054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532125,0.00455148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752699,0.0510737) , 
7, 2.95241, 1, 0, 0.550314,0.0356697) , 
4, -0.0215628, 1, 0, 0.503196,-0.00397439)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.178047,-0.0454415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502802,0.0133998) , 
6, 0.116459, 1, 0, 0.27675,-0.119883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554029,0.0082051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407437,-0.032822) , 
7, 2.95344, 1, 0, 0.536955,0.0140509) , 
3, 0.201516, 1, 0, 0.497829,-0.00608834)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327172,-0.0294182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.657846,0.0361349) , 
6, 2.05555, 1, 0, 0.364776,-0.0936101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539827,0.00102093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318193,-0.040005) , 
6, 2.6761, 1, 0, 0.517155,-0.014241) , 
4, -0.586708, 1, 0, 0.469001,-0.0393233)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659123,0.0377923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475406,-0.00210615) , 
6, 0.116763, 1, 0, 0.55731,0.0686722) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39295,-0.0257902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548295,0.00471453) , 
6, -1.82274, 1, 0, 0.510809,-0.0114505) , 
4, -0.319959, 1, 0, 0.527949,0.0180823)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565461,0.0119487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454725,-0.00929245) , 
7, 1.73593, 1, 0, 0.527624,0.0196655) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35158,-0.0328698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590428,0.00922712) , 
5, 163.607, 1, 0, 0.465971,-0.0568354) , 
6, 1.66775, 1, 0, 0.512047,0.000337824)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489332,-0.00281161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.791061,0.0401727) , 
5, 495.982, 1, 0, 0.506681,-0.0015968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438561,-0.048073) , 
5, 667.997, 1, 0, 0.503619,-0.0104023)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405426,-0.0154451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.65733,0.0132195) , 
5, 350.144, 1, 0, 0.453165,-0.0433013) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429873,-0.00861764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62589,0.0251181) , 
6, -1.27986, 1, 0, 0.557549,0.054961) , 
4, 0.33549, 1, 0, 0.491371,-0.00733593)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266764,-0.0382999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312689,0.00193693) , 
1, 13.8283, 1, 0, 0.279524,-0.118585) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580542,0.00677257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36584,-0.0230155) , 
7, 3.06765, 1, 0, 0.552372,0.0122337) , 
2, -13.4742, 1, 0, 0.483354,-0.0208575)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493781,0.00371917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.778881,0.0645106) , 
6, -1.53722, 1, 0, 0.529536,0.047738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503674,-0.00155919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442309,-0.0346898) , 
5, 412.771, 1, 0, 0.492434,-0.0328407) , 
6, -1.20198, 1, 0, 0.503141,-0.00958555)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737091,0.0510333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.70846,0.0207869) , 
5, 414.774, 1, 0, 0.726633,0.176611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438711,-0.0267151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50169,0.00383955) , 
7, -1.80817, 1, 0, 0.485341,-0.0178031) , 
7, -2.91375, 1, 0, 0.507176,-0.000209891)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7594,0.0484682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489181,-0.00114861) , 
6, -2.21009, 1, 0, 0.517141,0.0170387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394451,-0.0412598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441735,-0.00379286) , 
1, 6.41819, 1, 0, 0.424675,-0.0742457) , 
2, 5.51982, 1, 0, 0.490826,-0.00894031)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306276,-0.052469) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533941,0.00442391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426708,-0.0151455) , 
6, 1.66777, 1, 0, 0.505947,-0.00305003) , 
7, -3.30579, 1, 0, 0.493127,-0.0176222)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431502,-0.0286196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.820853,0.0341982) , 
1, 0.780783, 1, 0, 0.709714,0.0546462) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394281,-0.0214897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450797,-0.000244757) , 
7, -1.80616, 1, 0, 0.429559,-0.0368419) , 
1, 3.95102, 1, 0, 0.486961,-0.0180964)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473369,-0.00121256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676838,0.0221703) , 
4, -0.256064, 1, 0, 0.560762,0.036342) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361734,-0.0321285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390002,0.0223682) , 
1, 13.3322, 1, 0, 0.368052,-0.0915049) , 
4, 0.882669, 1, 0, 0.509871,0.00258011)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759274,0.0555072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574816,0.00776942) , 
0, 36.7838, 1, 0, 0.638757,0.10798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458583,-0.0142142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514027,0.00549934) , 
6, 0.460395, 1, 0, 0.484446,-0.0218917) , 
6, -2.28799, 1, 0, 0.503127,-0.0061696)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438887,0.00540777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232951,-0.0457862) , 
4, -1.19379, 1, 0, 0.339579,-0.0867006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588524,0.00569525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294295,-0.0180357) , 
1, 17.2844, 1, 0, 0.506633,-0.00459839) , 
4, -0.925795, 1, 0, 0.468353,-0.0234121)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470094,-0.00460311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640689,0.0261829) , 
5, 262.834, 1, 0, 0.502839,0.00587121) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310777,-0.0590213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59947,-0.00436943) , 
5, 492.797, 1, 0, 0.459854,-0.136785) , 
5, 413.821, 1, 0, 0.495248,-0.01932)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502347,-0.00630193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304836,-0.042594) , 
6, 1.8229, 1, 0, 0.454031,-0.066066) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460159,-0.00507661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655806,0.0233402) , 
2, -1.80029, 1, 0, 0.560697,0.0400514) , 
7, 0.154949, 1, 0, 0.505096,-0.0152637)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332617,-0.0324027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475721,-0.000655116) , 
7, -1.94039, 1, 0, 0.441234,-0.0365322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663846,0.0337853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558498,-0.000446496) , 
6, 0.0389427, 1, 0, 0.607685,0.064306) , 
5, 269.4, 1, 0, 0.487188,-0.00869257)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.252758,-0.0259293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508014,0.00173693) , 
2, -16.2693, 1, 0, 0.459735,-0.0146632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280919,-0.0580399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516777,-0.0123609) , 
4, -0.0710201, 1, 0, 0.408506,-0.15045) , 
5, 507.002, 1, 0, 0.453839,-0.0302902)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224475,-0.0530778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465077,-0.00797564) , 
5, 52.1796, 1, 0, 0.440645,-0.0545635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702206,0.0247714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347401,-0.00620237) , 
1, 12.3457, 1, 0, 0.537487,0.0420375) , 
6, 0.581958, 1, 0, 0.477477,-0.0178232)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213465,-0.0340694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500907,-0.00160795) , 
2, -11.5765, 1, 0, 0.442511,-0.034649) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618183,0.0134916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.135338,-0.0397479) , 
1, 28.6416, 1, 0, 0.564544,0.0333285) , 
5, 200.075, 1, 0, 0.497133,-0.00422211)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46522,0.00297007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227325,-0.0588019) , 
0, 37.3795, 1, 0, 0.426302,-0.0319156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674386,0.0409527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546881,-0.00071264) , 
4, -0.452891, 1, 0, 0.580346,0.0426014) , 
0, 39.831, 1, 0, 0.507678,0.00744912)    );
   return;
};

// Clean up
inline void ReadBDT-0.3_fold1::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.3_fold1::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
